CGraphics 関連の最適化
sakura-editor/sakura pull request #1411
Opened 2020-09-26 06:42 UTC by beru

#  PR の目的

描画処理を高速化してCPU負荷を減らすのが目的です。

#998 のリトライです。

##  カテゴリ

- 速度向上

##  PR の背景

### SaveDC と Restore DC の利用

従来実装では `CGraphics` クラスの構築時にクリッピング領域の取得操作が毎回行われており、その処理にいくらか時間を浪費していました。

各種GDIオブジェクトの保存と復帰処理の実装がいくらか煩雑な記述になっていました。このPRでは `SaveDC` と `RestoreDC` を使う事で保存復帰処理を単純化しました。

### CGraphics 型のインスタンスを使いまわす

while ループ内で呼び出す `CEditView::DrawLogicLine` メソッド内で `CGraphics` 型のインスタンスの生成と破棄を 行うのはコストが高いので、ループの外に用意して使いまわすようにしました。

### CGraphics::SetPen の代わりに PushPen, PopPen を使用

`SetPen` の実装では `ClearPen` してから `PushPen` していますが、そうするより `PushPen` と `PopPen` の方が処理内容が少なくなると考えて変更しました。

Performance Profiler で確認すると `_DrawEOL` 内で `gr.SetPen` で処理に時間が掛かっていたのが変更後は `PolyPolyline` に移っていました。サンプリング方式のプロファイラだと処理に時間が掛かっている箇所が厳密には分からないのかもしれません。ただパーセンテージでいうと少し低下しているので効果が少しはあるのではないかと思います。

##  PR のメリット

描画処理が少し速くなります、効果はかなり微妙で体感では分からないぐらいです。

`CGraphics` クラスの実装がシンプルになります。

##  テスト内容

Release x64 ビルドで確認しました。

変更前後の表示内容に違いが無い事を目視で確認しました。

`README.md` を開いてウィンドウを最大化 `redrawcounter.js` マクロを使って処理時間計測を5回実行しました。

変更前 d884ae4d3539382ea3963e4c24b79ba0197c9c0c : 2021ms, 2005ms, 2036ms, 2021ms, 2021ms  
変更後 c9dd8f8d0fe81e28162b5db1624d3d2ff5c9ca78 : 1974ms, 1974ms, 1974ms, 1973ms, 1952ms

`redrawcounter.js` マクロは60回の再描画操作に掛かる時間を測定するスクリプトなので、1回辺りにすると 1ms 未満の僅かな改善という事が分かりました。

##  PR の影響範囲

##  関連 issue, PR

#1405

##  参考資料

https://sourceforge.net/p/sakura-editor/patchunicode/_discuss/thread/8123c88f/21c3/attachment/redrawcounter.js

2020-09-26 09:36 UTC, berryzplus requested changes
基本的に問題ないと思います。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
`size() が 0以外` であるのか `not empty()` なのか、それは好みなのかも知れないですが。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +		if(m_vClippingRgns.size()){
文脈的に `if (true)` って書いてあるのと同じかも？と思ったけど違った・・・。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
これでいいのかあんまし自信がないです。
SelectObjectでHFONTを選択したら、
最終的に元に戻さないといけない（Windows API仕様）んですが、
このロジックで最後のフォントを元に戻したときにちゃんと戻るかどうか自信ないっす。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vFonts.size()){
> `size() が 0以外` であるのか `not empty()` なのか、それは好みなのかも知れないですが。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vPens.size()){
> `size() が 0以外` であるのか `not empty()` なのか、それは好みなのかも知れないですが。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vBrushes.size()){
> `size() が 0以外` であるのか `not empty()` なのか、それは好みなのかも知れないですが。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	size_t nSize = (int)m_vBrushes.size();
ここキャスト要らないっす。

2020-09-26 09:36 UTC, berryzplus commented on sakura_core/view/figures/CFigure_Eol.cpp
> +	gr.PushPen( pColor, 1 );
ここの第 2 引数は、論理ペンの「太さ」を表している気がします。

やってよいかは別にして、HighDPI対応を考慮する必要があるか判断しないとあかんと思います。

2020-09-26 10:13 UTC, beru commented on sakura_core/view/figures/CFigure_Eol.cpp
> +	gr.PushPen( pColor, 1 );
ここの変更ですが `SetPen` の記述の置き換えでその中で呼び出す `PushPen` に 1 を指定しているのでそれに合わせただけです。

線の太さはDPIの考慮うんぬんは本来はそうなんですが、今はされてないですね。するとしてもこのPRでは対応はしない方が良いと思います。

2020-09-26 10:23 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
`SaveDC` で取得した state を使って `RestoreDC` するから問題無いと思います。
とはいえ本当に問題が無い事の根拠というか出典を示せないですが…。

2020-09-26 10:28 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
うーん、上記のコメントの内容だとこちらが何かのアクションを取るべきなのかどうか判断しづらいです。単なる独り言やメモなのかもしれないですが、`Request changes` にしている場合は具体的にどういう変更を望んでいるかを明確にしてほしいです。

`not empty()` という書き方にしていない理由としては好みというより元のコードから記述を引きずっている事が大きいと思います。

2020-09-26 10:29 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> +	size_t nSize = (int)m_vBrushes.size();
確かに！

2020-09-26 10:31 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vPens.size()){
好みなのか他の記述に合わせたのか今となってはよくわかりません。

2020-09-26 10:43 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> -	}
ここの変更ですが `ClearBrush` 側はそのままにしているので整合性が取れていないですね。

2020-09-26 10:47 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> -	}
と思ったらそんな事無かったです。違う branch 見てました。`ClearBrush` の実装も `ClearClipping` と同じような記述に変更してました。

2020-09-26 10:59 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
`DeleteObject` する前に非選択状態にしないといけないという事で良くないかもしれないですね。

このPRのやり方だと `SelectObject` されている状態で `DeleteObject` していてその後に`RestoreDC` してます。
先に `RestoreDC` しておけば `DeleteObject` しても問題無いと思いますが。。

実害があるかどうかは動作確認したりリソースリークしていないか見たりしないと分からないですが、問題のない書き方にするのが一番ですね。

2020-09-26 11:50 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
これは修正依頼じゃないです。

ただ、この記述は好みでやってると思います。

元の記述を活かして修正しただけだとすると `>=1` が消えた理由を説明できないっす。

`if(m_vClippingRgns.size()>=2)`
 　　↓　変更を適用する
`if(m_vClippingRgns.size()>=1)`
 　　↓　C言語の基準で判定式を簡略化する
`if(m_vClippingRgns.size())`

今回削除したコードの中には `if(!m_vClippingRgns.empty())` に相当する記述があるので、
元の記述に合わせましたなら `not empty` になるような気がします。

2020-09-26 11:51 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> -	if(m_vClippingRgns.empty()){
ここにありますね、`not empty()`。

2020-09-26 11:54 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
SelectObjectの呼出しの数があっていればよかったはずです。
RestoreDCでリセットできるかどうかは微妙で、たしか保証されてなかったような。

2020-09-26 11:55 UTC, berryzplus commented on sakura_core/view/figures/CFigure_Eol.cpp
> +	gr.PushPen( pColor, 1 );
PRの趣旨とは関係ないので今回は保留、で了解しました。

2020-09-26 11:57 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> -	if(m_vClippingRgns.empty()){
ちがった！これ `is empty()` やん！

2020-09-26 11:58 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> -	if(!m_vClippingRgns.empty()){
`not empty()` はこれですね。

2020-09-26 12:36 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
( ,,`･ω･´)ﾝﾝﾝ？

なんかやっぱりおかしい気がします。

* push時  
```c++
	HFONT hFontOld = (HFONT)SelectObject(m_hdc, sFont.m_hFont);
	if (m_vFonts.empty()) {
		SFONT sDefaultFont = { { FALSE,FALSE }, hFontOld };
		m_vFonts.push_back(sDefaultFont);
	}
	m_vFonts.push_back(sFont);
```
（初回のみ、配列の先頭に旧FONTを入れる。）
* pop時  
```c++
	if (!m_vFonts.empty()) {
		m_vFonts.pop_back();
		if (!m_vFonts.empty()) {
			const auto& sFont = m_vFonts.back();
			::SelectObject(m_hdc, sFont.m_hFont);
		}
	}
```

ということなんじゃないでしょうか？

2020-09-26 19:04 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
というかどっちでもよくない？って思うんですけど…。

2020-09-26 19:12 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
> RestoreDCでリセットできるかどうかは微妙で、たしか保証されてなかったような。

ここは検索すると `SaveDC`, `RestoreDC` 使うと bkup を `SelectObject` する操作を省略出来るよ～って解説しているサイトがあるにはありますが、MSの公式サイトでそういう記述は見つけられていません。

が、下記の `SaveDC` の解説には、

https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-savedc

> The SaveDC function saves the current state of the specified device context (DC) by copying data describing **selected objects** and graphic modes (such as the bitmap, brush, palette, font, pen, region, drawing mode, and mapping mode) to a context stack.

と書かれているので選択状態は保存されて `RestoreDC` で復帰出来ると期待できます。

ただしこれとは別にまだ `SelectObject` されている状態で `DeleteObject` するのはまずいかもしれないですね。あと`DeleteObject` したのを `SelectObject` もアウトだと思います。前者については Windows 9x 系の古いOSだとリソースリークに繋がるみたいですが、もう環境持ってないので確認出来ません…。

2020-09-26 21:40 UTC, beru commented
`CGraphics` 側に変更を入れるのを取りやめました。変更内容に問題が無いかの判断が難しいのと、あとよくよく考えると `CGraphics` は色々な箇所で使われているので不具合が有った場合の影響範囲が大きい為です。

代わりの対策として EOL 描画で `CreatePen` を毎回せずに `HPEN` を使いまわすようにしました。
お手数ですが再度レビューお願いします。

2020-09-27 06:25 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
> が、下記の `SaveDC` の解説には、
> 
> https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-savedc
> 
> > The SaveDC function saves the current state of the specified device context (DC) by copying data describing **selected objects** and graphic modes (such as the bitmap, brush, palette, font, pen, region, drawing mode, and mapping mode) to a context stack.
> 
> と書かれているので選択状態は保存されて `RestoreDC` で復帰出来ると期待できます。

ここは了解です。（≒RestoreDCは以前のDC状態を復元できる）

ただ、だからpush/popで配列スタックに値を保持する機構をちゃんと作らなくてよいかというと、それは違う気がしていて、push/popはそれっぽく実装するんだけど、Restore時は配列スタック捨てちまいます、な構造がいいように思います。

2020-09-27 06:26 UTC, berryzplus commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
極論すると「好みである」の確認がとれればOKです。

2020-09-27 06:35 UTC, berryzplus reviewed
修正後コード確認しましたが問題なさそうに見えました。

2020-09-27 08:37 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
> +	if(m_vClippingRgns.size()){
!a.empty() より a.size() の方が短くて好みです。

ただ a.empty() の方が a.size() == 0 より好ましいと思います。が、empty の存在を忘れて後者の書き方をすることはありそうです。

2020-09-27 09:06 UTC, beru commented on sakura_core/uiparts/CGraphics.cpp
>  	m_vFonts.push_back(sFont);
CGraphics は元の実装に戻しましたが、Clear系のメソッドではそれに近いことやってますね。記述に統一感が無いですが。

CGraphics の配列スタックの方式って、CGraphics がリソース管理の責務を追いすぎな気がしますが、Push Pop メソッド使ってる箇所も結構あるので今さら違った方式に変えるのも難しいなと感じました。

2020-09-27 09:24 UTC, berryzplus approved these changes
問題ないと思います。

変更の重点が微妙に変化した（≒描画全般の改善⇒改行描画の改善）ので、
改行描画のパフォーマンスに特化した確認ができるようにマクロを改変してみました。
[flash_eol_test.zip](https://github.com/sakura-editor/sakura/files/5288011/flash_eol_test.zip) ← 正規表現で CRLF と行頭を交互に検索し、改行コードを再描画させるマクロです。

|-|コミット|測定結果|
|--|--|--|
|変更前|d884ae4d3539382ea3963e4c24b79ba0197c9c0c|8546ms, 8637ms, 8531ms|
|変更後|0383fec4ab5aec9a4856ec7dbbd590e1db01f1ad|6936ms, 6703ms, 6900ms|

再描画回数は 120回 なので PR本文の数値とは違うんですけど、
1500msくらい改善していることが分かると思います。

2020-09-27 11:27 UTC, merged

2020-09-27 11:32 UTC, beru commented
レビューありがとうございました。Mergeします。

2020-09-27 11:35 UTC, beru commented
> 
> 
> 問題ないと思います。
> 
> 変更の重点が微妙に変化した（≒描画全般の改善⇒改行描画の改善）ので、
> 改行描画のパフォーマンスに特化した確認ができるようにマクロを改変してみました。
> [flash_eol_test.zip](https://github.com/sakura-editor/sakura/files/5288011/flash_eol_test.zip) ← 正規表現で CRLF と行頭を交互に検索し、改行コードを再描画させるマクロです。
> - 	コミット 	測定結果
> 変更前 	[d884ae4](https://github.com/sakura-editor/sakura/commit/d884ae4d3539382ea3963e4c24b79ba0197c9c0c) 	8546ms, 8637ms, 8531ms
> 変更後 	[0383fec](https://github.com/sakura-editor/sakura/commit/0383fec4ab5aec9a4856ec7dbbd590e1db01f1ad) 	6936ms, 6703ms, 6900ms
> 
> 再描画回数は 120回 なので PR本文の数値とは違うんですけど、
> 1500msくらい改善していることが分かると思います。

変更前 の d884ae4 は #1405 が merge される前のものですね。1500 ms の改善のうち 97% くらいは usagisita さんの変更のおかげでしょうね。

2020-09-27 12:47 UTC, berryzplus commented
おお。

2020-09-27 13:05 UTC, berryzplus commented
取り直してみました。

0383fec4ab5aec9a4856ec7dbbd590e1db01f1ad 8212ms, 9466ms, 8362ms, 8571ms, 8705ms

なんかやたらと値がバラついてますが、改行描画の速度にフォーカスした測り方してるので #1405 適用後と比較しても 大きな差が出るのは想定内です。

2020-09-27 17:10 UTC, beru commented
berryzplus さんが確認前後で使用したコミットのSHA-1は古いコミットのものなので、それで確認するとこのPRの変更による効果を捉えられないと思います。

自分の方でも違ったコミットで確認しました。`README.md` ファイルを開いてからウィンドウを最大化して先頭行にカーソル合わせてから `flash_eol_test.js` を実行しました。

変更前 061c902a08b8e60c27843389d317d7f9c7273d5a : 5684, 5668, 5692, 5699, 5699, 5661, 
変更後 ad4537a33b858b4d8955a905eb1841144a88e3ea : 5427, 5469, 5446, 5430, 5446, 5462,

2020-09-27 17:23 UTC, berryzplus commented
ぼくがレビューした時点の古いコミット見てました。

061c902a08b8e60c27843389d317d7f9c7273d5a 6695ms, 7534ms, 7351ms, 6815ms, 7223ms

確かに誤差レベルの改善ですね。残念...orz