[WIP] ダイアログフォント美化
sakura-editor/sakura pull request #1421
Opened 2020-10-03 08:06 UTC by suconbu

#  PR の目的

すべてのダイアログボックスで Windows のシステムフォントを使うようにし文字の見た目を良くします。

※システムフォントではなくエディタと同じフォントの方が適当と思われる部分 (キーワード補完やアウトライン解析など) があります。この点は別の PR で対応したいと考えています。

例：
-|-
-|-
現状 | ![image](https://user-images.githubusercontent.com/11252784/94986485-2ba0e800-059a-11eb-9416-d41d5d2c302b.png)
変更後 | ![image](https://user-images.githubusercontent.com/11252784/94986495-3eb3b800-059a-11eb-869a-9a39d3f7d10f.png)

##  カテゴリ

- 仕様変更

##  PR の背景

##  PR のメリット

ギザギザしていない、きれいな文字が表示されるようになります。
(Windows7 以前ではユーザーが選択しているフォントに依存)

ＭＳ Ｐゴシックが苦手な人も気持ちよく使えるようになるかもしれません。

##  PR のデメリット (トレードオフとかあれば)

特にありません。

##  仕様・動作説明

ダイアログボックスのフォントが「ＭＳ Ｐゴシック」からシステムフォント (下表) に変わります。
OS              | 標準のシステムフォント
----------------|----------------
Windows10       | Yu Gothic UI
Windows8        | Meiryo UI
Windows7/Vista: | メイリオ (メッセージボックス)

##  テスト内容

* システムフォントに「Yu Gothic UI」が設定されている状態 (Windows10 標準状態) で、[すべてのダイアログボックス](https://github.com/suconbu/sakura/wiki/%E3%83%80%E3%82%A4%E3%82%A2%E3%83%AD%E3%82%B0%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E4%B8%80%E8%A6%A7)を表示させ、文字切れや文字重なりがないことを目視確認します。
* フォント変更ツール (参考資料) にてシステムフォントに「Meiryo UI」「メイリオ」を設定し、それぞれ「印刷ページ設定」ダイアログにて文字切れや文字重なりがないことを目視確認します。
→全部確認するのは大変なのでサイズ調整前に一番文字切れが目立っていたものだけとしました。

##  PR の影響範囲

##  関連 issue, PR

GREPダイアログ内の全コンボボックスに対してフォント設定で指定されたフォントを使用する #1400

##  参考資料

* Meiryo UIも大っきらい!!：http://tatsu.life.coocan.jp/MySoft/WinCust/index.html

2020-10-03 08:16 UTC, suconbu commented
`CDialog`を継承していないものたちを引き続き対応中です。

2020-10-03 08:47 UTC, beru reviewed
英語版のリソースファイル `sakura_lang_en_US/sakura_lang_rc.rc` も調整が必要かもしれません。
ただこのPRで一挙にやらないでも良いとは思います。

2020-10-03 18:00 UTC, berryzplus commented
ダイアログリソースのコントロールサイズの指定は、ダイアログ単位というダイアログ作成時に指定したフォントの平均文字幅と平均文字高さから算出される値を基準に書くものなので、フォントを変えるとめちゃめちゃたくさん変更しないといけないんですよ～～～という基本の話題はみなさん分かってるものとしてスルーしときます。（してない。

ツールでもって自動補正させたものを目視でチェックするって方向ですね。いいと思います。

ただ、ダイアログリソースのプロパティで `DS_SHELLFONT` を指定すると、システムフォントに対応させることができる という技術ネタがあるのでcppソース側の変更は要らんかも知れないです。

https://docs.microsoft.com/en-us/windows/win32/dlgbox/dialog-box-styles
https://dev.activebasic.com/egtra/2014/06/16/666/

ここの STYLE に DS_SHELLFONT を指定するです。
https://github.com/sakura-editor/sakura/blob/8f58ec825d2cc29c192725b13e6820fd89718e8d/sakura_core/sakura_rc.rc#L98-L101

何故か「文字コードの指定」ダイアログだけ指定済みでした。
https://github.com/sakura-editor/sakura/blob/8f58ec825d2cc29c192725b13e6820fd89718e8d/sakura_core/sakura_rc.rc#L703-L706

2020-10-04 00:56 UTC, suconbu commented
@beru さん

英語リソースの方は現状で Tahoma フォントが指定されていてきれいでしたので、こちらは現状維持となるよう対応したいと思います。
※仮で英語も Yu Gothic UI にしてみたところでは調整の難しそうな横方向のはみ出しが結構出てしまい、変更してしまうとかなり大変そうな雰囲気でした。

ただ、英語はタブだけがなぜかギザギザなので、こちらは理由を調べてみて軽微修正であれば直しておきたいです。

@berryzplus さん

ダイアログ単位：水平方向は平均文字幅の 1/4、垂直方向は文字高の 1/8 ということから、おそらく現状のテキスト高さには 8 が設定されている箇所が多かったようですが、フォント変更後は以下のような文字切れなどが見られたため各部調整必要となりました。

![image](https://user-images.githubusercontent.com/11252784/95004393-76b40d00-0625-11eb-819d-f5b391062e9a.png)

> ダイアログリソースのプロパティで DS_SHELLFONT を指定すると、システムフォントに対応させることができる

情報ありがとうございます。
しかし、結果は以下の通りでうまくいかずでした。指定できたら便利そうなだけに残念。

現状 (ＭＳ Ｐゴシック) | DS_SHELLFONT + ＭＳ Ｐゴシック | DS_SHELLFONT + MS Shell Dlg
-|-|-
![image](https://user-images.githubusercontent.com/11252784/95004313-9139b680-0624-11eb-940b-436ddfa84faa.png) | ![image](https://user-images.githubusercontent.com/11252784/95004477-736d5100-0626-11eb-91c4-71c90314c34c.png) | ![image](https://user-images.githubusercontent.com/11252784/95004316-96970100-0624-11eb-9496-23ee5c8ccd27.png)

以下の記事では「Windows 2000 default shell font」とあるので、MS UI Gothic + Tahoma が適用されてしまうのかもしれませんね。
https://devblogs.microsoft.com/oldnewthing/20050204-00/?p=36523

2020-10-04 02:30 UTC, suconbu commented
> フォント変更後は以下のような文字切れなどが見られた

リソースで指定されたフォント (= ＭＳ Ｐゴシック) で配置が決定され、実行時に設定されたフォントの大きさは考慮されないことに気づきました。なので↑となるのは当然でした。反映がされるものと誤解をしていました。

リソースに予め Yu Gothic UI を設定しておけば現状より余裕を持った配置となってくれるので、文字重なり予防の点でこの方が良いかもしれません。少し考えてみます。

2020-10-04 10:24 UTC, suconbu commented
リソース側で Yu Gothic UI を設定した場合は全体的なサイズ感が想定以上に変わってしまいました (右端) ので、
今回の PR としては、基本は現状のサイズ/配置のまま問題がある部分について個別調整していく (中央)、で進めようと思います。

現状 (変更前) | 実行時 Yu GothicUI 設定 (+調整) | リソースで Yu Gothic UI 指定
-|-|-
![image](https://user-images.githubusercontent.com/11252784/95011980-e64eea00-066f-11eb-8a51-257ff8d8aa1a.png) | ![image](https://user-images.githubusercontent.com/11252784/95011982-e8b14400-066f-11eb-8227-51bf9e1edb31.png) | ![image](https://user-images.githubusercontent.com/11252784/95011984-eb139e00-066f-11eb-8fb6-b07d43e24fd7.png)

2020-10-04 10:50 UTC, beru commented
> リソース側で Yu Gothic UI を設定した場合は全体的なサイズ感が想定以上に変わってしまいました (右端) ので、
> 今回の PR としては、基本は現状のサイズ/配置のまま問題がある部分について個別調整していく (中央)、で進めようと思います。

おぉ、右端のは結構縦長ですね。

https://forest.watch.impress.co.jp/docs/shseri/rewin10/1011993.html

`Yu Gothic UI` は縦長にデザインされた書体という事を今まで知りませんでした。。

ユーザーの好みに合わせて設定画面で選択できるようにするのが良いんでしょうか？ただリソースダイアログに設定したフォントによってダイアログ内のコントロールの最適な位置やサイズが変わるとなると、実行時に設定する方法でも課題は残りそうですね。。

2020-10-04 16:02 UTC, suconbu commented
> ユーザーの好みに合わせて設定画面で選択できるようにするのが良いんでしょうか？ただリソースダイアログに設定したフォントによってダイアログ内のコントロールの最適な位置やサイズが変わるとなると、実行時に設定する方法でも課題は残りそうですね。。

ダイアログのフォントについてはユーザーが自由に選べるようにするよりは、システムに合わせる (タイトルバーやメニュー等と統一する) の方が良いかなと個人的には考えていました。
HTML などのような動的に再配置する仕組みがない中、実行時にフォント設定するとなるとレイアウトの問題がおきるリスクは避けられない気がしますので、できるだけ自由度は少ない方向が安全というところですね。

幸い (？) Windows8 以降ではユーザーが気軽にフォント変更できないようになりましたので、各 OS バージョンでの標準フォントにて目視チェックしておけば大丈夫なはず、という目論見でいます。

……とはいえ、ＭＳ Ｐゴシック基準で配置されたものにサイズ感の違うフォントが載る点、気持ち悪さは残る気がしますので、いつか Yu Gothic UI などを基準として全体的に再配置すべきかもしれません。

2020-10-04 16:36 UTC, suconbu commented
> 英語はタブだけがなぜかギザギザなので、こちらは理由を調べてみて軽微修正であれば直しておきたいです。

こちらはまだ原因特定できておらず、おそらく今回は見送りとなりそうです。

2020-10-04 22:24 UTC, beru commented
動かしてみましたが、特に問題無さそうですね。文字が前より少し細って見えますが綺麗になったとおもいます。

2020-10-05 04:08 UTC, berryzplus commented
> ……とはいえ、ＭＳ Ｐゴシック基準で配置されたものにサイズ感の違うフォントが載る点、気持ち悪さは残る気がしますので、いつか Yu Gothic UI などを基準として全体的に再配置すべきかもしれません。

変えるなら `FONT 9, "ＭＳ Ｐゴシック"` を変えたいなぁ、とわがまま言ってみます。

vs2017 の最新版で新規ダイアログリソースを追加するとこうなるです。

```c++
IDD_DIALOG1 DIALOGEX 0, 0, 311, 177
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION "Dialog"
FONT 8, "MS Shell Dlg", 400, 0, 0x1
BEGIN
    DEFPUSHBUTTON   "OK",IDOK,200,156,50,14
    PUSHBUTTON      "キャンセル",IDCANCEL,254,156,50,14
END
```

`DS_SETFONT | DS_FIXEDSYS` は `DS_SHELLFONT` と同じ意味です。
https://devblogs.microsoft.com/oldnewthing/20050207-00/?p=36513

`DS_SHELLFONT` + `MS Shell Dlg` を指定したときの効果は、システムのUIフォントが使われる、です。
古い文献には `MS UI Gothic` になると書いてあるものもありますが、xpのUIフォントはそれなんで合ってます。

気が向いたらそちらのアプローチでPRおこしてみようかな、と思います。

2020-10-05 11:58 UTC, berryzplus commented
> `DS_SHELLFONT` + `MS Shell Dlg` を指定したときの効果は、システムのUIフォントが使われる

何故だ！そんな挙動にはならん！ｗ

2020-10-05 13:41 UTC, suconbu commented
> 何故だ！そんな挙動にはならん！ｗ

タイトルバー等と同じフォントにならないですよね。。
「MS Shell Dlg」は実際のシステムフォントとは関係なしに XP, 7, Vista (おそらく 8, 10 でも？) の日本語環境では MS UI Gothic に割り当てられてしまうようです。
https://docs.microsoft.com/en-us/windows/win32/intl/using-ms-shell-dlg-and-ms-shell-dlg-2

2020-10-05 14:03 UTC, suconbu commented
動作確認中、ファイル->印刷ページ設定 を開いて閉じるとフォントがおかしくなる現象を見つけたため修正中です。
キャッシュした共有のフォントハンドルが CDlgPrintSetting::OnDestroy で破棄されてしまっている気がします。

2020-10-06 05:04 UTC, berryzplus reviewed
気付いたことコメントしてみました。

2020-10-06 05:04 UTC, berryzplus commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
windowsがマルチDPIに対応しているので、ラップする関数を作るならマルチDPI対応の検討をしとくべきだと思います。旧バッチの適用なら仕方ないですが、新規作成ならマルチDPI対応を作ったうえで固定DPI対応版を用意するか検討したいっす。

2020-10-06 05:04 UTC, berryzplus commented on sakura_core/util/window.cpp
> +	if( wcsncmp_literal( CSelectLang::getDefaultLangString(), _T("Japanese" ) ) != 0 ){
これって必要ですかね？

むしろ現状で対応できてないのは日本語版のほうで、英語版は MS UI Gothic なんじゃなかったでしたっけ。

2020-10-06 15:09 UTC, suconbu commented on sakura_core/util/window.cpp
> +	metrics.cbSize = sizeof( metrics );
習慣によるところですが、可読性確保とメンバ順序依存になるのを嫌い個別代入としていました。
※C++20 になればメンバ名指定で初期化できるようでした
https://cpprefjp.github.io/lang/cpp20/designated_initialization.html

2020-10-06 15:25 UTC, suconbu commented on sakura_core/util/window.cpp
> +	if( wcsncmp_literal( CSelectLang::getDefaultLangString(), _T("Japanese" ) ) != 0 ){
この条件分岐は、[ここ](https://github.com/sakura-editor/sakura/pull/1421#issuecomment-703183341)の beru さん宛てコメントに対応する変更になります。

現状、英語版ダイアログリソースは Tahoma フォント指定になっていてアンチエイリアスが効いた状態でしたので、今回はそのままで良しとしました。

2020-10-06 15:38 UTC, suconbu commented
> 動作確認中、ファイル->印刷ページ設定 を開いて閉じるとフォントがおかしくなる現象を見つけたため修正中です。

こちらは https://github.com/sakura-editor/sakura/pull/1421/commits/1283afa2ea583d80ad821bb3e75983bda0d15a33 にて修正しました。
`WM_SETFONT`した直後に`WM_GETFONT`しても設定したフォントハンドルは取得されないというトラップに引っ掛かっていました。

2020-10-06 15:38 UTC, berryzplus commented on sakura_core/util/window.cpp
> +	metrics.cbSize = sizeof( metrics );
> 習慣によるところですが、可読性確保とメンバ順序依存になるのを嫌い個別代入としていました。

まぁ、可読性確保、と言われたら好きにしてくださいっすｗ

`cbSize` を持つ構造体は、将来的な拡張（≒メンバの追加）を見越して設計されています。
戦略的な設計なので、先頭32bitの前にメンバが追加されることはないと考えてよいと思います。

個人的には、これをやらない範囲なら害はないんじゃないかと思ってます。

```c++
    NONCLIENTMETRICS metrics:
    ::ZeroMemory( &metrics, sizeof( NONCLIENTMETRICS ) );
```

これのどこが悪い、と言われるとキツいです・・・。

2020-10-06 15:58 UTC, suconbu commented on sakura_core/util/window.cpp
> +	if( !SystemParametersInfo( SPI_GETNONCLIENTMETRICS, 0, &metrics, 0 ) ) {
コンパイル通らないと思ったら、利用できるのがターゲットが Windows10 以降からのようでした。
```cpp
#if(WINVER >= 0x0605)  // 0x0601
WINUSERAPI
_Success_(return != FALSE)
BOOL
WINAPI
SystemParametersInfoForDpi(
```

2020-10-06 16:09 UTC, suconbu commented on sakura_core/util/window.cpp
> +	metrics.cbSize = sizeof( metrics );
この`NONCLIENTMETRICS`についてはおっしゃる通り心配はないと思いますので初期化子でやっておきます。

2020-10-07 00:21 UTC, suconbu commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
この関数についてマルチDPI対応版/固定DPI対応版のイメージがつきませんでした。
現状の`nHeight`は論理ピクセル単位ですが、これとは別に物理ピクセル単位を入力できる版を用意する、というような感じでしょうか？？

2020-10-07 01:55 UTC, berryzplus commented on sakura_core/util/window.cpp
> +	if( !SystemParametersInfo( SPI_GETNONCLIENTMETRICS, 0, &metrics, 0 ) ) {
一旦保留して `ForDPI` なし版でいきますか・・・

> ```c++
> #if(WINVER >= 0x0605)  // 0x0601
> ```

ただ、0x0605ってバージョンは謎っすね。
https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=vs-2019

マニュアルによると win 10 1607 以降 only ってことらしいです。
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfofordpi

2020-10-07 02:08 UTC, berryzplus commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
マルチDPI対応版APIが使えなくなった時点でこのコメントは意味を失いました。

`LONG nHeight` に気づかなかったので、`UINT dpi` を追加したらいいかな？と思っていました。

システムフォントにはサイズを含むような気がします。
任意の高さを指定できてしまうと別なフォントを作ってしまうようなｗ

「論理単位」に対応する実際の大きさを表す用語は「デバイス単位」と思われます。

GDIのマッピングモードで変えられますが、「論理単位：デバイス単位＝１：１」で使う人が多いような気がします。ディスプレイのデバイス単位って、つまりピクセルですから。

2020-10-07 16:46 UTC, suconbu commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
> 任意の高さを指定できてしまうと別なフォントを作ってしまうようなｗ

確かにそうですね。あくまでシステムフォント「風」なものを提供する関数なので、関数名は再考の余地ありかもしれません。少し検討してみますがいいもの浮かばなければこのままとさせて下さい。

論理単位、デバイス単位、それと DPI の関係については以下のように理解を持ちましたが、間違っていないでしょうかね？
「論理単位」-- マッピングモード適用 --> 「デバイス単位」 -- DPI 倍率適用 --> 「ピクセル」

2020-10-08 00:45 UTC, suconbu commented on sakura_core/util/window.cpp
> +	NONCLIENTMETRICS metrics = { CCSIZEOF_STRUCT( NONCLIENTMETRICS, lfMessageFont ) };
既存コードに気になるコメントを見つけたため念のため合わせました。
https://github.com/sakura-editor/sakura/search?q=NONCLIENTMETRICS

2020-10-08 00:47 UTC, suconbu commented on sakura_core/util/window.cpp
> +	key << lfFont.lfHeight << " "
フェイス名＋高さのみではキーとして不十分であったため見直しました。

2020-10-08 02:09 UTC, berryzplus commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
> > 任意の高さを指定できてしまうと別なフォントを作ってしまうようなｗ
> 
> 確かにそうですね。あくまでシステムフォント「風」なものを提供する関数なので、関数名は再考の余地ありかもしれません。少し検討してみますがいいもの浮かばなければこのままとさせて下さい。

これは `システムフォント「風」` で納得です。

> 論理単位、デバイス単位、それと DPI の関係については以下のように理解を持ちましたが、間違っていないでしょうかね？
> 「論理単位」-- マッピングモード適用 --> 「デバイス単位」 -- DPI 倍率適用 --> 「ピクセル」

設計で決めた大きさ(96dpi想定のpx値) -- DPI倍率適用 -- 論理単位 -- マッピング適用 -- デバイス単位

このへんを見たらイメージ付くかも。
https://www.tokovalue.jp/function/SetMapMode.htm
アプリは通常、`MM_TEXT`で変換しとります。

2020-10-08 10:04 UTC, suconbu commented on sakura_core/util/window.cpp
> +HFONT GetSystemFont( LONG nHeight )
すいません、ありがとうございます。分かりました。

今回だと DPI 倍率適用済みの値が入力され、そのサイズでフォント作成するので問題ないですが、
将来、システムフォントそのままのサイズが欲しい！となった時には、DPI 値を入力引数に加えつつ SystemParametersInfoForDpi を呼ぶ、呼べないなら CDPI クラス使ってサイズ変換、となりそうです。

2020-10-08 10:07 UTC, suconbu commented
最新で動作確認し問題なしでしたので WIP 解除します。

2020-10-09 13:06 UTC, berryzplus commented on sakura_core/util/window.cpp
> +	NONCLIENTMETRICS metrics = { CCSIZEOF_STRUCT( NONCLIENTMETRICS, lfMessageFont ) };
> 既存コードに気になるコメントを見つけたため念のため合わせました。
> https://github.com/sakura-editor/sakura/search?q=NONCLIENTMETRICS

もしかしてこのコメントですかね？

> 以前のプラットフォームに WINVER >= 0x0600 で定義される構造体のフルサイズを渡すと失敗する

0x0600 は Windows Vista という `超古い windows OS` のことなので、対応は必須でないです。
https://docs.microsoft.com/ja-jp/cpp/porting/modifying-winver-and-win32-winnt

というかこの書き方だと「書きっぷりが古いのを訂正する」というPRで修正されると思います。
それで構わなければこのままでも構わんです。
位置づけ的に「間違ってるけど実害はないのでOK」です。

ちなみに `CCSIZEOF_STRUCT` というマクロは、「構造体」と「利用したいバージョンの構造体で定義されている最後のメンバー」を指定して使うものです。`CCSIZEOF_STRUCT( NONCLIENTMETRICS, lfMessageFont )` は 正しい ですが、他の利用箇所の利用方法は間違っているようです。

2020-10-09 13:21 UTC, berryzplus commented on sakura_core/util/window.cpp
> +	key << lfFont.lfHeight << " "
さすがにちょっと多くないですか？ｗ

これだけたくさん文字列化すると、キャッシュさせずに毎回CreateFontしたほうが早いかも？と無駄な最適化に走りたくなる人が現れても責められない気がします。

ただ、必要なら別によいです。

2020-10-09 14:56 UTC, suconbu commented on sakura_core/util/window.cpp
> +	key << lfFont.lfHeight << " "
QueryPerformanceCounter を使い計測 (CPU: i5-8250U) したところ、

* キー文字列生成に約 50us
* CreateFontIndirect に約 5us

と、フォントハンドル作成の方が圧倒的に短時間でした。(ハンドル作成速いですね)

キー化する要素はもう少し絞れる気もしますが、要素を「高さ」「フェイス名」の 2 つまで絞った場合でも約 40us と大して変化せずでしたので、今回はこのままとさせて下さい。

2020-10-09 16:24 UTC, berryzplus commented
右上の Reviewers のとこにある、

> Still in progress? Convert to draft.

をクリックすると Draft PR に変換できます。

どっちがいいとか別にありませんが、For Your Information ということで。

FYIコメントはなんかムカつくので嫌いなんですが、あえてFYIしてみました :smiley:

2020-10-11 00:50 UTC, beru requested changes
バージョン情報の画面で Compile Info の表示に問題が有ります。修正をお願いします。

## このPR
![image](https://user-images.githubusercontent.com/1131125/95667855-c99e3f00-0ba6-11eb-9162-a3f3f18dbec2.png)

## 2.4.2.3140

![image](https://user-images.githubusercontent.com/1131125/95667881-02d6af00-0ba7-11eb-8a9f-95402eaba6c0.png)

2020-10-11 03:11 UTC, suconbu commented
@beru さん

ありがとうございます。修正します。
確認された時のモニタの設定は 200% でしょうか？
(DPI 設定が 100%, 125% では発生しないようです)

2020-10-11 03:36 UTC, beru commented
@suconbu さん

> 確認された時のモニタの設定は 200% でしょうか？
> ~(DPI 設定が 100%, 125% では発生しないようです)~
> →100%, 125% の時、一行目の文字切れは発生しませんが二行目「Last Modified」以降が表示されない問題は発生していました。

はい、ディスプレイ設定の拡大縮小とレイアウトが 200% の環境で確認しました。

2020-10-11 08:13 UTC, suconbu commented
@beru さん

バージョン情報ダイアログボックスについて修正をし、拡大縮小とレイアウトの表示スケールが100%, 200% それぞれで問題ないことを確認しました。
* "Complile Info" の文字切れ (指摘事項)
* URL リンクの下線が表示されていない (自己発見問題)
* システムフォントに Meiryo UI を選択時、"(GitHash ...", "Copyright" が複数行になってしまう (自己発見問題)

※200% に設定すると私のディスプレイ環境では文字が大きくなりすぎて VisualStudio がポケコンのようになってしまいました。。

2020-10-11 08:21 UTC, suconbu commented
今になって気づいたのですが、表示スケールが 200% にもなると元の ＭＳ Ｐゴシック でも ClearType が適用されて綺麗に表示されるのですね。。

2020-10-11 08:38 UTC, suconbu commented
200% の状態で他に同じような問題出ていないか点検するため一旦 Draft にします。

2020-10-11 08:48 UTC, beru submitted a review, later dismissed
問題ないと思います。

03657f7d53c0fab722dfc0e4c5fda4cb365dd282 でバージョン情報の画面表示も修正された事を確認しました。

2020-10-11 09:08 UTC, beru commented
> 今になって気づいたのですが、表示スケールが 200% にもなると元の ＭＳ Ｐゴシック でも ClearType が適用されて綺麗に表示されるのですね。。

表示スケール 100% の場合にどうなるか確認してみました。

### 変更前
![image](https://user-images.githubusercontent.com/1131125/95674533-d1340700-0beb-11eb-99c2-dedca65d5770.png)

### 変更後
![image](https://user-images.githubusercontent.com/1131125/95674544-e7da5e00-0beb-11eb-83c0-d823d12b7734.png)

変更後は書体が変わってアンチエイリアシングが掛かってますね。変更後の方が行間が少し空いていて読みやすいですね。

アンチエイリアシングすると表示が必要以上にぼやけてしまって人によってはそれが気になりますが、高解像度のディスプレイで表示スケールを上げて利用する分にはあまり気にならないですね。

2020-10-11 11:27 UTC, berryzplus commented
https://github.com/sakura-editor/sakura/pull/1421#pullrequestreview-506135215 のコメントの問題って「文字切れ」なんだろうか？というのがちらっと気になりました。（解決済みなのでどうでもいい話 :smiley:

#1424 でリソーススクリプトを変更したのにマージ後にコンフリクトが発生しないのは、この変更が「ダイアログ」を対象にしているからなのかな？とか。（ #1424の対象は「プロパティーシート」なのでちょっと違う・・・）

2020-10-11 12:22 UTC, suconbu commented
> 200% の状態で他に同じような問題出ていないか点検するため一旦 Draft にします。

数か所見つかりましたので追加で修正をしました。
(指摘頂いたようながっつりと重なっているものはありませんでした)

2020-10-11 12:29 UTC, suconbu commented
@berryzplus さん

> #1421 (review) のコメントの問題って「文字切れ」なんだろうか？というのがちらっと気になりました。

問題の部分が下にある "原作者..." のテキスト (LTEXT) に上書きされて切れているように見えていたようで、実際は「重なり」でした。
この LTEXT にちょっと動いてもらうことでうまく収まりました。

> #1424 でリソーススクリプトを変更したのにマージ後にコンフリクトが発生しないのは、この変更が「ダイアログ」を対象にしているからなのかな？とか。（ #1424の対象は「プロパティーシート」なのでちょっと違う・・・）

私の変更でも同じプロパティシートを編集していますが、たまたま同じ行に変更が入らなったようです。

2020-10-11 13:47 UTC, beru requested changes
f4a552969c45dbaa6f1ff28fdb3d214f0d814010 を確認しました。

共通設定のファイルの `←注：ドロップファイルは1つのみ有効` というラベルの右端が欠けて表示されているのでお手数ですが修正をお願いします。

![image](https://user-images.githubusercontent.com/1131125/95680289-80380900-0c13-11eb-978b-624894687c2b.png)

2020-10-11 14:54 UTC, suconbu commented
> 共通設定のファイルの ←注：ドロップファイルは1つのみ有効 というラベルの右端が欠けて表示されている

修正しました。ここは「1つのみ有効」だったのですね笑
確認時、「1つのみ有(あり)」と読んでスルーしてしまっていました。
さらに PR 対応前は「1つのみ」となっていて、これまた違和感がなく全く気づきませんでした。

変遷：
v2.4.2.0 | https://github.com/sakura-editor/sakura/pull/1421/commits/f4a552969c45dbaa6f1ff28fdb3d214f0d814010 | https://github.com/sakura-editor/sakura/pull/1421/commits/04120b3d63600580a843b382ab557f465c456520
-|-|-
![image](https://user-images.githubusercontent.com/11252784/95681820-d5c4e380-0c1c-11eb-9664-73227524f4f1.png) | ![image](https://user-images.githubusercontent.com/11252784/95681799-c47bd700-0c1c-11eb-92ae-739fca7bcabe.png) | ![image](https://user-images.githubusercontent.com/11252784/95681810-ca71b800-0c1c-11eb-84bb-f1edf20b8a9b.png)

2020-10-11 15:17 UTC, beru approved these changes
問題ないと思います。

2020-10-11 15:18 UTC, beru commented
04120b3d63600580a843b382ab557f465c456520 の修正も確認して問題ないと思いますので Merge します。

2020-10-11 15:18 UTC, merged

2020-10-11 15:20 UTC, beru commented
f4a552969c45dbaa6f1ff28fdb3d214f0d814010 では色々な箇所の調整がされていますね。
コミットメッセージに説明がしっかり書かれているのが良いですね。

2020-10-11 15:47 UTC, suconbu commented
レビュー、マージありがとうございました。

> 英語はタブだけがなぜかギザギザなので、

こちらは引き続き調べてみます。

2020-10-11 15:49 UTC, berryzplus commented
> > #1421 (review) のコメントの問題って「文字切れ」なんだろうか？というのがちらっと気になりました。
> 
> 問題の部分が下にある "原作者..." のテキスト (LTEXT) に上書きされて切れているように見えていたようで、実際は「重なり」でした。

「文字切れ」とは、文字の一部分が欠けて表示される不具合だと思います。
まったく表示されていないように見えるのを「文字切れ」と言ってよいのか？という禅問答っす（キレテナーイ

> > #1424 でリソーススクリプトを変更したのにマージ後にコンフリクトが発生しないのは、この変更が「ダイアログ」を対象にしているからなのかな？とか。（ #1424の対象は「プロパティーシート」なのでちょっと違う・・・）
> 
> 私の変更でも同じプロパティシートを編集していますが、たまたま同じ行に変更が入らなったようです。

システムフォントでなくシステムフォント風を使っている（≒高さは変わらない）のが理由で、高さの変更は影響しなかったかもです。

2020-10-11 16:39 UTC, beru commented
> > > #1424 でリソーススクリプトを変更したのにマージ後にコンフリクトが発生しないのは、この変更が「ダイアログ」を対象にしているからなのかな？とか。（ #1424の対象は「プロパティーシート」なのでちょっと違う・・・）
> > 
> > 
> > 私の変更でも同じプロパティシートを編集していますが、たまたま同じ行に変更が入らなったようです。
> 
> システムフォントでなくシステムフォント風を使っている（≒高さは変わらない）のが理由で、高さの変更は影響しなかったかもです。

下記の変更で高さを変えた事との関連を話しているっぽいですね。

https://github.com/sakura-editor/sakura/pull/1424/files#diff-67955f03bb0bbb169f93ff6fa4998095L1190

いやーしかしこのPRでリソーススクリプトの調整が数多く行われましたね。リソースエディタでの編集ではなくてテキストエディタで編集してビルドして動作確認しての繰り返し作業だと思うのでかなり大変だったんじゃないですか？