プロパティシートのコントロール表示のちらつき防止
sakura-editor/sakura pull request #1424
Opened 2020-10-04 23:51 UTC by beru

#  PR の目的

共通設定の画面において、主にリスト系のコントロールの内容を切り替える際にちらついて表示されるので、それがなるべく起きないようにするのが目的です。

##  カテゴリ

- その他の問題

##  PR の背景

画面を操作していてコントロールの表示のちらつきが気になったので下記の対策を入れました。

- リスト系のコントロールの表示内容を差し替える前後で `WM_SETREDRAW` メッセージを送る事で表示更新のタイミングを制御
  - コントロールに対して行ってもちらつきが減らなかった場合は親ウィンドウのダイアログ（プロパティシート）に対してメッセージを送るようにしましたが、その場合後で `InvalidateRect` を実行する必要がありました。
- リソースファイルのプロパティシートの拡張ウィンドウスタイルに `WS_EX_COMPOSITED` を付けてダブルバッファリングされるようにしました。これをやらないでもちらつきが特に気にならないレベルまで解消される場合もありますが、そうでない場合もあります。メカニズムがいまいち不明なのと、動作環境によって挙動が変わるかもしれません。

##  PR のメリット

表示のちらつきが減ります。

##  PR のデメリット (トレードオフとかあれば)

`WS_EX_COMPOSITED` スタイルを付けてダブルバッファリングしているのでメモリ使用量が増えます。ただし最近のPCであれば問題になるような増加量では無い筈です。

##  仕様・動作説明

##  テスト内容

画面表示を目視で確認しました。

リスト表示のちらつきが減ったかどうかの確認は、ドロップダウンリストの選択を切り替えるとリストの表示内容が切り替わるので、その際のちらつきが減ったかどうかを確認しました。

##  PR の影響範囲

下記の画面に手を入れました。

- 共通設定
  - メインメニュー
  - ツールバー
  - タブバー
  - キー割り当て
  - カスタムメニュー
  - 強調キーワード

##  関連 issue, PR

##  参考資料

https://docs.microsoft.com/en-us/windows/win32/gdi/wm-setredraw
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-invalidaterect
https://devblogs.microsoft.com/oldnewthing/20171018-00/?p=97245

2020-10-05 01:14 UTC, berryzplus requested changes
> ほぼいちゃもんですが `::SendMessageAny` は使わないほうがよいと思います。

request changes な指摘はこれだけです。

PRの目的である「ちらつきを抑えたい」は、動かしてみてもちらつきが減ったかぼくには判断できないので、他の方にお任せします。

2020-10-05 01:14 UTC, berryzplus commented on sakura_core/prop/CPropComCustmenu.cpp
> +	::InvalidateRect( hwndDlg, NULL, FALSE );
ん？これは必要ですか・・・？
（たぶん、必要だから入れてると思いますが念のための確認です。）

window描画の仕組み
1. 外部から WM_UPDATE を送る。
1. WM_UPDATE を受け取ったウインドウは、クライアント領域に更新領域があれば自身に WM_PAINT を送る。
1. WM_PAINT を受け取ったウインドウは、クライアント領域を描画する。

`InvalidateRect(hwnd, NULL, FALSE)` は、クライアント領域の全域更新を指示する命令です。WM_SETREDRAW で再描画フラグを戻しただけだけだと更新されない仕様だと思うんですが、ここに要るなら他にもいるような気がして、何故ここだけ？と思いました。

2020-10-05 01:14 UTC, berryzplus commented on sakura_core/prop/CPropComKeyword.cpp
> +	InvalidateRect(hwndDlg, NULL, FALSE);
ここにはありますね・・・

2020-10-05 01:14 UTC, berryzplus commented on sakura_core/sakura_rc.rc
> +    RTEXT           "Font", IDC_STATIC_TABFONT, 102, 127, 180, 12, SS_RIGHT
これは必要です？ or NOT？

必要なら入れたらよいと思います。
右寄せラベルの高さが大きくなってるのを文字に合わせる変更に見えていて、ちらつき防止と関係あるようには思えないのですが・・・。

2020-10-05 01:58 UTC, beru commented on sakura_core/prop/CPropComCustmenu.cpp
> +	::SendMessageAny( hwndDlg, WM_SETREDRAW, FALSE, 0 );
使わないつもりが使ってしまいました。直しときます。

2020-10-05 02:01 UTC, beru commented on sakura_core/prop/CPropComCustmenu.cpp
> +	::InvalidateRect( hwndDlg, NULL, FALSE );
コントロールのウィンドウの変更に対して WM_SETREDRAW する場合は後で InvalidateRect を呼ばないでも表示が更新されてたんですが、親のダイアログの場合は呼ばないと表示が更新されませんでした。理屈は分かっていません。

2020-10-05 02:03 UTC, beru commented on sakura_core/sakura_rc.rc
> +    RTEXT           "Font", IDC_STATIC_TABFONT, 102, 127, 180, 12, SS_RIGHT
WS_EX_COMPOSITED を付けるとこの変更入れないと表示に問題がありました。

2020-10-05 02:03 UTC, beru commented on sakura_core/prop/CPropComKeyword.cpp
> +	InvalidateRect(hwndDlg, NULL, FALSE);
ここも親ダイアログに対しての場合ですね。

2020-10-05 02:32 UTC, beru commented
> PRの目的である「ちらつきを抑えたい」は、動かしてみてもちらつきが減ったかぼくには判断できないので、他の方にお任せします。

これについてですが変更前と変更後でアプリを両方起動して見比べないとなかなか判断出来ないと思います。

2020-10-05 05:12 UTC, beru commented on sakura_core/sakura_rc.rc
> +    RTEXT           "Font", IDC_STATIC_TABFONT, 102, 127, 180, 12, SS_RIGHT
![image](https://user-images.githubusercontent.com/1131125/95042411-c02f5580-0714-11eb-81b2-1d3bfbe0e9d3.png)

高さを調整しないとこのように表示されてしまいます。

2020-10-05 05:15 UTC, beru commented on sakura_core/sakura_rc.rc
> +    RTEXT           "Font", IDC_STATIC_TABFONT, 102, 127, 180, 12, SS_RIGHT
https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

の `WS_EX_COMPOSITED` の解説ですが

> Paints all descendants of a window in **bottom-to-top painting order** using double-buffering. Bottom-to-top painting order allows a descendent window to have translucency (alpha) and transparency (color-key) effects, but only if the descendent window also has the WS_EX_TRANSPARENT bit set. Double-buffering allows the window and its descendents to be painted without flicker. This cannot be used if the window has a class style of either CS_OWNDC or CS_CLASSDC.
Windows 2000: This style is not supported.

と書かれています。`bottom-to-top painting order` というのが画面のXYのYの上下の事なのかZ-orderの上下の事なのかわかっていませんが、この事が関わっていそうです。

2020-10-07 14:21 UTC, berryzplus commented on sakura_core/sakura_rc.rc
> +    RTEXT           "Font", IDC_STATIC_TABFONT, 102, 127, 180, 12, SS_RIGHT
> `bottom-to-top painting order` というのが画面のXYのYの上下の事なのかZ-orderの上下の事なのかわかっていませんが（多分後者）この事が関わっていそうです。

画面の下から上の順番でコントロールを描画していくってことでしょうね。
通常は上から下の順番で描画されていると考えると、下方向にはみ出したコントロールがこれまで問題にならず、拡張スタイルの追加でおかしくなった理由を説明できると思います。従来ははみ出した部分を下側にあるコントロールで上書きしていたから問題にならず、変更により描画済みのコントロールの上にはみ出して描画するようになったっちゅうことです。

2020-10-07 15:04 UTC, berryzplus reviewed
コードで気になる点は解消したと思います。
変更したプロパティーシートでドロップダウンリストが表示できることも確認しました。

変更前の「ちらつく」について定量的な表現で事象を解説してもらえれば、改修確認のデータ取ってもよいです。目視チェックする能力はないので、目視がいい場合は他の人に頼んでください。

2020-10-07 15:41 UTC, beru commented
> 変更前の「ちらつく」について定量的な表現で事象を解説してもらえれば、改修確認のデータ取ってもよいです。目視チェックする能力はないので、目視がいい場合は他の人に頼んでください。

いつかHFR(ハイフレームレート) 撮影が出来るカメラを購入して撮影した動画を YouTube において確認出来るようにしようかと思います。

2020-10-07 16:26 UTC, berryzplus commented
> > 変更前の「ちらつく」について定量的な表現で事象を解説してもらえれば、改修確認のデータ取ってもよいです。目視チェックする能力はないので、目視がいい場合は他の人に頼んでください。
> 
> いつかHFR(ハイフレームレート) 撮影が出来るカメラを購入して撮影した動画を YouTube において確認出来るようにしようかと思います。

超スロー再生にしたときに問題のある瞬間のコマがどう見えるか、
つまり、「ちらつく」がどういう不具合なのかを説明してもらえればいいっす。

2020-10-10 10:45 UTC, berryzplus commented
> > 超スロー再生にしたときに問題のある瞬間のコマがどう見えるか、
> > つまり、「ちらつく」がどういう不具合なのかを説明してもらえればいいっす。
> 
> 百聞は一見にしかず、ということわざがあるぐらいなので言葉で説明してもきちんと伝わるか自信が無いですが書いてみます。

なんどやっても変更前 455a7fff55759ba3058a210fa9ca62d1f8eb8baa の挙動を「ちらつく」と感じませんでした。

共通設定 ダイアログ
　メインメニュー タブ
　　「種別」を「ファイル操作系」から「編集系」に変える

目視の範疇では `不具合が再現しない` です。
`百聞は一見に如かず` に従うと、`何言ってるんだこいつは？` になるです。
（別な理由で、正しい対策なんだろうな、と思っていますが。）

本当に目視で「ちらつき」を感じていますか？
発端となった「問題のある操作」を明示してもらえたら、こちらでも再現できるのかもです。

2020-10-10 11:01 UTC, berryzplus commented
> 本来は表示する必要のない途中の絵が見えてしまうのがちらつきの原因です。

と書かれているので `「ちらつく」がどんな現象であるか？` に齟齬はないように思いました。

「ちらつく」は科学的に説明できる現象で、C/C++特有の `よくある不具合` です。

* 超スロー再生にしたときに問題のある瞬間のコマがどう見えるか  
消えて見えるか、不完全な描画状態に見えます。
* 「ちらつく」がどういう不具合なのか  
再描画の途中過程が（意図せず）見えてしまう不具合です。

よくある不具合なので対策手法の定石があります。

描画途中が見えてしまうことが問題ならば、見せなきゃよいのです。

修正内容は一定区間で発生する描画命令を抑制させるので、定石に照らして適切である、と予想できます。

問題は、実際の不具合事象を確認できていないのに理屈のみを以て approve してよいか？ ということで、
ダメなんじゃないかと思ったので「ちらつき」を感知する能力のある人による表示確認を提案した次第です。

2020-10-10 12:32 UTC, beru commented
## 変更前

![455a7fff55759ba3058a210fa9ca62d1f8eb8baa_IDD_PROP_KEYWORD](https://user-images.githubusercontent.com/1131125/95655099-f0755a80-0b3f-11eb-84ec-f363f26ac05c.gif)

## 変更後

![079929f9b9ad367e29b69b029d70b82561c3c9fb_IDD_PROP_KEYWORD](https://user-images.githubusercontent.com/1131125/95655107-06831b00-0b40-11eb-8602-547ba42d7ab4.gif)

2020-10-10 13:10 UTC, beru commented
上記のコメントに ScreenToGif でキャプチャして保存したアニメーションGIFファイルを貼り付けました。
等速再生なので違いがわかりにくいかもしれません。

下記のページでは同じ動画を 1/4 の速度で再生しています。
https://beru.github.io/flickering/test.html

2020-10-10 13:11 UTC, berryzplus commented
https://github.com/sakura-editor/sakura/pull/1424#issuecomment-706542216
これは確かにちらついてますね。
（ここまでハッキリちらついてたらさすがに見えるっす。）

よく考えてみたらPRの事象確認には結構な描画性能を持つマシンを使っていて、他の端末での確認は行っていませんでした。
（GeForce GTX 1070 Ti 相当を積んだノートで、実際 https://github.com/sakura-editor/sakura/pull/1424#issuecomment-706542216 の操作を試しても再現しませんでした。）

発生メカニズムからして「人の能力」ではなくて「マシンの能力」が影響する可能性に気付きました。

無駄な再描画（＝クリアして描画し直し）を繰り返し行なう「不適切なコード」があったとして、
「マシンの能力」が十分であれば即時に再描画が完了するため途中が見えてしまう事態が発生しません。

これをもって改善効果を確認できたとしてよいような気がしますがどうでしょう？

2020-10-10 14:03 UTC, beru commented
マシンの能力も関係すると思います。ところで一般的にモニタのリフレッシュレートは 60Hzですが、240Hzのゲーミングモニターを使えば（マシンパワーが十分にあれば）中間のコマが更に表示される可能性は増えますね。無駄な中間のコマを表示すると計算量も増えてしまうので、リスト系のコントロールに大量にアイテムを登録する場合には WM_SETREDRAW を使って再描画を抑える事が推奨されています。

2020-10-11 10:32 UTC, berryzplus approved these changes
問題ないと思います。

2020-10-11 11:02 UTC, beru commented
レビューありがとうございます。Mergeします。
もし問題が見つかったらあとで修正します。

2020-10-11 11:02 UTC, merged