利用できないコマンドラインオプション「-WQ(INIファイルを出力して即終了)」を削除したことにより可能となったコード整理を実施する
sakura-editor/sakura pull request #1435
Opened 2020-10-19 06:43 UTC by berryzplus

#  PR の目的

利用できないコマンドラインオプション「-WQ(INIファイルを出力して即終了)」を削除したことにより可能となったコード整理を実施します。

##  カテゴリ

- リファクタリング

##  PR の背景

#1432 で一度出した https://github.com/sakura-editor/sakura/commit/14c8faf8ebf196c745894d132767873c6813795e の出し直しです。

修正内容が挙動を変えないことを目視確認できるようにコミットを分けただけの代物です。
（といいつつ、内容は少し変えていますが:smiley:）

変更は個々のコミットを見たら自明となるように作ってあります。

緒tt迷った感じのコミットもいくつかあります。
* https://github.com/sakura-editor/sakura/commit/3a7aa9ffcf74d2e76418ddaaaa454cdacd085f30 本質的には CProfile::WriteProfile でやるべきことなので、移動するならそっちじゃね？とか。それやるとリファクタリングじゃなくなるので、とりあえずメソッドの外に移動しています。
* https://github.com/sakura-editor/sakura/commit/673818249f5b77eec2febf517a4eb7c92d2b02a5 この変更いらなくね？というのがあるかも知れません。もう一歩進めて IsPrivateSettings() というグローバル関数を作っても良いかも知れません。

##  PR のメリット

コードが多少分かりやすくなります。

##  PR のデメリット (トレードオフとかあれば)

とくにないと思います。

##  仕様・動作説明

仕様・動作に変更はありません。

このPRは不要となった共有メモリの構造体メンバーを削除するため、共有メモリバージョンを変更します。

|--|共有メモリバージョン|
|--|--|
|変更前|176|
|変更後|177|

##  テスト内容
このPRは外部仕様を一切変更しないため、エディタの起動を確認できれば十分です。

##  PR の影響範囲

コントロールプロセスの初期化に影響する変更です。
sakura.exe.ini を使ってマルチユーザー設定にした場合の動作に影響します。

##  関連 issue, PR

#1432

##  参考資料

2020-10-22 14:44 UTC, sanomari requested changes
あえて不完全な変更で止めてあるように見えました。

修正量や影響範囲が多くなってしまうとしても、修正をやり切ってしまったほうが良さそうに思います。

2020-10-22 14:44 UTC, sanomari commented on sakura_core/env/CShareData_IO.cpp
>  			cProfile.WriteProfile( szIniFileName, LTEXT(" sakura.ini テキストエディタ設定ファイル") );
WriteProfileの不具合と分かっているならそのように対応するのが筋なのではないですか？

2020-10-22 14:44 UTC, sanomari commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
この構造体を削ってしまってはいかかがでしょう。

### この構造体を残しておくことのメリデメ

| | 説明 |
| -- | -- |
| メリット | INIフォルダ判定結果をキャッシュできる。 |
| デメリット | 共有メモリに依存するので単体テストが書けない。 |

判定のオーバーヘッドも変数サイズもたいしたことないので、廃止して単体テストを書けるコードを増やしたほうがよさそうに思います。

2020-10-24 05:53 UTC, berryzplus commented on sakura_core/env/CShareData_IO.cpp
>  			cProfile.WriteProfile( szIniFileName, LTEXT(" sakura.ini テキストエディタ設定ファイル") );
#1438で対応してみました。

2020-10-24 06:03 UTC, berryzplus commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
PRの一部を分割したので一旦閉じて出し直します。

2020-10-30 16:58 UTC, berryzplus commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
う～ん、無理かも。

2020-11-01 11:19 UTC, sanomari commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
なんでですか？
具体的な理由を説明できますか？

2020-11-03 08:06 UTC, berryzplus commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
> なんでですか？
> 具体的な理由を説明できますか？

PRを出してもレビュアーが理解できないだろう、という意味で「無理かも」と書きました。

現在の単体テスト `tests1.exe` には4種類のテストが含まれています。

1. 本物の単体テスト  （コード＋スタブ等でコードそのものの良し悪しを判断するテスト）
1. 単体といいつつ、モジュールレベルの結合動作を確認するテスト （[test-loadstring.cpp](https://github.com/sakura-editor/sakura/blob/master/tests/unittests/test-loadstring.cpp)など）
1. 単体といいつつ、システムレベルの結合動作を確認するテスト （[test-winmain.cpp](https://github.com/sakura-editor/sakura/blob/master/tests/unittests/test-winmain.cpp)）
1. gtest の使用例サンプル 

・・・。この情報だけでもお腹一杯になれると思います。

普通に考えて、目的の異なる複数の種類のテストが1モジュールに詰まっていることは問題だと思います。
たぶん先に、テストモジュールを分割する対応が要って、そこだけで20手（≒20PR）くらい要りそうです。

事前の変更を行っている間に、ここの変更のことを覚えている自信がないので閉じずに放置してある次第です。

2020-11-09 00:35 UTC, sanomari commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
> > なんでですか？
> > 具体的な理由を説明できますか？
> 
> PRを出してもレビュアーが理解できないだろう、という意味で「無理かも」と書きました。

誰でも理解できるようには説明できない、と解釈しました。

それは当然だと思います。

ここの実装をテスト可能にする話と単体テストの種類が混在している話は別じゃないかと思いました、テストを混在させたままでもテスト可能にする変更はできると思います。

もちろん、gmockを使うテストは不可能でしょうけど、必要なんですか？

2021-01-20 03:26 UTC, sanomari commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
これ、やりましょうか？

2021-01-20 10:50 UTC, berryzplus commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
どうぞ。

どの範囲を？って疑問はありますが、自分がレビュー側にまわったほうがマージが早い傾向にあると思います。
（まー、レビューが適当だからなんですけども :smile: ）

2021-01-21 03:26 UTC, sanomari commented on sakura_core/env/CFileNameManager.h
>  };	/* iniフォルダ設定 */
> どうぞ。
> 
> どの範囲を？って疑問はありますが、自分がレビュー側にまわったほうがマージが早い傾向にあると思います。
> （まー、レビューが適当だからなんですけども 😄 ）

GetInidirをプロセスがない状態でも呼び出せるように変更する修正です。
このPRよりも一回り広い範囲の修正になると思います。

2021-01-23 05:16 UTC, berryzplus commented
#1512 に完全に取り込まれるようなのでこちらは閉じてしまいます。

2021-01-23 05:16 UTC, closed without merging