ビルド要件のドキュメントが古くなっているので更新する
sakura-editor/sakura pull request #1437
Opened 2020-10-21 12:45 UTC by berryzplus

#  PR の目的

ドキュメントが古いので更新します。

##  カテゴリ

- ドキュメント修正

##  PR の背景

#1357 ビルド要件のドキュメントが古くなっている、の対処をします。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

##  テスト内容

### テスト1

手順

##  PR の影響範囲

##  関連 issue, PR

close #1357

##  参考資料

2020-10-21 14:38 UTC, sanomari requested changes
いまよりはマシになってると思います。

2020-10-21 14:38 UTC, sanomari commented on README.md
> +  - [Hot topic](#hot-topic)
編集にvscode使ってますか？
目次のレベルが正規化されていて変更が見辛くなっています。
変更前がおかしいんだと思いますがコミットを分けたほうがよいと思います。

2020-10-21 17:10 UTC, kazasaku requested changes
[build.md](https://github.com/sakura-editor/sakura/blob/master/build.md) も更新したほうが良いと思います。

2020-10-22 14:49 UTC, berryzplus commented
しっくり来ねぇ...orz

2020-10-22 17:43 UTC, kazasaku commented on README.md
> +- [7Zip](https://sevenzip.osdn.jp/)
build.mdではオプションと前置きが記述されています。
表現をどちらかに合わせたほうが良いかもしれません。

2020-10-23 07:50 UTC, berryzplus commented
やめ。

記述が古いことよりも、記述位置が不適切なことのほうが気になってそちらを直したくなってしまうので、仕切り直したほうが良さそうに思いました。

2020-10-23 07:50 UTC, closed without merging

2020-10-25 08:00 UTC, sanomari commented
> 記述が古いことよりも、記述位置が不適切なことのほうが気になってそちらを直したくなってしまうので、仕切り直したほうが良さそうに思いました。

発覚した問題点は、具体的に報告しましょ。

2020-10-25 08:48 UTC, berryzplus commented on README.md
> +- [7Zip](https://sevenzip.osdn.jp/)
2つあるからズレるんですよね。
記述自体、`build.md` のほうだけで良い気がします。

2020-10-25 09:21 UTC, berryzplus commented
> > 記述が古いことよりも、記述位置が不適切なことのほうが気になってそちらを直したくなってしまうので、仕切り直したほうが良さそうに思いました。
> 
> 発覚した問題点は、具体的に報告しましょ。

発覚した問題点

* README.md の記述内容が、ぶっちゃけおかしい。
  * TOC（＝Table Of Contents ≒ 目次）の位置がおかしい。
  * Hot Topic が 事実上 stale。 
  * Web Site の heading がたぶん無駄。
  * 開発参加ポリシー の 記載がたぶん無駄。
  * 「サクラエディタ？何それ、おいしいの？」に関する説明がない。
  * サクラエディタ「そのもの」の使い方に関して一切説明がない。
  * Build Requirements がここにある理由が謎。
  * How to build がここに必要な理由が謎。
  * How to install がここになくて良い理由が謎。buildがあるなら用意するのが普通。
  * How to use がここになくて良い理由が謎。buildがなくても用意するのが普通。
  * how to build より下に書いてある項目が、全項目意味不明。　👈思考停止。


既知の問題として以下のものがあります。

* #740 トップディレクトリのファイルを整理する