SonarQubeの静的解析で検出されたバグを修正する
sakura-editor/sakura pull request #1439
Opened 2020-10-25 15:54 UTC by sanomari

#  PR の目的

SonarQubeの静的解析で検出されたバグを修正します。

##  カテゴリ

- リファクタリング

##  PR の背景

https://github.com/sakura-editor/sakura の README.md に貼ってある Sonar Qube の静的解析で、致命的なエラーが出ているのが気になっています。

[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=sakura-editor_sakura&metric=alert_status)](https://sonarcloud.io/dashboard?id=sakura-editor_sakura)
　👆2020/10/26現在、failed って出てます。

現在検出されているNG箇所は 330個 あります。

今回は、ランク分けされたNG箇所のうち、最もダメな警告に対処してみたいと思います。

### 対処するNG指摘
> Potential leak of memory pointed to by field '_Myval2'

### 対処方法
std::wstring を使ってメモリ確保失敗時に例外が発生するように修正します。

##  PR の影響範囲

ウインドウテキストの取得に生配列のスマートポインタを利用していた箇所をstd::wstringで置換します。

##  PR のメリット

静的解析で検出される警告が減ります。

##  PR のデメリット (トレードオフとかあれば)

何か動作かえてしまっていたらごめんなさい。

##  仕様・動作説明

設計時にバッファサイズを確定できない wchar_t 配列を動的に確保するコードをリファクタリングします。

##  PR の影響範囲

##  テスト内容

動作を変えていないので軽く動かしてみただけです。

##  関連 issue, PR

##  参考資料

https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqv&open=AXHBcsLrUe04Z9I8ZMqv
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqw&open=AXHBcsLrUe04Z9I8ZMqw
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqx&open=AXHBcsLrUe04Z9I8ZMqx
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsJ7Ue04Z9I8ZMqt&open=AXHBcsJ7Ue04Z9I8ZMqt
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsJ7Ue04Z9I8ZMqu&open=AXHBcsJ7Ue04Z9I8ZMqu
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqAzUe04Z9I8ZMqP&open=AXHBcqAzUe04Z9I8ZMqP
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp85Ue04Z9I8ZMqN&open=AXHBcp85Ue04Z9I8ZMqN
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp85Ue04Z9I8ZMqO&open=AXHBcp85Ue04Z9I8ZMqO
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqv&open=AXHBcsLrUe04Z9I8ZMqv
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqw&open=AXHBcsLrUe04Z9I8ZMqw
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsLrUe04Z9I8ZMqx&open=AXHBcsLrUe04Z9I8ZMqx
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsJ7Ue04Z9I8ZMqt&open=AXHBcsJ7Ue04Z9I8ZMqt
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcsJ7Ue04Z9I8ZMqu&open=AXHBcsJ7Ue04Z9I8ZMqu
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqAzUe04Z9I8ZMqP&open=AXHBcqAzUe04Z9I8ZMqP
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp85Ue04Z9I8ZMqN&open=AXHBcp85Ue04Z9I8ZMqN
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp85Ue04Z9I8ZMqO&open=AXHBcp85Ue04Z9I8ZMqO
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp2SUe04Z9I8ZMqL&open=AXHBcp2SUe04Z9I8ZMqL
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcp5XUe04Z9I8ZMqM&open=AXHBcp5XUe04Z9I8ZMqM
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqEqUe04Z9I8ZMqQ&open=AXHBcqEqUe04Z9I8ZMqQ
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqEqUe04Z9I8ZMqR&open=AXHBcqEqUe04Z9I8ZMqR
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBco-yUe04Z9I8ZMqF&open=AXHBco-yUe04Z9I8ZMqF
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqo5Ue04Z9I8ZMqS&open=AXHBcqo5Ue04Z9I8ZMqS
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqo5Ue04Z9I8ZMqT&open=AXHBcqo5Ue04Z9I8ZMqT
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqo5Ue04Z9I8ZMqU&open=AXHBcqo5Ue04Z9I8ZMqU
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqW&open=AXHBcqvOUe04Z9I8ZMqW
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqX&open=AXHBcqvOUe04Z9I8ZMqX
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqY&open=AXHBcqvOUe04Z9I8ZMqY
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqZ&open=AXHBcqvOUe04Z9I8ZMqZ
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqa&open=AXHBcqvOUe04Z9I8ZMqa
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqb&open=AXHBcqvOUe04Z9I8ZMqb
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqc&open=AXHBcqvOUe04Z9I8ZMqc
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqd&open=AXHBcqvOUe04Z9I8ZMqd
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqe&open=AXHBcqvOUe04Z9I8ZMqe
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcqvOUe04Z9I8ZMqf&open=AXHBcqvOUe04Z9I8ZMqf
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXHBcr28Ue04Z9I8ZMqs&open=AXHBcr28Ue04Z9I8ZMqs

2020-10-26 02:02 UTC, berryzplus approved these changes
ざっと見た感じ問題なさそうです。

2020-10-26 02:28 UTC, oooonduke commented
サクラエディタ   v2.4.2.3187 64bit dev Alpha Version
(GitHash cae422f7b5e387585aea9e04e1efd79224d8af29)
(GitURL https://github.com/sakura-editor/sakura.git)
バージョン情報のSourceURLが…giとなっているのが気になります。

2020-10-26 03:15 UTC, berryzplus commented
> バージョン情報のSourceURLが…giとなっているのが気になります。

ほんとですね。
![image](https://user-images.githubusercontent.com/3253151/97130468-e5980800-1784-11eb-832e-70b4e5c38594.png)

2020-10-26 03:49 UTC, sanomari commented
すみません、やらかしていました。

2020-10-26 06:00 UTC, usagisita reviewed
エラーメッセージでぐぐると以下のものがヒットします。
https://bugs.llvm.org/show_bug.cgi?id=38176
これって誤検出なのではないか、と思うのですが、実際にバグで、メモリーリークするケースがあるのでしょうか？
どういう状況で問題があるのか分かっているなら、教えてほしいなと思います。
もっとも、誤検出かどうかにかかわらず、これらのべた書きの処理をまとめるという部分に関しては、大賛成です。

2020-10-26 10:22 UTC, berryzplus commented
> これって誤検出なのではないか、と思うのですが、実際にバグで、メモリーリークするケースがあるのでしょうか？

std::make_uniqueの仕様とMSVCのnew()の仕様を見た感じでは誤検出っぽいです。
https://cpprefjp.github.io/reference/memory/make_unique.html

1. std::make_uniqueは仕様的に operator new() を呼ぶ。
1. MSVC の operator new() は失敗時に std::bad_alloc を投げる。  
ここだけ見ると誤検知に見えます。
1. operator new() は独自にオーバーロードできる。  
いいか悪いかは別にして、例外を投げないオーバーロードも可能。  
これを考慮すると、一概に誤検出だとは言えない気もします。

個人的には「failedなのはマズいっしょ！」という趣旨と理解してて、
バッチが真っ赤なのに気付いてなかったんで「やっべ！」と思っています。

2020-10-26 10:29 UTC, berryzplus commented on sakura_core/util/string_ex.h
> +inline int vstrprintf<WCHAR>( std::wstring& strOut, const WCHAR* pszFormat, va_list& argList )
ほぼ、いちゃもんですが。

テンプレートにしないで普通の関数としたほうがよいような気がします。
テンプレートをやめたら関数本体をcppに移動できてコメントも書けます :smiley:

2020-10-26 10:44 UTC, sanomari commented on sakura_core/apiwrap/StdControl.h
> +	*/
これは隣のメソッドに合わせました！

2020-10-26 10:46 UTC, sanomari commented on sakura_core/CGrepAgent.cpp
> +			strTemp = strTemp.substr( 1, strTemp.length() - 2 );
レビューありがとうございます。
パスに含まれる `"` を削除する処理に直したいと思います。

2020-10-26 11:15 UTC, sanomari commented on sakura_core/apiwrap/StdControl.cpp
> +		strText.reserve( cchRequired );
resize()に直しておきます。

2020-10-26 11:33 UTC, sanomari commented on sakura_core/apiwrap/StdControl.cpp
> +		strText.assign( strText.data(), actualCopied );
ここは実際にはコピーは行われずlength)だけが更新されます。

ポインタからポインタに値をコピーする処理で、ポインタが同じかどうかをチェックしないでコピーするコードを書いて静的解析ツールに怒られたことがあります。絶対に大丈夫？って聞かれるとゴニョニョですが、大丈夫なんじゃないかと思います。（VC++の実装は大丈夫でした。

2020-10-26 22:57 UTC, beru requested changes
883eee4ca80f1bf791cd8451bd4af89dd072e675 で確認しましたがビルドに失敗します。

```
1>CMainToolBar.cpp
1>C:\projects\sakura\sakura_core\window\CMainToolBar.cpp(189,2): error C3861: 'CreateToolBarButtons': identifier not found
```

最初のエラーメッセージが上記のものですが、`CMainToolBar.h` ファイルに `CreateToolBarButtons` メソッドのプロトタイプが存在しないので git のステージングし忘れのような気がします。

手間ですがローカル側でいったん別の場所で pull してビルド出来るかの確認はした方が良いです。

あとこれは強制的ではないですが開発ブランチの名前は `master` ではない方が良いと思います。

2020-10-26 23:08 UTC, beru commented
あくまで個人の意見に過ぎないですが、１つのPRで観点が色々な変更を一挙にやろうとしない方が良いと思います。変更のボリュームが大きい場合はなおさらです。レビューするのが大変というレビューアー側の能力の問題もありますが…。

`SonarQubeの静的解析で検出されたバグ` が多数ある場合はそれをまず新規に Issue を作成してでも良いので列挙して、複数のPRに分けた方がシンプルに片づけられそうならそうした方が良いかなと思います。

ただまぁ考え方は人によって違うので正解は無い事だと思います。急がば回れにするか、回りくどいやり方はかったるくてやってられるかで一気に済ませるか、人それぞれですね。

2020-10-27 02:09 UTC, berryzplus commented
CodeFactorの警告対応は修正と関係ない箇所で、
かつ、対応入れても警告が消えなかったようなので、
今回は外したほうがいいように思います。

2020-10-27 03:41 UTC, sanomari commented
> 最初のエラーメッセージが上記のものですが、`CMainToolBar.h` ファイルに `CreateToolBarButtons` メソッドのプロトタイプが存在しないので git のステージングし忘れのような気がします。

レビューありがとうございます。
原因はステージング漏れでした。

2020-10-27 03:41 UTC, sanomari commented
> CodeFactorの警告対応は修正と関係ない箇所で、
> かつ、対応入れても警告が消えなかったようなので、
> 今回は外したほうがいいように思います。

今回は外してしまうことにしました。

2020-10-27 09:27 UTC, berryzplus approved these changes

2020-10-28 11:51 UTC, berryzplus commented
結果を確認したいのでマージしてしまいます。

2020-10-28 14:25 UTC, beru commented on sakura_core/apiwrap/StdControl.cpp
> +		strText.assign( strText.data(), actualCopied );
assign メソッドではなく resize メソッドの呼び出しに置き換えるのに心理的に抵抗が無ければそうした方が良いのではないかと自分も思います。というかそれに変える事によるデメリットってあるんでしょうか？メリットとしては安心感でしょうか？

> ここは実際にはコピーは行われずlength)だけが更新されます。

自分は実装は確認していませんが assign で自己代入で長さを縮める操作をする場合はバッファの指定長の位置に null terminator の書き込みとかも行うんじゃないかと想像してます。

さて、動いているから問題ないだろと言われたら明確な反論は出来ないです…。

2020-10-28 14:32 UTC, beru commented on sakura_core/apiwrap/StdControl.cpp
> +	bool DlgItem_GetText( HWND hDlg, int nIDDlgItem, std::wstring& strText )
ヘッダ側の他の関数と同様にインライン関数にしてしまうのが良い気がします。
`/LTCG (リンク時のコード生成)` があるから不要と言われるかもしれませんが、ヘッダファイルの行数を増やす事で目grepに頼るプログラマの眼神経に負荷を与える事を思い浮かべて大きな自己満足を得る事が出来ます。

2020-10-28 14:35 UTC, beru commented on sakura_core/dlg/CDlgFind.cpp
> +	if( !ApiWrap::DlgItem_GetText( GetHwnd(), IDC_COMBO_TEXT, strText ) || strText != m_strText ) {
`IDC_COMBO_TEXT` の HWND を取る操作を Get と Set で2回繰り返していることが気になります。

2020-10-28 14:48 UTC, beru approved these changes
ビルドでエラーが起きないで起動して簡単な操作が出来る事は確認しました。
変更箇所が多いので変更箇所それぞれに対応する動作確認は取っていません。

2020-10-29 00:01 UTC, sanomari commented
> ビルドでエラーが起きないで起動して簡単な操作が出来る事は確認しました。
> 変更箇所が多いので変更箇所それぞれに対応する動作確認は取っていません。

お手数おかけしました。change requiredを無視するのはよくないと思ってお願いしていました。

2020-10-29 00:06 UTC, merged

2020-11-15 08:24 UTC, sanomari commented
いま数えてみたら残数302でした。

静的解析の結果で、この修正と同じ内容の警告がいくつか残っていることに気づきました。

2020-11-16 13:58 UTC, berryzplus commented
いま335件ですね。

SonarQubeのビルドは4本走っているので、バグの数は日によって異なります。
（Win32/x64、Debug/Releaseの組み合わせで4本です。）

今日の分は x64 - Release のビルドが最後に終わってるから、致命的にダメな警告がちょっと多いってことみたいです。