デバッグ実行時に外部コマンド実行ダイアログを開くとwarning_point関数で止まる問題を修正する
sakura-editor/sakura pull request #1440
Opened 2020-10-26 17:23 UTC by suconbu

#  PR の目的

外部コマンド実行ダイアログを開く時、`StaticVector`の有効範囲外参照 (要素数 0 の時に 0 番目を参照) により`warning_point`関数でブレークしてしまう点を解消します。
この現象は「名前」の履歴がない状態において 100% 発生します。

ただ、有効範囲外ではありますが有効なメモリ領域が参照され空文字列が取得されているために、実動作上の問題にはなっていないようです。

※ https://github.com/sakura-editor/sakura/pull/1421 の確認中に発見しました。

##  カテゴリ

- 不具合修正

##  PR の背景

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

* 履歴の数が 0 の場合にはコンボボックスへのデータ設定をスキップします。(コマンド履歴、カレントディレクトリについて)

##  テスト内容

1. VisualStudio でデバッグ実行を開始する。
2. 履歴の管理ダイアログを開き、「コマンド」「カレントディレクトリ」の履歴をそれぞれすべて削除する。
3. 外部コマンド実行ダイアログを開く。
* 確認: `warning_point`関数でブレークしないこと。

##  PR の影響範囲

##  関連 issue, PR

##  参考資料

2020-10-27 01:41 UTC, berryzplus requested changes
変更目的は理解しました。やったほうあいいと思います。

コンボを一旦クリアする処理をif文の外に出す件と
const付ける件は修正してから入れたいです。

2020-10-27 01:41 UTC, berryzplus commented on sakura_core/dlg/CDlgExec.cpp
> -	wcscpy( m_szCommand, m_pShareData->m_sHistory.m_aCommands[0] );
ここが問題箇所ですね :smile:

2020-10-27 01:41 UTC, berryzplus commented on sakura_core/dlg/CDlgExec.cpp
> +		Combo_ResetContent( hwndCombo );
この2行はif文の外側でやるべきだと思います。
構造的に、反映するデータがあろうとなかろうと一旦クリアするロジックだと思いますので。

2020-10-27 01:41 UTC, berryzplus commented on sakura_core/dlg/CDlgExec.cpp
> +	int nCommandsCount = m_pShareData->m_sHistory.m_aCommands.size();
この変数宣言にツッコミ２件あります。

* 変更不可にすると困る場合を除いて、constを付けるべきだと思います。
* `size()` の戻り値を受けるのに型が `int`なことに違和感があります。  
size()の戻り型って普通は std::size_t ですよね？ :smiley:

2020-10-27 16:12 UTC, suconbu commented on sakura_core/dlg/CDlgExec.cpp
> +		Combo_ResetContent( hwndCombo );
そうですね。移動します。

2020-10-27 16:16 UTC, suconbu commented on sakura_core/dlg/CDlgExec.cpp
> +	int nCommandsCount = m_pShareData->m_sHistory.m_aCommands.size();
* const をつけます。
* StaticVector::size() が int を返すのでした。
https://github.com/sakura-editor/sakura/blob/d0a92d064b9b13921ee57a0a7a37f66d80364669/sakura_core/util/StaticType.h#L41

2020-10-27 16:22 UTC, suconbu commented
> コンボを一旦クリアする処理をif文の外に出す件と
> const付ける件は修正してから入れたいです。

指摘頂いた点が修正できましたのでご確認お願いします。

2020-10-28 03:11 UTC, berryzplus commented on sakura_core/dlg/CDlgExec.cpp
> +	int nCommandsCount = m_pShareData->m_sHistory.m_aCommands.size();
> * StaticVector::size() が int を返すのでした。

まー、その事実を踏まえて、コメントだけで「修正したい」と言ってないわけですが...(笑)

2020-10-28 03:12 UTC, berryzplus approved these changes

2020-10-28 14:53 UTC, suconbu commented on sakura_core/dlg/CDlgExec.cpp
> +	int nCommandsCount = m_pShareData->m_sHistory.m_aCommands.size();
指摘と誤解してしまいました😅

2020-10-28 14:53 UTC, suconbu commented
レビューありがとうございました。マージします。

2020-10-28 14:53 UTC, merged