コンボボックスのサブクラス化処理を簡素化する
sakura-editor/sakura pull request #1463
Opened 2020-11-11 05:40 UTC by kasumikagari

# PR の目的

#1311 で要望されている機能の実現に向けた関連コードの整理です。
Windows Vista までに導入された API を活用します。

## カテゴリ

- リファクタリング

## PR の背景

検索ダイアログ等のコンボボックスに単語削除機能の追加を試みる途中、既存のコンボボックスのサブクラス化処理が幾分古く冗長であることが気になりました。
単語削除を追加すると関連コードがより複雑になるため、先に整理しておくことで以後のレビュー負担が軽減できるかと思います。

## PR のメリット

- コンボボックスのサブクラス化に関わるコードの複雑度が減ります。
- `SetComboBoxDeleter` の呼び出し時に構造体を用意する必要がなくなります。

## PR のデメリット (トレードオフとかあれば)

ないはずです。

## 仕様・動作説明

- `GetComboBoxInfo` を使う
既存コードでは Edit と ListBox のハンドルを取得するために `WM_CTLCOLOR*` を目的外利用していましたが 、同じ情報がこの関数で取得できるためハックを除去します。

- `SetWindowSubclass` を使う
元の `WNDPROC` を保存・リストアするコードが除去できます。

- `SComboBoxItemDeleter` 構造体の廃止
構造体のメンバが `HWND` と `CRecent*` のみになったため、プロシージャの引数（`HWND`）とウィンドウプロパティ（`CRecent*`）で代替してしまいます。

## テスト内容

検索ダイアログ等のコンボボックスの既存動作が変更されないことを手動で確認します。
サブクラス化で実現している履歴の削除動作に対して特に確認が必要です。

## PR の影響範囲

`SetComboBoxDeleter` を使用する各ダイアログに影響しますが、動作は変更しません。

## 関連 issue, PR

#1311

## 参考資料

[後ほど PR 予定の完成形](ab827ae1a9bb5a66f6906bd42415e29a18a5fb4d)

2020-11-11 14:12 UTC, beru reviewed
SetComboBoxDeleter メソッドを呼び出す際に GetItemHwnd メソッドを呼び出してコントロールのHWNDを取得して渡している記述が結構有るのが気になりました。GetItemHwnd メソッドを内部で呼び出す SetComboBoxDeleter メソッドのオーバーロードを追加するのはどうでしょうか？

2020-11-11 14:37 UTC, kasumikagari commented
SetComboBoxDeleter は static なのに対して GetItemHwnd は non-static であるためオーバーロードはできません。
本質的には CDialog とは関係のない関数ですから独立させてしまって、CDialog 専用のヘルパー関数を追加するほうが良いかなと思います。

2020-11-11 17:01 UTC, berryzplus reviewed
まず、趣旨には賛成です。

このPRによって、少なくとも利用側のコードは簡素化できているように見えました。
逆に、共通コード部分の複雑度が高まったように見えていて、全体把握ができてる自信がないです。

現状でOK/NGを判断できそうにないので、一旦コメントだけ残しておきます。

2020-11-12 11:03 UTC, kasumikagari commented on sakura_core/dlg/CDialog.cpp
> +	data->pEditWndProc = reinterpret_cast<WNDPROC>(::GetWindowLongPtr(info.hwndItem, GWLP_WNDPROC));
C-style にしてみました。

> OSとの接合部に関しては例外的に「C-Styleキャストしてよい」になってたと思います

これはサクラエディタプロジェクト内の指針ということでしょうか？
「C-style は使うな」という話は聞いたことがあっても逆はあまり聞きませんが…。

2020-11-12 19:06 UTC, berryzplus commented on sakura_core/dlg/CDialog.cpp
> +	data->pEditWndProc = reinterpret_cast<WNDPROC>(::GetWindowLongPtr(info.hwndItem, GWLP_WNDPROC));
> > OSとの接合部に関しては例外的に「C-Styleキャストしてよい」になってたと思います
> 
> これはサクラエディタプロジェクト内の指針ということでしょうか？

出典はたぶん「c++によるプログラミングの原則と実践」というC++の入門書です。
（ちゃんと確認してないので嘘かも知らん・・・。

サクラエディタプロジェクト内に「指針」はありません。

そういうことにしておかないとあちこち置換しないといけなくて面倒だからそういうことにしておいたほうがいいんじゃないか、という個人的な見解です。

C++の一般的なガイドラインでは `そもそもキャストが必要になるようなコードを書くな！` だと思っています。
https://www.aristeia.com/EC3E/3E_item27.pdf

2020-11-14 15:37 UTC, berryzplus commented on sakura_core/dlg/CDialog.cpp
> +	                         UINT_PTR uIdSubclass, DWORD_PTR dwRefData)
[SetWindowSubclass](https://docs.microsoft.com/ja-jp/windows/win32/api/commctrl/nf-commctrl-setwindowsubclass) の仕様じゃヴォケ！と返してもらえれば、普通に「そうなの、じゃ仕方ないわね。」になる指摘でした。

本当は、この辺のド基礎の情報を参考資料に貼っておいて欲しいです。（わがまま
https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nc-commctrl-subclassproc

2020-11-14 17:01 UTC, berryzplus requested changes
一通り内容を確認して、問題ないかな～という結論に至りました。

先に書いていた「共通関数が複雑になった気がする」の改善点をあげてみたのでご検討ください。

理由があれば対応なしも可だと思います。
そうであれば、その旨コメントを。

2020-11-15 14:07 UTC, kasumikagari commented on sakura_core/dlg/CDialog.cpp
>  		if( wParam == VK_DELETE ){
WM_KEYDOWN をトレースしながらいろいろと試してみましたが、「実行されない」で正しいかもしれません。
ドロップダウン展開中は Edit にフォーカスが固定される構造らしく、ListBox 側の WM_KEYDOWN は Edit から一部（確認できたのは VK_UP と VK_DOWN）がリダイレクトされる形で届いているように見えます。
「ここは通らない」ことの証明はできませんが、消してしまっても見た感じの挙動が変わらないので不要と言ってしまっても実害がなさそうな雰囲気ではあります。

2020-11-15 14:11 UTC, kasumikagari commented on sakura_core/dlg/CDialog.cpp
> +	                         UINT_PTR uIdSubclass, DWORD_PTR dwRefData)
「レビュワーさんの方が明らかに詳しいし細かく書く必要ないかも」とか勝手に思ってました。横着をしてすみません。
あらためて考えればレビューに限らず複数の方が読まれるものなので具体的に書くべきことですよね…。

2020-11-15 14:17 UTC, kasumikagari commented on sakura_core/dlg/CDialog.cpp
> +	::SetWindowSubclass(info.hwndItem, SubEditProc, 0, (DWORD_PTR)hwndCtl);
ご指摘の通りの方向で問題なさそうですのでそのように修正します。

2020-11-15 14:21 UTC, kasumikagari commented on sakura_core/dlg/CDialog.cpp
> -			HWND hwndCombo = data->hwndCombo;
#1311 の機能追加のために `case WM_CHAR:` の追加を予定していまして、そちらで `hwndCombo` を参照する予定があるためswitch 外に移動しています。

2020-11-16 01:01 UTC, berryzplus approved these changes

2020-11-20 13:32 UTC, berryzplus commented
@sakura-editor/sakura-developers 
3回目PRなのでinvite出しちゃいましたが、
既にapprove済なので何かあれば早めのレビューをお願いします。

2020-11-22 01:48 UTC, kasumikagari commented
丁寧なレビューをありがとうございました。
他にコメントがなければ今夕ぐらいにマージしたいと思います。

2020-11-22 07:29 UTC, merged