GetDateTimeFormatの入出力をWCHAR*からstd::wstring(_view)に変更する
sakura-editor/sakura pull request #1489
Opened 2020-12-20 02:22 UTC by suconbu

#  PR の目的

GetDateTimeFormat の使い勝手を良くしつつ実装を簡素化します。

##  カテゴリ

- 仕様変更

##  PR の背景

https://github.com/sakura-editor/sakura/pull/1483#issuecomment-747202632 にて提案された内容を元にしています。

##  PR のメリット

* GetDateTimeFormat を使う時に必要バッファサイズを計算する必要がなくなります。
* 結果格納用の配列が不要となりソースコードからマジックナンバーを排除できます。
* GetDateTimeFormat の複雑度 (Cyclomatic complexity) が減少します。(18 -> 12)

##  PR のデメリット (トレードオフとかあれば)

特にないと思います。

##  仕様・動作説明

##  PR の影響範囲

GetDateTimeFormat を使用して日時文字列を取得している処理に影響があります。

##  テスト内容

GetDateTimeFormat を使用している処理がデグレしていないことを確認します。
※ #1483 と同じテスト内容です。

### テスト1 - 無題の文書のファイル名

1. 無題の文書が開いている状態で「ファイル」→「名前を付けて保存」を選択する。
確認1：名前を付けて保存ダイアログのファイル名に現在日時が付加されていること。

### テスト2 - バックアップファイル名

1. 「共通設定」→「バックアップ」にて「詳細設定する」をチェック、「保存時の日時・時刻を使用」を選択する。
2. 「詳細設定する」直下のテキストボックスに `.\$0_%Y%m%d_%H%M%S.*` を入力する。
3. 任意のファイルを開き、バックアップ付きで上書き保存する。
確認1：保存先ディレクトリに、現在日時が付加されたファイル (バックアップファイル) が作成されていること。
4. バックアップファイルを削除する。
5. 上書き保存したファイル (バックアップではない方) の更新日時をメモする。
6. 「共通設定」→「バックアップ」で「前回のファイル更新時の日付・時刻を使用」を選択する。
7. 再度、バックアップ付きで上書き保存する。
確認2：保存先ディレクトリに、「4」でメモした日時が付加されたファイルが作成されていること。

##  関連 issue, PR

#1483

##  参考資料

2020-12-20 13:45 UTC, k-kagari requested changes
自分のちゃぶ台返し的なコメントに対応してくださりありがとうございます。取り急ぎコードだけをみて指摘させていただきました。
細かい点については無言スルーで全然OKです。動作についてはこれから確認します。

2020-12-20 13:45 UTC, k-kagari commented on sakura_core/util/format.cpp
> +		}else if( f == L'\0' ){
質問ですが、std::wstring_viewの途中にnull文字があった場合に処理を打ち切るのは仕様ですか？ 仕様なのであればコメントへの明記とテストの用意があったほうがいい気がします。

2020-12-20 13:45 UTC, k-kagari commented on sakura_core/util/format.h
> +
`#include <string_view>`もあるべきではないかと。コンパイル通るみたいなので構わないといえばそうなのですが。

2020-12-20 14:40 UTC, suconbu commented on sakura_core/util/format.cpp
> +std::optional<std::wstring> GetDateTimeFormat( std::wstring_view format, const SYSTEMTIME& systime )
私も最初は不要かもと思ったのですが、将来何かしらエラー処理が実装された時に std::optional で返す仕様にしておいた方が無難かなと思いました。いかがでしょうか。

2020-12-20 14:49 UTC, k-kagari commented
動作確認を行いました。問題なさそうです。

2020-12-20 14:51 UTC, suconbu commented on sakura_core/util/format.cpp
> +std::optional<std::wstring> GetDateTimeFormat( std::wstring_view format, const SYSTEMTIME& systime )
> 将来何かしらエラー処理が実装された時に

この関数に限ってはなさそうな気がしてきましたので std::wstring を返すよう仕様変更します。

2020-12-20 14:59 UTC, suconbu commented on sakura_core/util/format.cpp
> +		}else if( f == L'\0' ){
はい、そのような仕様としていますのでコメントに追記致します。

テストはこちらが対応しています。
https://github.com/suconbu/sakura/blob/c9876e06d9116d1809abc0aeb5da1e5a970fb4b9/tests/unittests/test-format.cpp#L71

2020-12-20 14:59 UTC, k-kagari commented on sakura_core/util/format.cpp
> +std::optional<std::wstring> GetDateTimeFormat( std::wstring_view format, const SYSTEMTIME& systime )
将来のために準備をしても活用されない予感がします。今回のように呼び出し側ごと書き換えておしまいになりそうです。optionalを受け取った側の処理が特に意味なく複雑になりますから、個人的な意見としては不要派です。

2020-12-20 15:02 UTC, k-kagari commented on sakura_core/util/format.cpp
> +		}else if( f == L'\0' ){
回答ありがとうございます。見落としていました。

2020-12-20 15:09 UTC, berryzplus commented on sakura_core/util/format.h
> +
あるべきなのかも知れないですが、include 実績は殆どない認識っす。
なので、入れなくてもいいような気はします。
※stringをincludeしない場合、話は別。

2020-12-20 15:13 UTC, berryzplus commented on sakura_core/util/format.cpp
> +	for( const auto f : format ){
どちらかと言うと、「f」って変数名が分かりづらいと思いましたｗ

2020-12-20 15:27 UTC, berryzplus commented on sakura_core/util/format.cpp
> +	bool esc = false;
%% で % を出力する特徴から「エスケープシーケンスの一種」という説明をすることが（たまに）あります。

自分なら正規表現 `m/(%%|%[GetDateFormatが認識するメタ文字]|[^%])+/` で取得した部分文字列を、
GetDateFormat に委譲するコードを書くような気がします。

その辺はたぶんに好みの問題であるような気がしています。。。

2020-12-20 15:35 UTC, berryzplus commented on sakura_core/util/format.cpp
> +std::optional<std::wstring> GetDateTimeFormat( std::wstring_view format, const SYSTEMTIME& systime )
確保するメモリ量が小さいので std::wstring で返す仕様で問題ない気がします。

フォーマット文字列にエラーがある場合に例外を投げるかどうかについては意見が分かれると思います。
良識に従えば std::invalid_argument 例外で、既存に合わせるとエラーがあっても無視するになるので。

2020-12-20 15:48 UTC, suconbu commented on sakura_core/CBackupAgent.cpp
> +				dateTimeString = GetDateTimeFormat( (const WCHAR*)bup_setting.m_szBackUpPathAdvanced, ctimeLastWrite.GetSYSTEMTIME() );
c_str() で対応しました。

2020-12-20 15:50 UTC, suconbu commented on sakura_core/util/format.cpp
> +	result.reserve( format.length() * 2 );
そのままとしました。

2020-12-20 15:54 UTC, suconbu commented on sakura_core/util/format.cpp
> +	bool esc = false;
名前を見直しました。

2020-12-20 15:54 UTC, suconbu commented on sakura_core/util/format.cpp
> +	for( const auto f : format ){
そのままとしました。

2020-12-20 15:57 UTC, suconbu commented on sakura_core/util/format.cpp
> +				(void)wsprintf( str, L"%d", systime.wYear );
* (void) は戻り値の読み捨てを明示する意図で付けています。改めて周辺のソースコードを確認するとあまり見られなかったためなしとしておきました。
* swprintf に変更しました。

2020-12-20 15:59 UTC, suconbu commented on sakura_core/util/format.h
> +
追加しました。

2020-12-20 16:17 UTC, suconbu commented on sakura_core/CBackupAgent.cpp
> +		std::wstring formatString = GetDateTimeFormat( bup_setting.m_szBackUpPathAdvanced.c_str(), time );
* この時点の文字列にはまだ `$0` などの変換指定子が含まれているため変数名を見直しました。(dateTimeString -> formatString)
* 重複していた箇所を括り出しました。

2020-12-20 16:50 UTC, suconbu commented on sakura_core/util/format.cpp
> +	for( const auto f : format ){
> どちらかと言うと、「f」って変数名が分かりづらいと思いましたｗ

入れ違いでコメント頂いたこと気づいていませんでした😅
どんな感じだと分かりやすいでしょうかね？「formatChar」などでしょうか。(今後の参考に……)

2020-12-21 08:35 UTC, k-kagari reviewed
変更内容に問題はないと感じましたが、既存ループにバグを発見してしまいました。そちらの修正を含めていただければと思います。別PRにされるのであればコメントください。即approveいたします。

2020-12-21 08:35 UTC, k-kagari commented on sakura_core/CBackupAgent.cpp
>  			{
共通処理をくくりだしたことでこのブロックが不要になっています。除去するかの判断はお任せします。

2020-12-21 08:35 UTC, k-kagari commented on sakura_core/CBackupAgent.cpp
>  				while( *q ){
このループには問題があります。書式設定の末尾が $ だった場合、末尾のnull文字の先にある値を終了条件の判定材料として読み取り始めるのです。
これは既存のバグです。今回の変更によって壊れたものではありませんが、本PRに修正を含めて速やかに修正するのが望ましい性質のものではないかと思います。

2020-12-21 08:35 UTC, k-kagari commented on tests/unittests/test-format.cpp
> +	// 変換指定子の解釈
このコメントは+1したいです。読みやすくなりました。

2020-12-21 11:56 UTC, berryzplus commented on sakura_core/util/format.cpp
> +	for( const auto f : format ){
> どんな感じだと分かりやすいでしょうかね？「formatChar」などでしょうか。(今後の参考に……)

意味論的な最適を探ると `spec` になるのかな・・・ 
変換指定子なので `flag` でも良いとは思います。

あえて原始的な文字解析をやってることが分かるように、単に ch としても良い気はします。

2020-12-21 12:30 UTC, suconbu commented on sakura_core/CBackupAgent.cpp
>  			{
除去しました。

2020-12-21 12:37 UTC, suconbu commented on sakura_core/CBackupAgent.cpp
>  				while( *q ){
修正を行いました。
末尾が `$` の場合に速やかに while ループを抜けることを確認しました。

※GetDateTimeFormat も以前 (#1483 反映前) は同じような問題があったようです。(書式文字列末尾が `%` の場合)

2020-12-21 12:38 UTC, suconbu commented on sakura_core/CBackupAgent.cpp
>  			{
除去しました。

2020-12-21 12:43 UTC, k-kagari approved these changes
6b2c49c01 で手動テストを実施しました。LGTM です。

2020-12-21 14:44 UTC, suconbu commented on sakura_core/util/format.cpp
> +	for( const auto f : format ){
確かに ch は C 言語で書かれた字句解析処理などでよく見かける気がします。

2020-12-21 14:54 UTC, suconbu commented
ありがとうございました。お陰様ですっきりさせることができました。
生配列で文字列をやりとりする関数は引き続き減らしていきたいですね。

2020-12-21 14:55 UTC, merged