help配下のShift_JISファイルのために.gitattributesを追加する
sakura-editor/sakura pull request #1518
Opened 2021-01-24 10:51 UTC by berryzplus

#  PR の目的

タイトル通りです。（👈書いてみたかった）

##  カテゴリ
- その他の問題

##  PR の背景

#1458 とかでやっている話の一つです。

##  PR のメリット

help配下の見慣れない拡張子のファイル群がShift_JISエンコードのテキストファイルであることが明確になります。

##  PR のデメリット (トレードオフとかあれば)

とくに思い当たりません。

##  仕様・動作説明

現状でShift_JISで登録されているファイルをUTF8で登録するように変更します。
checkout後のworking-treeにはShift_JISのファイルができるようになります。
（つまり、目に見える変更点は特にありません。）

これらファイルがShift_JISであることがリポジトリ内に現れるので少し分かりやすくなります。
他には、GitHub上で差分表示される際に、文字コードが誤判定されて化ける可能性をゼロに出来ます。

##  PR の影響範囲

アプリへの影響はありません。

##  テスト内容

gitの「お約束」として確立された手法なのでテスト不要と思います。

##  関連 issue, PR

#1458

##  参考資料

2021-01-27 09:35 UTC, sanomari requested changes

2021-01-27 09:35 UTC, sanomari commented on help/macro/macro.HHP
> +Title=マクロリファレンス
これは？

2021-01-27 12:44 UTC, sanomari approved these changes

2021-01-28 09:54 UTC, berryzplus commented
レビューありがとうございます。
マージしちゃいます。

2021-01-28 09:54 UTC, merged