プロポーショナル版で禁則処理を使えるようにする
sakura-editor/sakura pull request #1543
Opened 2021-02-17 04:15 UTC by kazasaku

# PR の目的

禁則処理が使えない問題を解決します。

## カテゴリ

- 不具合修正

## PR の背景

過去に行われたプロポーショナルフォント対応の際、内部で取り扱うレイアウト上の桁数が半角単位からピクセル単位に変更されました。
禁則処理用の関数に対して、これに対応する変更がなされなかったため、条件分岐が正しく判定されなくなっていました。
（※似たような機能で「改行ぶら下げ」がありますが、これは正常に機能しているようです。）

##  PR のメリット

自明だと思います。

## PR のデメリット (トレードオフとかあれば)

## 仕様・動作説明

patchunicode#1034として登録されているパッチをもとに文字幅の換算処理を追加して、以前と同様に「行末付近でのみ判定を行う」ようにしました。
句読点ぶら下げの時は行末の半角2桁、行頭・行末禁則の時は行末の半角4桁の範囲内に達したときに限り禁則処理の実施判定が行われます。
（この範囲に現在位置にある文字と次位の文字が収まらず、折り返しが発生する時に禁則処理が実施されます。）

また`IsKinsokuPosHead()`及び`IsKinsokuPosTail()`は、これまで行の残り桁数と各文字の桁数の組み合わせで判定を行っていましたが、文字幅がピクセル単位の数値となった現在、この方法では正しく判定ができません。
そのため、`IsKinsokuPosKuto()`の条件式と同様に文字幅（注：ここでいう文字幅は現在の仕様上文字間隔を含みます）が行の残り幅より大きいかどうかで判定を行うようにし、単位の違いに関わらず判定できるようにしました。

そのほか、次の変更を含みます。
- 関係する関数に記述されたコメントで内容が現状にそぐわない箇所を更新しました。
- 禁則の判定関数に`const`修飾子の有り/無しが混在していたので有りに統一しました。
- `IsKinsokuPosKuto`関数をヘッダファイルからソースファイル（`CLayoutMgr_New.cpp`）に移動しました。
- 未使用の判定関数があったので、パッチによってコメントアウトされるコードとともに除去しました。
  - 除去した`_ExistKinsokuHead()`は`IsKinsokuHead()`と、`_ExistKinsokuKuto()` は`IsKinsokuKuto()`と等価です。

## PR の影響範囲

句読点ぶら下げ・行頭禁則・行末禁則のいずれかが有効になっている環境の次のビュー
- 編集ビュー
- 印刷プレビュー

## テスト内容

- 各禁則処理の動作を以前のバージョンと比べて確認しました。
  - 正常動作する最後のバージョンはv2.2.0.1、動作しなくなったのはv2.3.0.0以降です。
  - 比較画像を後で用意しておきます。

### テスト1：編集ビューにおける禁則処理

1. タイプ別設定に「テキスト」を一時適用する
   - 「テキスト」であれば、行頭・行末禁則の対象文字に既定値が設定されます。
2. 句読点ぶら下げ・行頭禁則・行末禁則を有効にする
   - 確認を容易にするため、折り返し方法を「指定桁で折り返し」に設定し、適度な桁数を設定するとよいです。
4. 禁則対象文字(下記参照)が行頭・行末にくるようなテキストを入力し、動作を確認する

### テスト2：印刷プレビューにおける禁則処理

1. 印刷ページ設定で句読点ぶら下げ・行頭禁則・行末禁則を有効にする
2. 禁則対象文字(下記参照)が行頭・行末にくるようなテキストを入力する
3. 印刷プレビューを表示して動作を確認する

### 補足：禁則対象文字の既定値（タイプ別設定がテキストの時）
- 句読点ぶら下げ（8種類）
   `、。，．､｡,.`
- 行頭禁則（51種類）
   `!%),.:;?]}\xa2°’”‰′″℃、。々〉》」』】〕゛゜ゝゞ・ヽヾ！％），．：；？］｝｡｣､･ﾞﾟ￠`
   - \xa2は半角セント記号です。
- 行末禁則（22種類）
   `$([\\{\xa3\xa5‘“〈《「『【〔＄（［｛｢￡￥`
   - \xa3は半角ポンド記号、\xa5は半角円記号です。

## 関連 issue, PR

## 参考資料

[patchunicode#1034](https://sourceforge.net/p/sakura-editor/patchunicode/1034/)

2021-02-17 09:16 UTC, k-kagari commented on sakura_core/doc/layout/CLayoutMgr_New.cpp
> +bool CLayoutMgr::IsKinsokuPosKuto( CLayoutInt nRest, CLayoutInt nCharChars ) const
もとからあった関数ですけれど、短いですね…。引数を比較しているだけなのでメンバ関数である必要もないようです。

2021-02-17 09:16 UTC, k-kagari commented on sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
> +	 && ( pWork->eKinsokuType == KINSOKU_TYPE_NONE ) )
内側の括弧、なくても意味は同じですね。

除去してほしいという要求ではありません。元からですし…。

2021-02-17 09:16 UTC, k-kagari commented on sakura_core/doc/layout/CLayoutMgr_New.cpp
> +	if( nRest < nCharKetas ){
この分岐はなくても大丈夫のような気がします。nCharKetas2 が負になり得るのであれば話が変わってきますが…。

2021-02-17 13:07 UTC, berryzplus commented
## 質問
このPRって「内部で扱う水平方向の内部単位をpxに統一したい」であっています？

## 疑問
* サクラエディタは元々、古代のコンソールのように半角6px、全角12pxの等幅フォントを表示する前提で書かれています。これはそもそもの前提として、文字コードに対応するフォントグリフ（≒字形）を検索するには時間がかかる（に違いない）を起点にして考案された描画スタイルと考えられます。検索に時間がかかるならキャッシュしてしまえ、という考え方自体は正しいのですが、本当に時間がかかるの？については疑問を持っています。
* プロポーショナルフォントに対応したことにより、半角・全角のフォント幅は一様ではなくなりました。半角iの幅は超狭いですし、全角Wの幅は漢字よりも広くなります。文字コードに対応するフォントグリフの検索に本当に時間がかかるのであれば、従来通りキャッシュを行う手法は有効と考えられますが、個人的にはグリフの検索に時間がかかるの仮定がどうもしっくりきません。
* プロポーショナルフォントに含まれている情報はグリフ（≒字形）だけではありません。サクラエディタのプロポーショナルフォント実装は文字間隔をユーザーが指定する固定の px 分だけ空けるようになっていますが、本来プロポーショナルフォントが持つ情報の中には、特定の文字の連続を描画するのに適切な間隙の量もあります。（もちろん、その情報がないフォントファイルもある。）おそらく、本当にプロポーショナルフォントに対応したいのであれば、従来サクラエディタが行っている、1文字ずつ描画するをやめて、プロポーショナルフォント向けにビューを組みなおすべきなんだと思います。（注：既に特定の状況下でひとかたまりの文字列をまとめて描画する処理を取り込み済みですが、それとは関係ありません。）

もちろん、目先の不具合っぽいものに対応しようぜ！って趣旨であれば、どうあるべきかは横に置いておいてマージ前提で話をすすめていくことに異論はありません。

2021-02-17 13:55 UTC, kazasaku commented on sakura_core/doc/layout/CLayoutMgr_New.cpp
> +	if( nRest < nCharKetas ){
コメントありがとうございます。

たしかに要らないかも知れませんね。
残り1桁分しかない行に2桁分の文字を入れようとしたときに成立しそうですが、nCharKetas2が負数にならない限りはもう一つのif文で対応できそうです。
文字間隔の設定値が負数だったり、WCODE::CalcPxWidthByFont()の戻り値が負数だったりすれば、ここに負数が入ってくるのではないかと。
確認しておきます。

2021-02-17 14:42 UTC, kazasaku commented
> 「内部で扱う水平方向の内部単位をpxに統一したい」

そういう意図はないです。
この不具合がユーザーに指摘され(2016-01-23)てから[5年が経ちました](https://sakura-editor.github.io/bbslog/sf/general/8106.html)。

2021-02-18 15:18 UTC, berryzplus commented
一旦了解しました。

では、どなたか動作確認していただいてコメントつけてもらえれば、自分はapproveで良いと思います。

2021-02-19 12:17 UTC, k-kagari commented
編集ビュー・印刷プレビューともに正しく動作しているものと思います。

2021-02-20 00:26 UTC, kazasaku commented on sakura_core/doc/layout/CLayoutMgr_New.cpp
> +bool CLayoutMgr::IsKinsokuPosKuto( CLayoutInt nRest, CLayoutInt nCharChars ) const
ワードラップ（＝欧文の禁則処理）で使う関数に_GetKeywordLength()というstatic関数がありましたので、これに倣ってstatic化しておきます。

2021-02-20 01:05 UTC, kazasaku commented
編集ビューのみではありますが、変更前後の比較画像を置いておきます。
左がv2.4.1、右がこのPR（ f6babac9f4516df1c077ef7c4c6173b8b14d3320 ）です。

![前後比較：編集ビュー](https://user-images.githubusercontent.com/67105596/108576975-d1df6580-7362-11eb-9674-1bfb583571b4.png)

2021-02-20 02:53 UTC, suconbu commented
恥ずかしながらサクラエディタにこんなワープロソフトばりの機能があることをこれまで意識してませんでした💦

私も動作を見させてもらったところ、折返し位置の手前に絵文字がある状態でその後に行頭禁則文字を置いた時に、カーソル位置や文字挿入がおかしくなることがあったため動画を撮ってみました。
なんとなく修正前からの潜在問題のような気がしますが。。

![fix_line_breaking_process_test](https://user-images.githubusercontent.com/11252784/108580768-4cfb4880-7370-11eb-8b40-cb48199394fb.gif)

※ https://github.com/sakura-editor/sakura/pull/1543#issuecomment-782513118 の Win32 にて確認しました。

2021-02-20 09:03 UTC, kazasaku commented
suconbu様、お疲れ様です。この機能自体は2002年の春に実装されています（ANSI版の開発掲示板による）。
> 折返し位置の手前に絵文字がある状態でその後に行頭禁則文字を置いた時に、カーソル位置や文字挿入がおかしくなる

とりあえず、禁則対象文字の手前がサロゲートペアの場合、CNativeW::GetHabaOfCharが、下位サロゲートに対して0を返すため、IsKinsokuPosHeadは「処理位置ではない」と判断したことが判明しました。
例示された画像で行頭禁則が効いていないように見えるのはこれによるものと考えています。

引き続き調査を続けます。

2021-02-20 14:18 UTC, sanomari commented
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/6c4a9474d282d89b0f89980e1deba92e8852fccb4933755a65493099ed25f18e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302e706e67">](https://sonarcloud.io/component_measures?id=sakura-editor_sakura&pullRequest=1543&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=sakura-editor_sakura&pullRequest=1543&metric=new_coverage&view=list)

個人的には、修正したコードのカバレッジが完全にゼロなのが気になっています。

* マクロから指定した文字列を挿入する
* マクロから折り返しモードを変更する
* マクロから折り返し桁数を変更する
* マクロから「元に戻す」を実行して文字列挿入をなかったことにする

印刷プレビューの折り返し処理コードを走らせるのは無理にしても、実行させてみない限りは追加した分岐が必要なことを証明できないように思います。

2021-02-21 03:44 UTC, kazasaku commented
仮ですがサロゲートペア対策を入れてみました。
サクラエディタの禁則処理は、対象文字の前後にある文字とともに次の行に送る、追い出し処理によるものなのですが、
サロゲートペアの時に下位側も読み取っていたため、処理が行われる時に下位側だけが次の行に送られていました。

2021-02-21 04:29 UTC, berryzplus requested changes
動作確認 https://github.com/sakura-editor/sakura/pull/1543#issuecomment-782039880 もしていだだいたので、基本「行き」でよいと思っています。

> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1543&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1543&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1543&resolved=false&types=CODE_SMELL)

対応できない種類のCodeSmellsは放置でよいと思っていますが、今回は対応できそうなので修正をお願いしたいです。
`[[nodiscard]]` は付けとくべきかな？と思います。
メンバを変更しない関数の`const`も付けとくべきかな？と思います。

カバレッジ＝ゼロに関してはどうなんですかね？
一応、「やったほうがいいけど必須ではない」の認識です。

2021-02-21 07:05 UTC, suconbu commented
> 仮ですがサロゲートペア対策を入れてみました。

調査と対策ありがとうございました。
https://github.com/sakura-editor/sakura/pull/1543#issuecomment-782545028 の問題が解消されていることを確認しました。

2021-02-21 07:38 UTC, kazasaku commented
suconbuさん、ご確認ありがとうございました。

2021-02-21 11:21 UTC, suconbu commented
> 余談ですが、MSゴシックでも絵文字の文字幅が全角・半角のどちらでもないということに気が付きました。

MS ゴシックには絵文字は収録されていないはずですので、フォントフォールバックで絵文字の所だけ Segoe UI Symbol あたりが使われていそうですね。

2021-02-21 15:50 UTC, k-kagari approved these changes
指摘するべき問題はなさそうです。

何らかの自動テストは確かにあるべきだと思います。追加タイミングについてはお任せします。

2021-02-22 13:59 UTC, berryzplus approved these changes
> 追加タイミングについてはお任せします。

自分もそれでよいと思います。

2021-02-22 15:05 UTC, kazasaku commented
皆様、ご確認ありがとうございました。

2021-02-22 15:13 UTC, merged