キャレット位置の文字情報をステータスバーに設定する際の再描画をまとめる
sakura-editor/sakura pull request #1601
Opened 2021-03-21 09:54 UTC by beru

#  PR の目的

カーソルキーを押してキャレット位置を変えるとステータスバーの表示が更新されますが、その処理を効率化するのが目的です。

##  カテゴリ

- 速度向上

##  PR の背景

開発環境(Visual Studio)のメニューの Debug > Performance Profiler で CPU Usage にチェックを付けて Start をして、どこの処理に時間が掛かっているのかを確認する事が出来ます。

キャレット位置の文字情報をステータスバーに設定する処理の呼び出し `CMainStatusBar::SetStatusText` における `StatusBar_SetText` に結構処理時間が掛かっていたので対策を行いました。

##  PR のメリット

キャレット位置変更時にステータスバーの更新を行う際の処理が効率化されます。

処理を効率化する事でCPU使用率が下がるのではないかと思います。

##  PR のデメリット (トレードオフとかあれば)

記述が増える事で処理内容が読み取りにくくなります。

元々そこまで目立って重たい処理でも無いので、変更によって処理が軽くなったかを体感できるかというと出来ません。

##  仕様・動作説明

`StatusBar_SetText` の実装は `SB_SETTEXT` メッセージを `SendMessage` 関数で送るものです。

https://docs.microsoft.com/en-us/windows/win32/controls/sb-settext#remarks

によると、

> The message invalidates the portion of the window that has changed, causing it to display the new text when the window next receives the WM_PAINT message.

と書かれていたのでおそらく内部で `InvalidateRect` しているように思えます。

このPRの変更では `WM_SETREDRAW` メッセージを使う事でステータスバーの各パートに文字列を設定する際に個々に描画を行われる事を防ぎます。また各パートに文字列が設定された場合は各パートのRECT領域を取得して結合し、後で `InvalidateRect` を呼び出す事で再描画をまとめる事で表示処理の効率化を図ります。

描画をまとめて行う事で、カーソルキーを押しっぱなしにした場合のステータスバーの表示のちらつきが無くなるかというと、残念ながらそんな事は無いようです。

##  PR の影響範囲

##  テスト内容

### テスト1

手順
- テキストファイル（たとえば README.md とか）を開いた後にカーソルキーを押してキャレット位置を変える操作を行い、ステータスバーの表示が更新されるかどうかを確認

##  関連 issue, PR

##  参考資料

https://docs.microsoft.com/en-us/windows/win32/controls/sb-getrect

https://docs.microsoft.com/en-us/windows/win32/controls/sb-settext

https://docs.microsoft.com/en-us/windows/win32/gdi/wm-setredraw

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-invalidaterect

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unionrect

2021-03-21 11:25 UTC, beru commented
dac4cd3bd281244a944ae3abbcbfc12c58f44c8a で #1592 と同じように拡張スタイル `WS_EX_COMPOSITED` を使う事でステータスバーの表示のちらつきを解消しました。

2021-03-21 11:44 UTC, berryzplus commented
> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL) [<img alt="B" width="16" height="16" src="https://camo.githubusercontent.com/4b339499e8c469ac5f6012ef6c3830c2539c3951e18610e61c98f2e459a94ccf/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f422e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL) [8 Code Smells](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL)

ざっくり2件の指摘が上がっています。
  - 関数呼び出しと同時に index++ してるのをばらしたほうがよい。（×7）
  - ラムダ式が44行もあって長いので、多くても20行程度に整理すべき。

修正内容は見てるので「ええっ！」って感想も分かりますが、なるたけ対応したいです。

2021-03-21 11:48 UTC, beru commented
> 
> 
> > [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL) [<img alt="B" width="16" height="16" src="https://camo.githubusercontent.com/4b339499e8c469ac5f6012ef6c3830c2539c3951e18610e61c98f2e459a94ccf/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f422e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL) [8 Code Smells](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL)
> 
> ざっくり2件の指摘が上がっています。
> 
>     * 関数呼び出しと同時に index++ してるのをばらしたほうがよい。（×7）
> 
>     * ラムダ式が44行もあって長いので、多くても20行程度に整理すべき。
> 
> 
> 修正内容は見てるので「ええっ！」って感想も分かりますが、なるたけ対応したいです。


>     * 関数呼び出しと同時に index++ してるのをばらしたほうがよい。（×7）

については元のコードがそういう記述内容なのでそっとしておきたいです。
ばらす事で可読性が悪化してしまうと思いますし。

>     * ラムダ式が44行もあって長いので、多くても20行程度に整理すべき。

に関してはもっともな指摘だと思います。ここはラムダ式を使わずに do while ループに変更します。

2021-03-21 11:51 UTC, beru commented
しかし `CCaret::ShowCaretPosInfo()` メソッドは行数が多いですね。

このPRの本来の意図はそのメソッド等に入れた変更で再描画を抑制して処理負荷を下げる事ですが、拡張スタイル `WS_EX_COMPOSITED` を付けてちらつきを解消する事の方が効果としては美味しいと思えてきました…。

2021-03-27 04:00 UTC, berryzplus requested changes
先日のレビュー時点に比べて警告が増えているようです。

> [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL) [11 Code Smells](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1601&resolved=false&types=CODE_SMELL)

前回 8件⇒11件

`index++` を修正できないのは了解ですが、他は対応が要ると思っています。

2021-03-28 09:34 UTC, beru commented
> 前回 8件⇒11件
> 
> `index++` を修正できないのは了解ですが、他は対応が要ると思っています。

## `Use the "nullptr" literal.` について

WindowsAPI を呼び出している箇所で引数に NULL を指定している部分ですね。
ここで警告を出すのは間違っていると思いますが簡単に対応できるので変更しておきました。

## `Reduce the number of nested "break" statements from 4 to 1 authorized.` について

これは do-while文を `break` で抜けるのを4箇所ではなくて1個所に減らすようにという指摘ですが、この対応をすると逆に可読性が低下すると思うので変更しません。

do-while 文を使っているのは lambda式が長すぎると静的解析が CodeSmell にしてきたからですが、他の方法で対処するとしたら、`StatusBar_SetText` 関数を呼びだすかどうかを判定する処理を関数化する手段があると思います。

## `Convert this integer literal to a bool literal.` について

do-while文の条件式の部分で整数リテラルではなくてブーリアンのリテラルを使うように変えなさい、という指摘です。
こちらも対応するのもなんか微妙な気がしますが簡単に対応できるので変更しました。

2021-03-28 13:18 UTC, sanomari approved these changes

2021-03-28 14:03 UTC, beru commented
レビューありがとうございました。Mergeします。

2021-03-28 14:03 UTC, merged