IsFileExists()とIsDirectory()でワイルドカードが通過する不具合を修正する
sakura-editor/sakura pull request #1608
Opened 2021-03-26 17:23 UTC by usagisita

タイトルの通りです。
パス検証を導入して、?、\*などパスに使えない文字を事前にはじくようにします。

#  PR の目的
関数の仕様として、微妙そうな動作を修正します。

##  カテゴリ
- 不具合修正

##  PR の背景
`IsFileExists()`と`IsDirectory()`では、そのファイル/ディレクトリ確認に、`FindFirstFile`を使用しています。
しかしこのWin32APIは、ワイルドカードを受け付けるので、入力文字列に含まれていると、その文字列そのもののファイル/フォルダが存在していないのに、たまたまマッチしたファイルがあれば`true`を返すことがあります。

##  PR のメリット
微妙そうな動作が改善されます。

##  PR のデメリット (トレードオフとかあれば)
利用箇所の上位のコードで動作が変わるため、新しい問題が発生する可能性もあります。

##  仕様・動作説明

ファイル名/フォルダ名にワイルドカードがある場合には`false`を返すように変更します。

すでに同種の関数`IsInvalidFilenameChars()`があります。しかしファイル名部分らしい部分のみしか確認してくれません。
`WCODE::IsValidFilenameChar`のみでは、`\\?\C:\Wimdows\`の形式を通過させることができません。
当面の処置として、関数を新設しました。

##  PR の影響範囲

コードの利用箇所を軽く見て回った範囲では、実害はほぼないようです。

##  テスト内容

単体テストが書けそうですが、今のところありません。

##  関連 issue, PR

##  参考資料

2021-03-27 02:13 UTC, berryzplus commented
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1608&resolved=false&types=BUG) [<img alt="D" width="16" height="16" src="https://camo.githubusercontent.com/95c7073812843649a7be8230a7d83e54e7706e01688c21754aa4c204e3f671b9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f442e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1608&resolved=false&types=BUG) [1 Bug](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1608&resolved=false&types=BUG)

修正範囲外コードであるため、レビュー対象外としてよい認識です。

2021-03-27 02:25 UTC, berryzplus requested changes
PR趣旨は了解です。

コード眺めて気になった箇所にコメントしました。

強いていうと、扱う対象「ファイルパス」を表す型は `const wchar_t*` や `std::wstring_view` などの「文字列」ではなくて `std::filesystem::path` なんじゃないかな？と思いました。パスに変えると色々めんどくさそうなので、とりあえず文字列想定で進めてよいと思いますが。

2021-03-27 02:25 UTC, berryzplus commented on sakura_core/util/file.cpp
> +	int pos = 0;
新規コードにはx64考慮を入れたいです。
変数の使い方から、size_tで宣言するのが適当かと思います。

2021-03-27 02:25 UTC, berryzplus commented on sakura_core/util/file.cpp
> +		pos = 4;
ここは人によると思いますが、リテラルの意味を明確にしたいです。

4 = _countof(LR"(\\?\)") - 1

だと思うんですけど合ってますでしょうか？

2021-03-27 02:25 UTC, berryzplus commented on sakura_core/util/file.cpp
> +bool IsValidPathAvailableChar(const wchar_t* path)
引数型に疑問があります。
nullptr を渡せる仕様としたいならこのままでよいです。
nullptr が渡されることを考慮しないなら std::wstring_view とすべきな気がします。

2021-03-27 02:25 UTC, berryzplus commented on sakura_core/util/file.cpp
> +	for (int i = pos; path[i] != L'\0'; ++i) {
終了条件がバッファオーバーランを考慮してない気がします。

2021-03-27 08:06 UTC, usagisita commented on sakura_core/util/file.cpp
> +bool IsValidPathAvailableChar(const wchar_t* path)
std::wstring_viewのデフォルトコンストラクタは、data()でnullptrを返します。
nullptrが渡されないことを明示したいなら、その変更は無意味です。

2021-03-27 12:41 UTC, berryzplus commented on sakura_core/util/file.cpp
> +bool IsValidPathAvailableChar(const wchar_t* path)
変更提案の意図は、引数が無効でないこと(=nullptrでないこと)を呼出し側に強要することにあります。
std::wstring_view を使う場合に、length() をチェックせずに data() を参照するコードはそれはそれで問題だと思います。

```c++
void func1(const wchar_t* sz);
void func2(std::wstring_view str);

void test(){
    wchar_t* ptr = nullptr;
    func1(ptr); //呼出側では落ちない。nullチェック忘れは呼ばれた側の責任。
    func2(ptr); //呼出側でAccessViolationして落ちる。nullチェック忘れは呼出側の責任。
}
```

2021-03-27 16:37 UTC, usagisita commented on sakura_core/util/file.cpp
> +		pos = 4;
合ってます。が直値はよくないですね、直しました。

2021-03-27 16:41 UTC, usagisita commented
wstring_viewに変更しました。
指摘された点は直しました。
emptyをtrueとするかfalseとするかは、賛否ありそうですが、とりあえずtrueにしてあります。
wcsncmp_literalの「==0」がなかったため、if文の条件が反転していたので、直しました。
コードは短いですが動作が怪しかったので、ちょっと反省して、単体テストをつけました。

2021-03-28 11:30 UTC, berryzplus approved these changes
コードの目視確認のみですが、問題なさそうに見えます。

2021-03-28 11:30 UTC, berryzplus commented on sakura_core/util/file.cpp
> +	constexpr size_t len = _countof(dos_device_path) - 1;
指摘じゃないっすけど・・・

dos_device_path の定義型は `const (wchar_t&)[5]` 型ですね、たぶん。

2021-03-28 11:30 UTC, berryzplus commented on tests/unittests/test-file.cpp
> +	EXPECT_FALSE(IsValidPathAvailableChar(L"\\\\?\\C:\\dir*\\test.txt"));
ここ、テストコードなので直す必要はないと思いますが、
テスト対象とか期待値に `LR"(...)"` を使ったほうが読みやすくなる気がします。

2021-03-28 11:33 UTC, berryzplus commented on tests/unittests/test-file.cpp
> +	EXPECT_FALSE(IsValidPathAvailableChar(L"\\\\?\\C:\\dir*\\test.txt"));
そして、先頭 `\\?\` で始まるシリーズで、途中に `*` とか `?` とか含むパターンをやる必要があるかは、少し謎です。
（だって、先頭 `\\?\` を検出した時点で、式全体の false が確定するから。後続部分変えても意味なくね？という）

テストコードなので修正の必然はないように思います。

2021-03-28 13:20 UTC, sanomari approved these changes

2021-03-28 14:21 UTC, usagisita commented
レビューありがとうございます。
マージします。

2021-03-28 14:22 UTC, merged