フォルダ選択ダイアログを SHBrowseForFolder() でなく IFileDialog を使用するように変更
sakura-editor/sakura pull request #1609
Opened 2021-03-27 10:38 UTC by Ocelot1210

#  PR の目的
フォルダ選択ダイアログの操作性を向上させる事が目的です

##  カテゴリ

- 仕様変更

##  PR の背景
- `SHBrowseForFolder` はツリー形式の UI のため操作性に難があります(特に深い階層のフォルダを選択する場合)  
- Windows Vista 以降では `SHBrowseForFolder` ではなく、 `FOS_PICKFOLDERS` オプションを指定した `IFileDialog` を使用する事が推奨されています(詳細は参考資料 No.1 をご参照下さい)

##  PR のメリット
フォルダ選択ダイアログの操作性が向上します

##  PR のデメリット (トレードオフとかあれば)
Vista 以前の OS (2000/XP) でフォルダ選択ダイアログが動作しなくなります

##  仕様・動作説明
### 変更前
[`SHBrowseForFolder`](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfolderw) を使用してフォルダ選択ダイアログを表示します

### 変更後
[`IFileDialog`](https://docs.microsoft.com/ja-jp/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialog) に [`FOS_PICKFOLDERS`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) オプションを指定し、フォルダ選択ダイアログを表示します

##  PR の影響範囲
フォルダ選択ダイアログを表示する以下の項目に影響があります

1. メニュー→設定→共通設定→バックアップ→フォルダ名
2. メニュー→設定→共通設定→プラグイン→設定→値
    - 確認用に使用したプラグインは参考資料 No.2 をご参照下さい
3. メニュー→設定→共通設定→マクロ→マクロ一覧
4. メニュー→設定→共通設定→支援→migemo設定→辞書
5. メニュー→設定→共通設定→編集→ファイルダイアログの初期位置→指定フォルダ
6. メニュー→ツール→外部コマンド実行→カレントディレクトリ
7. メニュー→検索→ファイルツリー→設定→パス
8. メニュー→検索→Grep→検索場所
9. メニュー→検索→タグファイルの作成→タグ作成フォルダ
10. マクロ専用関数 [FolderDialog()](https://sakura-editor.github.io/help/HLP000268.html#FolderDialog) が呼ばれた際

##  テスト内容

### テスト1
手順
1. PR の影響範囲の 1～9 にあるフォルダ選択ダイアログが表示されるボタンを押す
2. フォルダ選択ダイアログのタイトルが変更前後で差異が無い事を確認する
3. フォルダ選択ダイアログにて「キャンセル」ボタンを押した際の動作が変更前後で差異が無い事を確認する
4. フォルダ選択ダイアログにて「フォルダーの選択」ボタンを押した際の動作が変更前後で差異が無い事を確認する

### テスト2
手順
1. 以下の内容のファイル(拡張子は.js)を作成し、メニュー→ツール→名前を指定してマクロ実行で開く
```js
result = Editor.FolderDialog("フォルダを選択してください", "C:\\Windows")
Editor.MessageBox(result, 0x40)
```
2. フォルダ選択ダイアログのタイトルが変更前後で差異が無い事を確認する
3. フォルダ選択ダイアログにて「キャンセル」ボタンを押した際の動作が変更前後で差異が無い事を確認する
4. フォルダ選択ダイアログにて「フォルダーの選択」ボタンを押した際の動作が変更前後で差異が無い事を確認する

##  関連 issue, PR
直接的な issue, PR はありませんが、 @beru さんが [#1431 にて言及されております](https://github.com/sakura-editor/sakura/pull/1431#issuecomment-716862179)

##  参考資料
1. [SHBrowseForFolderW function (shlobj_core.h)](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfolderw#remarks)
2. [テスト用プラグイン.zip](https://github.com/sakura-editor/sakura/files/6215408/default.zip)

2021-03-27 12:22 UTC, berryzplus commented
@Ocelot1210 さん　はじめましてでしょうか。PR趣旨は了解です。

> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT) [<img alt="E" width="16" height="16" src="https://camo.githubusercontent.com/d1da85f351e00bba6c56d3810244c6e8db2ac21477a0ebfb29caf57027619c72/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452e706e67">](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT)

いまのところ、レビューして「問題ありません」で解決した実績はないです。
`wcscpy_s` を使うように修正するだけで良いので対応をお願いしたいです。

> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=CODE_SMELL)

- C++ではポインタに `NULL(=数値0のこと)` を使うべきでないそうです。
- ネストしたコードブロックには、通常「名前」を付けられます。
  関数化して処理の「名前」を明示したほうがメンテナンスしやすくなるそうです。
- 関数の戻り値が使用されないパスがあるようです。
  戻り値は処理の成否を表すことが多いので、取得したら何らかの判定を行うべきと思います。

SonarCloud指摘に対する対処は「絶対必要」というわけではないです。
- 対処することによって修正を誤る危険がある。
- 対処するのがすっごくめんどい。
- 明らかに Fault Positive （＝擬陽性、解析ツールのバグじゃね？）。

「対応しない理由」が（普通に考えて）納得できるようなら「スルー」で良いと思っています。

2021-03-27 14:27 UTC, Ocelot1210 commented
@berryzplus さん、はじめまして
PR の内容のご確認及びアドバイスを頂きありがとうございます
普段 C++ を触らないので勉強になりました
GitHub / SonarCloud をあまり理解していないためお手数をおかけして申し訳ございません
ご指摘頂いた内容を対応いたしました
<br>


> wcscpy_s を使うように修正するだけで良いので対応をお願いしたいです。

本件、格納先の要素数を渡すため `SelectDir` 関数の引数が増えましたがご容赦ください

2021-03-28 11:40 UTC, berryzplus commented
appveyorのビルド失敗が意味不明なのでリビルドかけときました。

2021-03-31 12:07 UTC, berryzplus submitted a review, later dismissed
判断できずに放置してしまっていました。
対応したい変更はできてそうなので結論を出しておきます。

「分かんなかったらapprove」で良いこともあると思うんですよね。
人間、一人で全領域のスペシャリストにはなれないのだから。
それで問題を起こさないようにするためのCIで、SonarCloudだと思っています。

一応、今回は動かしたっす :smiley:

2021-04-02 10:47 UTC, Ocelot1210 commented
@beru さん、PR のご確認ありがとうございます
ご指摘頂いた点を対応いたしました

2021-04-02 15:15 UTC, beru commented on sakura_core/outline/CDlgFileTree.cpp
> +				if( SelectDir(hwndDlg, LS(STR_DLGGREP1), szDir, szDir ) ){
細かい指摘ですみませんがこのファイルの差分は消せると思います。

2021-04-03 06:43 UTC, Ocelot1210 commented on sakura_core/outline/CDlgFileTree.cpp
> +				if( SelectDir(hwndDlg, LS(STR_DLGGREP1), szDir, szDir ) ){
対応いたしました
ご指摘頂きありがとうございます

2021-04-03 08:53 UTC, beru commented on sakura_core/outline/CDlgFileTree.cpp
> +				if( SelectDir(hwndDlg, LS(STR_DLGGREP1), szDir, szDir ) ){
対応ありがとうございました。

2021-04-04 07:41 UTC, berryzplus submitted a review, later dismissed
細かいところは後まわしでもいいような気がするんですよね・・・。

2021-04-04 07:41 UTC, berryzplus commented on sakura_core/util/shell.h
> +BOOL SelectDir(HWND hWnd, const WCHAR* pszTitle, const WCHAR* pszInitFolder, WCHAR(&strFolderName)[nMaxCount])
ここ、SonarCloudの警告がでました。
対応は必須でないと思いますが、あるべき姿で考えると「戻り値BOOL」がマズいのかもです。

```c++
std::wstring SelectDir(
  HWND hWnd,
  std::wstring_view title,
  std::wstring_view initFolder);
```

2021-04-04 07:41 UTC, berryzplus commented on sakura_core/dlg/CDlgExec.cpp
> +			if( SelectDir( GetHwnd(), LS(STR_DLGEXEC_SELECT_CURDIR), &m_szCurDir[0], &m_szCurDir[0], m_szCurDir.GetBufferCount() ) ){
戻り値BOOLをやめた場合、ここはこんな感じになります。

```c++
if( auto selectedDir = SelectDir( GetHwnd(), LS(STR_DLGEXEC_SELECT_CURDIR), &m_szCurDir[0] ); selectedDir.length() > 0 ){
  m_szCurDir = selectedDir.c_str();
```

m_szCurDir の宣言型がおかしいのが原因で、ロジックが書きづらくなっています。
対応はしなくてもいいんじゃないかなぁ、と思います。

2021-04-04 07:41 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +static void SetInitialDir( Microsoft::WRL::ComPtr<IFileDialog> pDialog, const WCHAR* pszInitFolder )
別に正しく書く必要はありませんが、使い方が間違っています。

```suggestion
static void SetInitialDir( IFileDialog* pDialog, const WCHAR* pszInitFolder )
```

あとは好みですが、第二引数は std::wstring_view がいいっす。

2021-04-04 07:41 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +	CutLastYenFromDirectoryPath( szInitFolder );
:smiley:

2021-04-04 07:57 UTC, berryzplus commented
あるべき姿で考えるとSelectDirのシグニチャはこうなんですよね。

```c++
std::filesystem::path SelectDir(
  HWND hWnd,
  std::wstring_view title,
  const std::filesystem::path& initFolder);
```

このグローバル関数が扱う対象は何でしょう？
- パス文字列 = std::filesystem::path
- 文字列参照 = std::wstring_view
- 出力文字列 = std::wstring& 
- 共有メモリ内の文字列 = SFilePath = StaticString<wchar_t, 260>

2021-04-04 13:16 UTC, Ocelot1210 commented on sakura_core/util/shell.cpp
> +static void SetInitialDir( Microsoft::WRL::ComPtr<IFileDialog> pDialog, const WCHAR* pszInitFolder )
対応いたしました
ご指摘頂きありがとうございます

2021-04-06 14:38 UTC, beru commented on sakura_core/util/shell.cpp
> +	wcscpy_s( szInitFolder, _countof(szInitFolder), pszInitFolder.data() );
「メニュー→設定→共通設定→プラグイン→設定→値」で確認しました。
とても長いパスをエディット部分に貼り付けてから ... を押すとここで実行時エラーが起きます。

```
C:\test\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbb
```

2021-04-07 13:15 UTC, Ocelot1210 commented on sakura_core/util/shell.cpp
> +	wcscpy_s( szInitFolder, _countof(szInitFolder), pszInitFolder.data() );
ご指摘ありがとうございます
本件、初期フォルダとして指定されたパスを `SHCreateItemFromParsingName` に直接渡すようにする事で対応いたしました

追加で以下のパターンで初期フォルダが開く事を確認いたしました (末尾の `'\\'` 有無も含めて確認)
- ルートディレクトリ
- ルートディレクトリ以外
- とても長いパス (フォルダ選択可能な事も確認)

2021-04-07 15:18 UTC, beru commented on sakura_core/util/shell.cpp
> +	wcscpy_s( szInitFolder, _countof(szInitFolder), pszInitFolder.data() );
この問題が解消されたことを確認しました。修正ありがとうございました。

2021-04-07 15:28 UTC, beru commented on sakura_core/util/shell.cpp
> +	wcscpy_s( strFolderName, nMaxCount, pszResult );
`wcscpy_s` は格納先のバッファサイズが足りない時にエラーハンドラが起動され実行時エラーになります。

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s?view=msvc-160#remarks

> If dest or src is a null pointer, or if the destination string size dest_size is too small, the invalid parameter handler is invoked, as described in Parameter Validation.

サクラエディタの実装ではCRT の `_set_invalid_parameter_handler` を呼び出してカスタム処理をさせているわけではないのでCRTデフォルト実装のワトソン行きコースになりアプリが終了します。

`pszResult` には以下のパスが入る条件で動作確認しました。

```
\\?\D:\123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890\aaa\aaaaaaaaaaaaaaaaaa
```

`MAX_PATH` を超える長いフォルダパスはExplorerだけでは作れませんが、アドレスバーに `cmd` と入力して Enter キーを押して `cmd.exe` を起動し、そこで `mkdir` コマンドでフォルダを作成したり、作成したフォルダを `rename` コマンドで長いフォルダ名に変えることが出来ます。

2021-04-07 15:39 UTC, beru commented on sakura_core/util/shell.cpp
> +	wcscpy_s( strFolderName, nMaxCount, pszResult );
過去のPRで同様に `wcscpy_s` の問題がコメントで指摘されてその結果代わりに使われているのが `wcsncpy_s` です。
最後の `count` 引数に `_TRUNCATE` を指定する事で自動的に切り詰めてくれます。

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncpy-s-strncpy-s-l-wcsncpy-s-wcsncpy-s-l-mbsncpy-s-mbsncpy-s-l?view=msvc-160

ただしフォルダ選択ダイアログのケースでは切り詰めた不完全なパスを返しても、呼び出し元にとって利益になるかというとそうではないかもしれません。なので出力先のバッファ長を超過するケースでは `CoTaskMemFree( pszResult );` して `return FALSE;` するのが良い気がします。

`SelectDir` の出力先が固定長配列ではなくて動的確保する文字列型であればこういう問題は回避出来ますが、元実装がそもそもそういう作りではないのでこのPRで `SelectDir` と呼び出し元を魔改造する必要性は無いと思います。

2021-04-08 12:08 UTC, Ocelot1210 commented on sakura_core/util/shell.cpp
> +	wcscpy_s( strFolderName, nMaxCount, pszResult );
ご指摘及びアドバイスありがとうございます
本件、ご提示頂いた方法で実行時エラーが発生しないよう対策いたしました

長いフォルダパスは 7zip のファイラーを使用して作成していましたが、`cmd.exe` でも作成出来るのは初めて知りました
ありがとうございます
<br>

> このPRで `SelectDir` と呼び出し元を魔改造する必要性は無いと思います。

了解です
ひとまずこの状態とさせていただきます

2021-04-09 04:42 UTC, berryzplus requested changes

2021-04-09 04:42 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +	if ( nMaxCount < wcslen(pszResult) ) {
この行でSecurity Hotspotが検出されとります。
> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT) [<img alt="E" width="16" height="16" src="https://camo.githubusercontent.com/d1da85f351e00bba6c56d3810244c6e8db2ac21477a0ebfb29caf57027619c72/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452e706e67">](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1609&resolved=false&types=SECURITY_HOTSPOT)


```suggestion
	if ( pszResult != nullptr && nMaxCount < wcsnlen( pszResult, nMaxCount ) ) {
```
になるのかなぁ・・・。

2021-04-09 04:42 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +	PWSTR pszResult;
作法的なモノですが、こうしておくと一部の不安を除去できます。

```suggestion
	PWSTR pszResult = nullptr;
```

2021-04-09 04:42 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +		CoTaskMemFree( pszResult );
この関数の呼び出しは、GetDisplayNameが成功した場合に必須だと思います。
（返された出力値がnullptrであっても呼ぶ・・・）
https://docs.microsoft.com/ja-jp/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitem-getdisplayname#remarks

2021-04-09 11:25 UTC, beru commented on sakura_core/util/shell.cpp
> +	wcscpy_s( strFolderName, nMaxCount, pszResult );
対策が追加されて落ちなくなった事を確認しました。
フォルダ選択に失敗した事がユーザーにとって分かりにくいですがそれは元からそういう作りなのでしょうがないと思います。

2021-04-09 11:29 UTC, beru commented on sakura_core/util/shell.cpp
> +		CoTaskMemFree( pszResult );
`CoTaskMemFree` の呼び出しはちゃんと行われているように見えます。

こういうのはスマートポインタを使ってメモリ解放の呼び出しを明示的に書く必要がないようにできたらいいですね。

https://devblogs.microsoft.com/oldnewthing/20160620-00/?p=93705

のコードでは ATL の `CComHeapPtr` クラスが使われていますが、Windows Runtime C++ Template Library (WRL) のヘッダファイルにはそれと同等品が残念ながらなさそうです（ちゃんと調べていませんが）。

2021-04-09 11:33 UTC, beru commented on sakura_core/util/shell.cpp
> +	if ( nMaxCount < wcslen(pszResult) ) {
`IShellItem::GetDisplayName` が成功時に `pszResult` の値が nullptr になる事があるのかどうかは疑問ですが、仮にそうなる事があるとしてその場合に `wcsnlen` を呼ばないようにしたいという事でしょうか？

ただこの記述だと仮に `pszResult` が nullptr の時に `wcsnlen` は呼ばれないですが、`wcscpy_s` は呼ばれますよね。

それならばそもそも `pszResult` が nullptr の場合は `return FALSE;` した方が良いと思いますね。まぁ無いと思いますが…。

2021-04-09 11:42 UTC, beru commented on sakura_core/util/shell.cpp
> +	if ( nMaxCount < wcslen(pszResult) ) {
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strnlen-strnlen-s?view=msvc-160

の説明に下記のように書かれていました。

> strnlen, wcsnlen, and _mbsnlen do not validate their parameters. If str is NULL, an access violation occurs.

> strnlen_s and wcsnlen_s validate their parameters. If str is NULL, the functions return 0.

実際に `pszResult` が NULL 値になるとは思いませんが使うなら `wcsnlen` より `wcsnlen_s` が良いと思います。

あと `wcsnlen` はC標準規格には無いのか下記のページには載っていませんでした。

https://en.cppreference.com/w/c/string/wide/wcslen

元の `wcslen` 関数を呼び出す記述だと SonarCloud が Security Hotspot を検出してきますが、実際には問題は無いと思うんですよね。`GetDisplayName` 成功時に取得した文字列は有効領域と見なせると思います。

なお `wcslen` の代わりに `wcsnlen_s` を使う事による利点としては、SonarCloud が Security Hotspot を検出しなくなるのと、あと文字列長が出力先バッファ長を超える場合にそこでループが中断させる事が出来るので無駄が少ないですね。

というか `IShellItem` が `DisplayName` のバッファ長を返すメソッドを用意してくれていたら良かったんですが探しても見つかりませんでした。

2021-04-09 13:11 UTC, berryzplus commented
util/shell.cpp 104行目からの修正案です。

```c++
	BOOL bRet = TRUE;
	if ( STRUNCATE == wcsncpy_s( strFolderName, nMaxCount, pszResult, _TRUNCATE ) ) {
		wcscpy_s( strFolderName, nMaxCount, L"" );
		bRet = FALSE;
	}

	CoTaskMemFree( pszResult );

	return bRet;
```

これなら pszResult の長さを取得する必要も、初期値を設定する必要もないです。

2021-04-09 13:12 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +		CoTaskMemFree( pszResult );
解放はちゃんとできていましたね。取り下げておきます。

2021-04-09 13:13 UTC, berryzplus commented on sakura_core/util/shell.cpp
> +	PWSTR pszResult;
初期化漏れでも問題はないと気付いたので取り下げておきます。

2021-04-09 13:30 UTC, beru commented
> util/shell.cpp 104行目からの修正案です。
> 
> ```c++
> 	BOOL bRet = TRUE;
> 	if ( STRUNCATE == wcsncpy_s( strFolderName, nMaxCount, pszResult, _TRUNCATE ) ) {
> 		wcscpy_s( strFolderName, nMaxCount, L"" );
> 		bRet = FALSE;
> 	}
> 
> 	CoTaskMemFree( pszResult );
> 
> 	return bRet;
> ```
> 
> これなら pszResult の長さを取得する必要も、初期値を設定する必要もないです。

`wcsncpy_s` を使う方法は https://github.com/sakura-editor/sakura/pull/1609#discussion_r608770837 でもコメントしましたが戻り値を確認して FALSE を返す事を思いつきませんでした。その方法は良いですね。

なお戻り値の判定は `STRUNCATE` ではなくて 0 以外かどうかの方が良い気がします。

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncpy-s-strncpy-s-l-wcsncpy-s-wcsncpy-s-l-mbsncpy-s-mbsncpy-s-l?view=msvc-160#return-value

> Zero if successful, STRUNCATE if truncation occurred, otherwise an error code.

2021-04-09 15:56 UTC, beru approved these changes
問題無いと思います。

PRの説明の影響範囲に列挙されていた箇所で、フォルダ選択ダイアログにVista以降のCommon Item Dialogが使われるようになった事の動作確認をしました。

----

SonarCloud が `wcslen` の呼び出しを Security Hotspot として検出していますが、実際に今のコードでどういうケースでどういう問題が起きるのか（起こせるのか）は分かりません。

自分が分かっている範囲では `SelectDir` 関数の引数に NULL を渡したら問題が起きると思いますが、そのように呼び出している箇所は無いと思います。

という事で、それについては対応してもしなくてもどちらでも良いとの判断で Approve します。

2021-04-10 05:00 UTC, berryzplus submitted a review, later dismissed
Security Hotspotが検出されないように修正を試みてほしいです。

2021-04-10 06:06 UTC, Ocelot1210 commented
ご指摘ありがとうございます
`wcslen` が Security Hotspot として検出されるとは思わず、お手数をおかけして申し訳ございません...

以下対応いたしました
- ご提示頂いた方法で Security Hotspot が検出されないように修正を試みた
- `SelectDir` 関数冒頭で出力先バッファの nullptr チェックを追加

2021-04-10 09:36 UTC, berryzplus approved these changes
対応ありがとうございます。

2021-04-10 11:27 UTC, beru approved these changes
動作確認して特に問題は見つかりませんでした。

2021-04-10 11:27 UTC, merged