メモリバッファクラスをx64対応できるように書き替える
sakura-editor/sakura pull request #1618
Opened 2021-04-08 15:09 UTC by berryzplus

#  PR の目的

CMemoryをリファクタリングして、x64対応作業を始められるようにすることが目的です。

##  カテゴリ

- その他

##  PR の背景

CMemoryやCNativeWはサクラエディタの中核に位置するクラスです。

SonarCloudによる静的解析で、以下のBugsレベル警告が検出されています。

- Bugs(Blocker)レベル
  - sakura_core/mem/CMemory.cpp
    > Out of bound memory access (accessed memory precedes memory block)
    > https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXiZfAqkWWGx2hJc4xkw&open=AXiZfAqkWWGx2hJc4xkw
- Bugs(Critical)レベル
  - sakura_core/mem/CNativeA.h
    > Explicitly define or delete the missing destructor so that it will not be implicitly provided.
    > https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AWnxcx-MO9B58BDk-CXO&open=AWnxcx-MO9B58BDk-CXO
  - sakura_core/mem/CNativeW.h
    > Explicitly define or delete the missing destructor so that it will not be implicitly provided.
    > https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AWnxcx-EO9B58BDk-CXM&open=AWnxcx-EO9B58BDk-CXM

これらのクラスは、依存関係のルート付近にあるヘッダーで定義されているため、修正がしづらいです。
最近マージされた #1615 により、修正のやりづらさはさらに増したと思います。

ただ、ここを修正しないと x64対応 は不可能なので、どこかでなんとかしたいと考えていました。

今回は、思い切ってCMemory/CNativeWの大幅改修をして、x64対応の作業ができる状態を作り出したいと思います。

##  PR のメリット

- 上記3件のBugsレベル警告を解消できます。
- 現在発生している2万件のCodeSmellsのうち21件を解消できます。
- CMemoryの単体テスト網羅率が100%になります。
-  INT_MAX(＝約2GB) を超えるメモリの確保を試みた場合に確実に「失敗」するようになります。
  ※従来は異常を検出できず、処理が続行されていました。
- `x64 - Debug`ビルドの警告が 576件 から 495件 に減ります。

##  PR のデメリット (トレードオフとかあれば)

- CMemoryのpublicメソッドをいくつかリネームしているため、修正量が多くなっています。
- CodeSmellsが新たに21件増えます（今回は対処しません。）

##  仕様・動作説明

CMemoryで定義されているメソッドの改廃を行っています。
|クラス名|メソッド名|対応|代替|説明|対応理由|
|--|--|--|--|--|--|
|CMemory|Clean|削除|Reset|バッファをリセット(解放)する|同機能の別名メソッドがあり、存在自体が冗長であるため。|
|CMemory|Clear|削除|Reset|バッファをリセット(解放)する|CNativeの同名メソッドと混同する危険があるため。|
|CMemory|_Empty|削除|Reset|バッファをリセット(解放)する|メモリバッファのリセット(解放)はクラス外部から普通に利用する機能であり、非公開にしておく意味がないため。|
|CMemory|Reset|新規| - |バッファをリセット(解放)する|リセット(解放)を意味するメソッド名が存在していなかったため。|
|CMemory|_AddData|削除|AppendRawData|データを追加する|メモリ確保とコピーを統合することにより、メモリ確保失敗時にコピーが強行される事態を防ぐ必要があった。|
|CMemory|SwabHLByte|削除|SwapHLByte|Byteを交換する|`Windows SDK`の[_swab](https://docs.microsoft.com/ja-jp/previous-versions/visualstudio/visual-studio-2013/e8cxb8tk(v=vs.120))を利用するためには、好ましくないキャストをする必要がある。加えて、_swabを利用するメリットはとくにないため。|

##  PR の影響範囲

- CMemoryを利用する機能（エディタ機能全般）に影響する修正です。

##  テスト内容

影響範囲が広すぎるので、単純な起動確認をしたほうが良さそうです。

1. サクラエディタを起動する。
2. 任意のテキストファイルを開く。

##  関連 issue, PR

#1504
#1541
#1575 
#1605

##  参考資料

2021-04-09 03:12 UTC, sanomari requested changes

2021-04-09 03:12 UTC, sanomari commented on sakura_core/mem/CNativeW.cpp
> +	, m_nDataLen(cmem.GetStringLength())
41行目と同様にキャスト付けたほうがいいと思います。

2021-04-09 03:12 UTC, sanomari commented on sakura_core/mem/CNativeW.cpp
> +	CMemory::SetRawData( pData,nDataLen * sizeof(wchar_t) );
存在しない関数 CNative::SetRawData を書くよりはマシ、の意図と把握しました。
CMemory::SetRawDataはstaticでもvirtualでもないので、紛らわしい気がします。
単に SetRawData としておけば誤解なく読めると思います。

2021-04-09 03:12 UTC, sanomari commented on sakura_core/mem/CNativeW.cpp
> +	if( format.empty() || format.data() == nullptr ){
```suggestion
	if( format.empty() ){
```

2021-04-09 03:12 UTC, sanomari commented on sakura_core/mem/CNativeW.cpp
> + * @throws std::invalid_argument formatがNULL
```suggestion
 * @throws std::invalid_argument formatが無効値
```

2021-04-09 03:12 UTC, sanomari commented on sakura_core/mem/CNativeW.cpp
> +	if( static_cast<int>(nIndex) < GetStringLength() ){
同様です。他も横展開要ると思います。

2021-04-09 03:29 UTC, berryzplus commented on sakura_core/mem/CNativeA.cpp
> +	if( static_cast<int>(nIndex) < GetStringLength() ){
やばいですね。対応します。

2021-04-09 03:32 UTC, berryzplus commented on sakura_core/mem/CNativeW.cpp
> +	CMemory::SetRawData( pData,nDataLen * sizeof(wchar_t) );
> 存在しない関数 CNative::SetRawData を書くよりはマシ、の意図と把握しました。

この意図で合っています。

付けるかどうか迷いましたが、削るほうで修正しておきます。

2021-04-09 07:46 UTC, berryzplus commented
こんなの出てたので追加修正しました。

> Rename this member function so that it doesn't hide an inherited non-virtual function, or make it virtual in the base class "CMemory".
> https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXi037PsqNOaEhErIvC_&open=AXi037PsqNOaEhErIvC_&pullRequest=1618

2021-04-09 10:00 UTC, berryzplus commented
https://github.com/sakura-editor/sakura/pull/1618#issuecomment-816488218 を対応しようとしたらこんなの出たので諦めます。
> 'CMemory' has virtual functions but non-virtual destructor
> https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AXi1t3KSmnSiw_EpU5Ks&open=AXi1t3KSmnSiw_EpU5Ks&pullRequest=1618

2021-04-09 12:57 UTC, sanomari approved these changes

2021-04-10 12:37 UTC, k-kagari commented on sakura_core/mem/CNativeW.h
> +	unsigned		m_nDataLen = 0;
`unsigned` は `unsigned int` と同義ですが、意図するところでしょうか？ PRの趣旨に合わないように思えます。

2021-04-10 13:00 UTC, k-kagari commented on sakura_core/mem/CNativeW.h
> +	unsigned		m_nDataLen = 0;
あ、「x64対応**できるように**書き替える」ですね。今のところ32bit幅に限定する仕様であると理解しました。

2021-04-10 13:31 UTC, k-kagari approved these changes

2021-04-10 13:31 UTC, k-kagari commented on sakura_core/mem/CMemory.cpp
> +		::memcpy( pData, cmem.GetRawPtr(), nDataLen );
元のコードが過去にパフォーマンス問題に対策した結果のものに見えるので、115行目のコンストラクタと memcpy での2回のコピーがパフォーマンスに与える影響が気になりました。ビット演算するのが書いた人の趣味だった可能性もありますけれど…。

2021-04-10 14:42 UTC, berryzplus commented on sakura_core/mem/CMemory.cpp
> +		::memcpy( pData, cmem.GetRawPtr(), nDataLen );
[bswapはCPU命令](https://c9x.me/x86/html/file_module_x86_id_21.html)なので、パフォーマンスを重視するならこちらを使うべきです。

もともとはstaticバージョンに本体があり、インスタンスメソッド側が参照する構造になっていたのを逆転しています。staticバージョンを使わない方向に持っていき、最終的には廃止したいと考えているので、あえて不都合が起きる実装にしています。いきなり動かなくすると困りそうなのでいったん残してある状態です。

2021-04-10 15:16 UTC, k-kagari commented on sakura_core/mem/CMemory.cpp
> +		::memcpy( pData, cmem.GetRawPtr(), nDataLen );
過渡的な実装ということで承知しました。

2021-04-11 03:16 UTC, usagisita commented on sakura_core/mem/CMemory.cpp
> +		return;
不具合ではないのですが、`<`よりも`<=`のほうがほんの少しだけ幸せになるかもしれないと思いました。

2021-04-11 03:26 UTC, usagisita commented on sakura_core/mem/CMemory.h
> +	[[nodiscard]] int capacity() const noexcept { return 8 <= m_nDataBufSize ? m_nDataBufSize - 2: 0; }
この8というマジックナンバーが曲者ですね。
2を引くのはm_nDataBufSizeがNUL終端を含んでいるからというのが根拠ですが、
8のほうはAllocBufferの実装に強く依存している可能性があるというか。
マイナス値を避けたいので変更したんだと思いますが、
2以上であれば、8でなくてもよいというなら、2のほうがいいかもしれないとは思います。
(これは修正要求ではないので、変更しなくてもかまいません）

2021-04-11 04:48 UTC, berryzplus commented on sakura_core/mem/CMemory.cpp
> +		return;
ここを less than にした理由は capacity() の実装に起因しています。
おっしゃる通りだと思うのでどこかで対応したいです。（今回は見送りたいです）

2021-04-11 04:58 UTC, berryzplus commented on sakura_core/mem/CMemory.h
> +	[[nodiscard]] int capacity() const noexcept { return 8 <= m_nDataBufSize ? m_nDataBufSize - 2: 0; }
マジックナンバー「8」についてはクラスコメントに記載しました。
「内部バッファのサイズは8の倍数に切り上げて確保される。」
8を定数化するのがあるべき姿かもしれません。
（冷静に考えると、0より1つ大きい値が8なので「0 < m_nDataBufSize」にしとけばいいのかも。）

現在のcapacity()実装は標準ライブラリstd::wstring::capacity()と異なるので、メソッドをリネームするか、実装を標準ライブラリに寄せるかして取り違え防止を図るのがよいと思います。

2 = sizeof(wchar_t) だから実質的に「1つ違いエラー」の見直しになるので今回PR対象からは外しました。

2021-04-11 05:05 UTC, berryzplus commented
レビューありがとうございます。とりあえずマージしちゃいます。

このPRは目的が「準備」であることもあり、至らぬ点が多数ある認識っす。

何か気付いた点があれば、このPRのコメントでも良いですし、新規issueでも良いので課題をあげてもらえれば幸いです。

2021-04-11 05:05 UTC, merged

2021-04-11 05:25 UTC, berryzplus commented on sakura_core/mem/CMemory.cpp
> +		::memcpy( pData, cmem.GetRawPtr(), nDataLen );
ちなみにstaticバージョンでメモリコピーを行っている理由は、以下です。

- bswapの対象は`uint16_t(=unsigned short)`です。
  - `uint16_t*`の値は、必ず偶数アドレスになります。 
- static関数の引数は`char*`です。
  - `char*`の値は、奇数アドレスになりえます。

　👇

- bswapを使うには、`char*`を`uint16_t*`に reinterpret キャストする必要があるので、問題をふせぐために新たに確保したメモリにコピーしてから処理する必要があります。

細かいことをいうと、mallocが返すアドレス値がどんな値であるか（≒偶数or奇数、アラインメント単位は？）について言語仕様的な規定はないはずです。返却されるメモリアドレスになんらかの要求仕様があるときには [_aligned_malloc](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/aligned-malloc) を使って仕様を明示します。一応、mallocで奇数アドレスが返ってきたのを見たことありませんし、現状の通常mallocで問題はないと思っていますが。