PatchUnicode-1051 現在のドキュメント内容をGrep
sakura-editor/sakura pull request #1639
Opened 2021-04-22 13:24 UTC by dep5

#  PR の目的
Mocaさん、novice123さん作の
[PatchUnicode-1051 現在のドキュメント内容をGrep](https://sourceforge.net/p/sakura-editor/patchunicode/1051/)　を適用します
<blockquote cite="https://sourceforge.net/p/sakura-editor/patchunicode/1051/">
「現在編集中ファイルから検索」を、
現在開いているファイル名の保存ファイルからGrepだったものを、
現在のドキュメントの内容(無題等を含む)から直接Grepできるように変更したものです。
　ウィンドウからGrepを使うと、対象が"Windows:[タイトル]"と表示されて、
Grepのタグが":HWND:[01234567]"のハンドルが表示されます。
Grepの自分自身を指定することもできます。
(ヘッダで出力された検索キーワードが引っかかってしまう制限付き)
</blockquote>

##  カテゴリ

- 機能追加
- 仕様変更

##  PR の背景
新規の文書・編集中の文書をGrepしたい場合、一時的にでもファイルとして保存する必要がありました。

##  PR のメリット
ファイルに保存していないテキストを、Grepできるようになります
検索結果のカウントなどもできます

##  PR のデメリット (トレードオフとかあれば)
Grepでファイルを編集中のGrepする対象が変わります。
GrepとGrep置換で挙動のずれが生じます

##  仕様・動作説明
Grep
新規のテキスト
（前）不可 （後）可
ファイルを編集中
（前）ファイルをGrep （後）テキストをGrep
ファイルに保存済み
（前）ファイルをGrep （後）ファイルをGrep？

Grep置換
機能しません

##  PR の影響範囲

##  テスト内容

### テスト1

手順

##  関連 issue, PR

##  参考資料

2021-04-22 16:49 UTC, beru commented
もかさんは過去に mocaskr というユーザー名の github のアカウントで活動していたようです。

https://github.com/mocaskr/sakura

でグーグル検索すると結構ヒットします。今はもう引退されてしまったようですね。

2021-04-22 23:22 UTC, sanomari requested changes
Secutiry HotSpotが出てるのはいけないんではないかと思いました。

> [<img alt="E" width="16" height="16" src="https://camo.githubusercontent.com/d1da85f351e00bba6c56d3810244c6e8db2ac21477a0ebfb29caf57027619c72/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452e706e67">](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1639&resolved=false&types=SECURITY_HOTSPOT) [4 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1639&resolved=false&types=SECURITY_HOTSPOT)

パッチで提供された機能の取り込みなので、CodeSmellsの対応はめんどうならしなくてもいいでしょう。Security Hotspotはご時世的に対応必須です。

追加したい機能についてですが、仕様的におかしいと思います。
「要望がおかしい」ではなく「仕様的におかしい」です。

やりたいこと：
　編集中の未保存データ内を検索してGrepみたいな結果表示をさせたい。

仕様的におかしい点：
　やりたいことは「検索」の延長だと思います。（違う機能を拡張してません？）
　Grepは検索対象ファイル群を横断的に（グローバルに）検索する仕様です。
　（Grepを世間一般の仕様と乖離させたいという「仕様変更」は許容できますか？）

既存でも仕様がおかしいところは既にたくさんあるので、
このままいれちゃってよいようにも思います。

2021-04-23 00:46 UTC, berryzplus commented
Security Hotspotsの対応が必須なのは同意見です。
CodeSmellsはめんどうなやつ（if文とか階層とかstd::stringとか)以外は直したいっす。

拡張するのはGrepじゃなくて検索にも同意ですが
流用したい結果表示機能を切り出すためにはCGrepAgentを触る必要があって、
結果表示のオプションを流用するためにはGrepダイアログを使うほうがいい気がしました。
（つまり、修正対象は大して変わらん気がします。）

よって、SonarCloud対策ができたら「とりあえず入れてみる」で良いと思います。

2021-04-23 07:56 UTC, kazasaku commented
コミットに表示されている人がmocaさんではなく、フランスの開発者のようです。
authorを訂正したほうがいいと思いました。

2021-04-23 10:01 UTC, berryzplus commented
> コミットに表示されている人がmocaさんではなく、フランスの開発者のようです。
> authorを訂正したほうがいいと思いました。

beruさんの書き込みと同じ指摘っぽいですね。

sourceforge時代の主力開発者 moca さんのアカウントは [moca_skr](https://sourceforge.net/u/moca_skr/profile/) なはずです。
既に削除されたアカウントを参照するのも若干アレなのですが、
フランス人（おそらく無関係の別人）が書いたことにしちゃうよりはマシかと思います。

代案は Moca<moca_skr ＠ users.sourceforge.jp> のように、
GitHubのシステムに誤認させないようにリアルな Author を設定することっす。

2021-04-23 13:44 UTC, dep5 commented
誤ったAuthorに関連付けされていたのを直しました。すいません。
アドバイスありがとうございます。

sanomariさん
複数のファイルを横断的に処理するのがGrepということですね。
現在当該チェックボックスでは一つのファイルだけをGrepしているので、
その延長で、ファイルにする前のテキストを対象にするのもありかなと思います。
しかし、欲しいものはファイル保存せずにGrepした結果の一覧やタグジャンプですので、
その機能があれば、場所や名称を変えてもよいと思います。

2021-04-23 13:55 UTC, dep5 commented
この変更でファイルを開いて編集中に「編集中のファイルから検索」でGrepした場合、
これまで保存済みのファイルが対象だったのが、編集中の内容が対象に変わります。
以前の挙動のほうが必要な方がいたらご意見聞かせてください。

2021-04-23 14:44 UTC, berryzplus commented
むぅ、コンフリクトの内容を確認していたんですが、かなり難しい感じに衝突しているようです。
CViewCommander_TagJump.cpp (2箇所)

マージは慣れてるはずの自分が、断念するレベルっす・・・。

2021-04-23 15:45 UTC, dep5 commented
Secutiry HotSpotの修正は_countof()をつけるのでいいんでしょうか？
ビルドさえ成功すればいいと思って、使ってきたのでコード修正についてはわかりません。
できたらどなたか対応してもらえませんか。

2021-04-24 03:33 UTC, berryzplus commented
> Secutiry HotSpotの修正は_countof()をつけるのでいいんでしょうか？
> ビルドさえ成功すればいいと思って、使ってきたのでコード修正についてはわかりません。
> できたらどなたか対応してもらえませんか。

解析結果 https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1639&resolved=false&types=SECURITY_HOTSPOT に書いてありますよ。

- wcscpy(dest, src)は、srcの中身がdestの確保サイズより大きい場合にオーバーフローします。
  wcsncpy_s(dest, _countof(dest), src, _TRUNCATE)のようにオーバーフローする部分を考慮した実装が推奨です。
- wcscat(dest, somethingToAdd)もオーバーfフローします。
  連結した文字列長が確保サイズを越えないことを保証したいだけなので_s版じゃなくてもよいです。
  同様に_s版関数を使うのか推奨です。
- wcslen(dest)はdestがnullptrのとき、アクセス違反で落ちます。
  destがNULLのときwcslen(dest)を呼ばないように修正すれば良いです。

当面でヤヴァいのはコンフリクトっす。

2021-04-24 04:49 UTC, suconbu commented
> この変更でファイルを開いて編集中に「編集中のファイルから検索」でGrepした場合、
> これまで保存済みのファイルが対象だったのが、編集中の内容が対象に変わります。
> 以前の挙動のほうが必要な方がいたらご意見聞かせてください。

私は賛成です。
どこぞからコピーして無題ウィンドウに貼り付けたテキストを、いちいち保存せずにいつもの「Grep」ができるのは結構便利な気がします。※ grep というより sed な感覚ですね。

2021-04-24 08:07 UTC, berryzplus commented on sakura_core/cmd/CViewCommander_TagJump.cpp
> +	// :HWND:[01234567] 無題1(1234,56)  [SJIS]: str
ここのところ、現役でコード書く人じゃなくても、参加できる話題だと思います。

サクラエディタは、入社1年目のド素人とかに薦めるアプリですが、
そういうやつらに「HWNDとは？」を説明する手間を考えると、HWNDは要らないように思います。
アプリ内のウインドウ識別に「無題1」で足らんかというとそうでもないはずなので。

変更自体は「全然アリ」だと思っています。
むしろ、従来の「編集中ファイルをGrep」って編集中じゃねーじゃん！とすら思っております。
（旧仕様は未保存の編集中ファイルをGrepすることはできないっすから。）

2021-04-24 13:02 UTC, dep5 commented
wcscpy(pszTagName, L"(Grep)");
wcsncpy_s(pszTagName, _countof(pszTagName), L"(Grep)", _TRUNCATE);

wcscpy( szJumpToFile, szPath );
wcsncpy_s( szJumpToFile, _countof(szJumpToFile), szPath, _TRUNCATE );

wcscpy( szFile, szPath );
wcsncpy_s( szFile, _countof(szFile), szPath, _TRUNCATE );

wcscat( szPath, szFile );
wcscat_s( szPath, _countof(szPath), szFile );

wcscat( szJumpToFile, szFile );
wcscat_s( szJumpToFile, _countof(szJumpToFile), szFile );

if( NULL == p ) return false;
pmemTitle->SetStringHoldBuffer(p, wcslen(p));

if( NULL == szWindowPath ) return false;
int nPathLen = wcslen(szWindowPath);

if( NULL == szExts ) return false;
size_t nExtLen = wcslen( szExts );

こういう変更でいいんでしょうか？
後でテストしてみます

2021-04-24 13:16 UTC, dep5 commented on sakura_core/cmd/CViewCommander_TagJump.cpp
> +	// :HWND:[01234567] 無題1(1234,56)  [SJIS]: str
テクニカルな感じがして気にいっていたのですが、変更してもいいかもしれませんね。
ファイルを編集していなければ通常のGrepになるので、対象がファイルではないとわかるようにしたいですね。
編集中のファイルパスにGrepをする、と理解していました。

2021-04-24 13:57 UTC, dep5 commented
suconbuさん
まさにコピーして貼り付けた内容をGrepしてその結果を別のソフトで処理して、と使っています。
結果出力の表示を変更したりできて便利なんです。

2021-04-24 15:10 UTC, berryzplus commented
> こういう変更でいいんでしょうか？

はい。

if( NULL == szNanika ) という判定は、Windows APIプログラムでは歴史的に一般的ですが、
C++の作法に照らして見ると正しくないです（＝ポインタを数値と比較してるから。）
なので、if( !szNanika ) とか if( nullptr == szNanika ) とする感じになります。

あと、wcslenの戻り型はsize_tなので、intで受ける場合にはキャスト付加が推奨っす。
```
int nPathLen = wcslen(szWindowPath);
```

int = 32bit
size_t = 64bitだから

int nPathLen = static_cast<int>(wcslen(szWindowPath));

このへんとかwcscatは、std::wstring使ったほうが楽だと思います。

2021-04-25 12:40 UTC, dep5 commented
Grep置換が動かないので「編集中のテキストから検索」を選択できなくしました。
Grep置換で「編集中のファイルから検索」を使っている方がいたら意見を聞かせてください。

2021-05-01 13:18 UTC, dep5 commented
Security Hotspotsの解消はNULLチェック以外にどうしたらいいですか？

2021-05-01 14:55 UTC, beru commented on sakura_core/CGrepAgent.cpp
> +		if( !p ){
ここのローカル変数のポインタ `p` が有効かどうかを判定して有効でなかったら `return false;` する記述は不要だと思います。

2021-05-01 15:03 UTC, beru commented on sakura_core/CGrepAgent.cpp
> +			int nPathLen = static_cast<size_t>(wcslen(szWindowPath));
ここの記述は下記のようにすればよいと思います。

```cpp
auto nPathLen = wcsnlen_s(szWindowPath, _countof(szWindowPath));
```

2021-05-01 15:07 UTC, beru commented on sakura_core/CGrepAgent.cpp
> +		pmemTitle->SetStringHoldBuffer(p, wcslen(p));
ここの `wcslen(p)` の呼び出しが Security Hotspot になっていますが出なくするには下記のように書いてしまえばよいと思います。

```cpp
pmemTitle->SetStringHoldBuffer(p, 8);
```

8 というのはポインタ `p` が指す文字列 `Window:[` の文字数です。

2021-05-01 15:12 UTC, beru commented on sakura_core/cmd/CViewCommander_TagJump.cpp
> +		size_t nExtLen = wcslen( szExts );
ここの記述は下記のようにすればよいと思います。

```cpp
auto nExtLen = wcslnen_s( szExts, _countof(szExts) );
```

2021-05-02 04:14 UTC, berryzplus commented on sakura_core/CGrepAgent.cpp
> +		if( !p ){
なんかすごいコードが残ってたんですね :smiley:

2021-05-02 11:26 UTC, beru commented on sakura_core/CGrepAgent.cpp
> +		if( !p ){
元のパッチにはこの記述は無かったんですが cb0f3cece8bcd305e8b0b46af6dc63d6e82b4ce3 で追加されています。
dep5 さんは https://github.com/sakura-editor/sakura/pull/1639#issuecomment-826089746 でこの変更で良いのか確認を取ってますね。

2021-05-02 11:38 UTC, beru commented
> Secutiry HotSpotの修正は_countof()をつけるのでいいんでしょうか？
> ビルドさえ成功すればいいと思って、使ってきたのでコード修正についてはわかりません。
> できたらどなたか対応してもらえませんか。

@dep5 さん、もし問題が無ければこちらで対応するのでコメント下さい。

2021-05-03 06:06 UTC, berryzplus commented on sakura_core/CGrepAgent.cpp
> +		if( !p ){
> 元のパッチにはこの記述は無かったんですが [cb0f3ce](https://github.com/sakura-editor/sakura/commit/cb0f3cece8bcd305e8b0b46af6dc63d6e82b4ce3) で追加されています。
> dep5 さんは [#1639 (comment)](https://github.com/sakura-editor/sakura/pull/1639#issuecomment-826089746) でこの変更で良いのか確認を取ってますね。

ん？

https://github.com/sakura-editor/sakura/pull/1639#issuecomment-826107038

> > こういう変更でいいんでしょうか？
> 
> はい。

確かにｗ

2021-06-07 12:40 UTC, dep5 commented
PR のメリットに検索結果のカウントができると書いていましたが
カウントできていませんでした。
本当はnHitCountに値を入れるようにしたかったですが、わたしにはできなかったので
nGrepTreeResultに値が入っているようなのでこれを使っています。

かっこの位置を間違えていたところも変更しています。

beruさんの修正をそのまま反映しました。
そちらで対応いただければ助かります。
ぜひそのようにお願いします。

Grepの対象ファイルに(":HWND:"+16進数16桁)と入れて検索すると
タスクマネージャーでしか終了できないウィンドウ？ができるので
それにも対応していただけませんか。

2021-06-09 13:39 UTC, dep5 commented
v0.22は提案をそのままのせただけなのでauthorを変更しました。

v0.23についてです。しばらく悩んでいた挙動の再現手順がようやくわかりました。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/39492557 でテストしました
文書を新規作成する
Grepで「編集中のテキストから検索」にチェックを入れ検索する
表示された結果画面でGrepをもう一度呼び出す
「編集中のテキストから検索」のチェックを外す
対象ファイルに:HWND:から始まる文字列が入っている---(1)
そのまま検索してしまい履歴に残ってしまう
文書を新規作成する
Grepの結果画面を閉じる(対象ファイルの示す先がなくなる)
新規作成した文書でGrepダイアログを開き、対象ファイルに:HWND:から始まる文字列を選択する
「編集中のテキストから検索」のチェックを外して検索する

この画面を閉じようとすると「Grepの処理中です。」というダイアログが出てきて、
タスクマネージャーで強制終了するしかなくなる---(2)

2番目が特にひどいので今回対応できてよかったです。

対象ファイルの最初6文字が:HWND:だったら
(1)*．*に変更する
(2)検索を中止する

という対応にしていますが対象ファイルで「:」は何か意味がある文字ですか？

2021-06-14 14:11 UTC, dep5 commented
v0.20でszJumpToFileをwstringで書き換えたかったのですが、
IsHWNDTagにNULLを渡す方法がわからず、タグジャンプを動かすことを優先にして
そのままにしていました。

IsHWNDTagでは3つの引数があるときは2番目の引数を使っていないようなので、
そのように書き換えると、wstringにすることができました。

2021-06-14 14:31 UTC, beru commented
@dep5 更新ありがとうございます。commit履歴が見やすくなるようにrebaseしてもらう事は可能ですか？

バージョン番号はコミットメッセージに含めているんですね。

動作確認等これから行っていきます。

2021-06-14 14:42 UTC, beru commented
@dep5 このPRの変更でGrep画面で「編集中のファイルから検索」にチェックを入れた場合に無効化されるコントロールが増えたように見えます。内部処理的の細かい変更はコードレビューで確認する事だと思いますが、ユーザー視点でどのように挙動が変わるのかについての解説をPRの説明でスクリーンショット付きで書いてくれると助かります。ただ面倒な場合は別にいいです…。

2021-06-14 14:59 UTC, beru commented
「編集中のテキストから検索」にチェックを入れた場合に「検索場所」と「対象ファイル」のコンボボックスに表示されるテキストが `(現在のドキュメント)` に変化するようになりましたね。その状態で「上階層へ」ボタンや「現フォルダ」ボタンを押すと「検索場所」のコンボボックスに表示されるテキストが変わってしまいます。この挙動は元からそうなんですがなんか変ですね。「編集中のテキストから検索」にチェックを入れた場合には「上階層へ」ボタンと「現フォルダ」ボタンも無効化した方が良いのかもと思いました。どうでしょうか？

2021-06-16 12:54 UTC, dep5 commented
beruさん
「上階層へ」「現フォルダ」ボタンがこんな動きをするとは初めて知りました。
ありがとうございます。さっそくグレーアウトしました。
ついでにサブフォルダのチェックが外れてしまうのもグレーアウトだけにしましたが、
何か問題あるかもしれません。

「commit履歴が見やすくなるようにrebase」というのは現在のmasterをベースに最初からということですか？それとも一部でよいですか？
数字を振ってないものはほんとはrebaseしたかったのでやりたいです。
このcommitはひとまとめでよいというアドバイスありましたら教えて下さい。

2021-06-16 13:06 UTC, dep5 commented
適用前
![Grep](https://user-images.githubusercontent.com/66961537/122222720-79be0780-ceed-11eb-91df-6f1c3abc09b9.png)
適用後
![Grep2](https://user-images.githubusercontent.com/66961537/122222723-7a569e00-ceed-11eb-929a-663d759a1653.png)
現在のパスが表示されていた2項目が(現在のドキュメント)に
除外フォルダ・ファイルが空白に

今回
「上階層へ」「現フォルダ」
「サブフォルダも検索」の選択状態を保つように

そのうえで以上の項目がグレーアウトします

またGrep置換では「編集中のテキストから検索」が
最初からグレーアウトして操作できなくしてあります。

2021-06-18 13:05 UTC, dep5 commented
beruさん
https://github.com/dep5/sakura/compare/grepthis-r
最新masterで作り直してコミットもいくつかまとめてみましたがどうでしょうか？
新規にプルリクエストしてもよい気がしてきましたが、rebaseした方がよいですか？

2021-06-18 16:24 UTC, beru commented
> https://github.com/dep5/sakura/compare/grepthis-r
> 最新masterで作り直してコミットもいくつかまとめてみましたがどうでしょうか？
> 新規にプルリクエストしてもよい気がしてきましたが、rebaseした方がよいですか？

新規にPRを作成したかったらそれでも良いと思いますが、その場合このPRと内容が被るのでこのPRはCloseする事になりそうですね。念のためにお伝えしますが `git rebase` した後はコミットのSHA-1が変わるのでremoteに通常の `git push` は出来ないので、`git push --force` する必要が有ります。conflict が発生している場合の rebase は慣れないうちは少しややこしいので、面倒であれば rebase ではなくて新規にPR作成でも全然問題無いと思いますよ。

2021-06-18 16:41 UTC, beru commented
@dep5 `grepthis-r` ブランチ（54b534504e73c8d577a2c6853c1e6006ad995018）を動作確認してみました。

「編集中のテキストから検索」のチェックボックスを付けると下記のコントロールの表示内容が設定されて無効化でグレーアウトになります。そしてチェックを外すと元の状態に戻ります。
- 検索場所
- 対象ファイル
- 除外ファイル
- 除外フォルダ

チェックを付けたてから外すと元々設定されていたテキストに戻す動作は良いと思います。

気になるのは実際に検索を実行していないのにチェックを付けた時点のコントロールのテキストが記憶されてしまう事です。記憶されるというのは、ESCキーを押してGrepダイアログを閉じてから再度 Ctrl + G キーを押してGrepダイアログを開いた場合に前回設定されていたテキストが復帰される事を指します。

元の挙動はどうだったか `master` ブランチ (c1568ded08eee89759f6954ed15d4fc79069b029) に切り替えて挙動を確認してみたところ「編集中のファイルから検索」のチェックを付けると「検索場所」と「対象ファイル」のコントロールが無効化されますがその際に「検索場所」には変更前のテキストを設定して「対象ファイル」のテキストには現在開いているファイルのファイル名が設定される挙動でした。チェックを外すと「検索場所」と「対象ファイル」のコントロールが有効化されますが「対象ファイル」のテキストは元々設定されていた `*.*` には戻らずに現在開いているファイルのファイル名が設定されたままです。これはこれで良くない動作ですね。

2021-06-18 16:43 UTC, beru commented
@dep5 さん https://github.com/sakura-editor/sakura/pull/1639#issuecomment-862363858 でスクリーンショットを貼ってくれてありがとうございます。「適用前」と「適用後」の画像が反対ですかね？

2021-06-19 16:25 UTC, dep5 commented
スクリーンショットの文字を修正しました。
パッチをまとめて当てた際にエラーが出るようになったので、しばらくこのPRを続けさせてください。
Escで抜けるとこんな動きをするんですね。
除外関連はさわらないので気付きませんでした。
ほかの方法がありそうですが、とにかく対応してみました。
どうでしょうか？

2021-06-20 11:49 UTC, dep5 commented
PRからパッチをダウンロードして複数のパッチを当てた時に、
RC2104 undefined keyword or key name:     sakura_rc.rc 90
と出るようになってビルドできなくなりました。
エラーの起きたキーワードも空白だし、該当行を見てもヒントになりません。

前回まではgit amでパッチを当てていたのをgit applyにしたためのようです。

コミット日時での前後情報がうまく処理されないのでしょうか？
UTF16のはずのsakura_rc.rcがUTF8になっていました。
これをUTF16で保存し直すとビルドできました。

パッチの問題ではなさそうなので、Security Hotspotsに対応して新規のPRにしました。
#1696

コメント・アドバイスいただいた方ありがとうございました

2021-06-20 11:49 UTC, closed without merging

2021-06-22 17:52 UTC, beru commented
> スクリーンショットの文字を修正しました。

修正確認しました。自分は画像を交換する事しか思いつかなかったですが、スクリーンショットの見出しの文字を交換で対処する方法も有りですね。

> ほかに投稿したパッチをまとめて当てた際にエラーが出るようになったので、対応する間しばらくこのPRでこのまま続けさせてください。
> Escで抜けるとこんな動きをするんですね。
> 除外関連はさわらないので気付きませんでした。
> ほかの方法がありそうですが、とにかく対応してみました。
> どうでしょうか？

#1696 のブランチ `dep5:grepthis-r` d46ff926e4ffd232fdb086c4e399f7084293884c で動作確認しましたが、https://github.com/sakura-editor/sakura/pull/1639#issuecomment-864158246 に書いた現象は変わらずでした。

2021-06-22 17:55 UTC, beru commented
> PRからパッチをダウンロードして複数のパッチを当てた時に、
> RC2104 undefined keyword or key name: sakura_rc.rc 90
> と出るようになってビルドできなくなりました。
> エラーの起きたキーワードも空白だし、該当行を見てもヒントになりません。
> 
> 前回まではgit amでパッチを当てていたのをgit applyにしたためのようです。

PRからパッチをダウンロードって何でしょうか？自分はやった事が無い操作かも。。

> 
> コミット日時での前後情報がうまく処理されないのでしょうか？
> UTF16のはずのsakura_rc.rcがUTF8になっていました。
> これをUTF16で保存し直すとビルドできました。

使っているgitクライアントの名前とバージョンはなんでしょうか？

なお自分が使っているのは下記のものです。
```
TortoiseGit 2.12.0.0
git version 2.29.2.windows.2
```

> パッチの問題ではなさそうなので、Security Hotspotsに対応して新規のPRにしました。
> #1696

今後はそちらを確認する事にします。

2021-06-23 15:43 UTC, beru reviewed
`CDlgGrep::OnBnClicked` において

```cpp
if (::IsDlgButtonChecked(GetHwnd(), IDC_CHK_FROMTHISTEXT)) {
```

の条件判定は無い方が動作がより自然になると思いますがどうでしょうか？

2021-06-23 15:43 UTC, beru commented on sakura_core/dlg/CDlgGrep.cpp
> +		if (::IsDlgButtonChecked(GetHwnd(), IDC_CHK_FROMTHISTEXT)) {
@dep5 さん、この if の判定は不要だと思います。

この判定がある事で下記の操作を行うと不自然な挙動になります。

操作内容 | スクリーンショット
----------|--------
Ctrl + G キーを押してGrepダイアログを表示します。| ![image](https://user-images.githubusercontent.com/1131125/123125315-5cf07980-d483-11eb-9fcb-41d7f0f5595f.png)
「対象ファイル」のテキストを `*.*` から `*.*あああ` に変更します。| ![image](https://user-images.githubusercontent.com/1131125/123125448-7bef0b80-d483-11eb-87cc-177cb20278e1.png)
「編集中のテキストから検索」にチェックを入れます。 | ![image](https://user-images.githubusercontent.com/1131125/123125720-bbb5f300-d483-11eb-8635-1ef60fa7cf2a.png)
「編集中のテキストから検索」のチェックを外します。 | ![image](https://user-images.githubusercontent.com/1131125/123125798-ccfeff80-d483-11eb-83f1-14b549fc7fa1.png)
Escapeキーを押してGrepダイアログを閉じます。| &nbsp;
再度 Ctrl + G キーを押してGrepダイアログを表示すると「対象ファイル」のテキストが `*.*あああ` のままになっています。 |  ![image](https://user-images.githubusercontent.com/1131125/123126050-07689c80-d484-11eb-8faa-531595629609.png)

自分が正しいと思う挙動についてですが、
- Grepダイアログを開いてから検索条件を変更する
  - 検索を実行してからGrepダイアログを閉じて再度Grepダイアログを開いた場合は、検索前にコントロールに設定していた検索条件が復帰される
  - 検索を実行せずにGrepダイアログを閉じて再度Grepダイアログを開いた場合は、検索条件を変更する前の検索条件がコントロールに設定される