レイアウト桁位置に対するロジック桁位置の進め方を改善する
sakura-editor/sakura pull request #1658
Opened 2021-05-03 12:39 UTC by kazasaku

#  PR の目的
レイアウト情報の作成過程で、ロジック桁位置の進む量を文字に応じて変化させる。

##  カテゴリ
- 仕様変更

##  PR の背景
現状のレイアウト作成処理では、レイアウト桁位置に対応するロジック桁を次の数だけ進めるようになっています。
- ワードラップ: 単語の桁数
- 行頭禁則: 禁則対象文字と追い出される文字を合わせた桁数
- その他の禁則処理: 禁則対象文字の桁数
- それ以外: 1文字分の桁数

ここでいう文字の桁数は、1文字が必ずロジック単位で1つであることを想定しているようです。
ロジック行上のデータはUTF-16で表現されるため、サロゲートペアはロジック単位で2つ進めなければなりません。
このため、レイアウト作成フローはサロゲートペアが分割されてしまうリスクを抱えています。

一方、行データのイテレータである CMemoryIterator クラスでは、
以前からロジック・レイアウト単位の増分をそれぞれ CNativeW クラスの静的メンバで計算しており、
サロゲートペアに遭遇しても問題がないようになっています。

##  PR のメリット
レイアウト作成時にサロゲートペアが前後に分割処理されることによって発生しうる不具合を防げます。

##  PR のデメリット (トレードオフとかあれば)
この PR の変更対象としたクラスには単体テストがなく、共有データ依存のため追加も難しいです。
このため一時的にカバレッジが低下します（全期間で見たカバレッジには影響ありません）。

##  仕様・動作説明
レイアウト作成処理において、現在処理している物理データ行上の文字の位置は、 SLayoutWork 構造体のメンバ変数に保持されています。
これまでこの変数にロジック単位で（文字ごとに）1ずつ加算していたところを、各文字毎に`CNativeW::GetSizeOfChar()`で取得した値を加算するように変更します。

なお、既存コードに追加した GetSizeOfChar のオーバーロードを活用できる箇所がいくつかありますが、遡及適用は行っていません。

##  PR の影響範囲
各行のレイアウト作成を行う際の準処理（`CLayoutMgr::_MakeOneLine()`）

##  テスト内容
指定した内容でタイプ別設定を変更したのち、添付したマクロ実行します。
[テスト用マクロ (test.zip) ](https://github.com/sakura-editor/sakura/files/6414725/test.zip)

### 手順
1. タイプ別設定一覧ダイアログから、「テキスト」タイプの設定を次のように変更します。  
   （この設定変更を忘れないでください。）
    - 英文ワードラップ：有効
    - 句読点ぶら下げ：有効
    - 改行ぶらさげ：有効
    - 行頭禁則：有効
    - 行末禁則：有効
2. 添付のマクロを実行し、結果を確認します。
    - マクロで挿入されるデータは 329 文字・レイアウト 57 行・ロジック 29 行です。  

##  関連 issue, PR
#1543 

##  参考資料

2021-05-04 05:05 UTC, k-kagari requested changes
概要を読んだ限りでは不適切な仕様を改善する変更のように思えますが、実際に現在の実装でサロゲートペアが分割される例があるのかどうかが分かりませんでした。

分割される例があるかどうかの検証が必要だと思います。実害がないなら変更そのものが不要になってしまいますし、あるのなら改善を証明するテスト手法があったほうが良いように思います。

2021-05-04 05:37 UTC, kazasaku commented on sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
> -		if(0 == k)k = CLayoutInt(1);
現時点ではここに来るのは次の文字の時だけです（ IS_KEYWORD_CHAR の仕様による）。
`#$0123456789@ABCDEFGHIJKLMNOPQRSTUVWXYZ\_abcdefghijklmnopqrstuvwxyz`

自分には過去に行ったサロゲートペア対応時の削除漏れに見えました。
また、この箇所以外に0pxを1pxにみなす動作をしている箇所はすべてコメントアウトされているはずです。

2021-05-04 05:44 UTC, kazasaku commented
> 不適切な仕様を改善する変更のように思えますが、実際に現在の実装でサロゲートペアが分割される例があるのかどうかが分かりません

実際に問題になったのは行頭禁則処理においてです。次行に追い出されるロジック単位文字数が足りませんでした。
#1543 では条件判定追加で済ませましたが、後から桁数の算出方法が非対称になっている（※）ことがそもそもの原因だと思いましたので、本PRを作成しました。
（※：レイアウト単位の増分は文字ごとに計算するのに対して、ロジック単位の増分は値が固定されている）

2021-05-04 05:46 UTC, kazasaku commented on sakura_core/mem/CNativeW.h
> +		{ return GetSizeOfChar( cStr.GetPtr(), cStr.GetLength(), nIdx ); }
CStringRef を扱う GetKetaOfChar / GetColmOfChar のオーバーロードにもテストが無いです。
これらも追加しときます。

2021-05-04 08:51 UTC, kazasaku commented on sakura_core/mem/CNativeW.h
> +		{ return GetSizeOfChar( cStr.GetPtr(), cStr.GetLength(), nIdx ); }
対応完了。

2021-05-04 10:17 UTC, k-kagari commented on tests/unittests/test-cnative.cpp
> +		CStringRef SetString(const wchar_t* pcStr, size_t nLen) { return CStringRef(pcStr, nLen); }
GetSizeOfChar の呼び出し時に CStringRef を直接構築すると不都合があるのでしょうか？ 少し考えてみましたがよく分かりませんでした。

2021-05-04 10:17 UTC, k-kagari commented on tests/unittests/test-cnative.cpp
> +TEST(CNativeW, GetSizeOfChar_with_CStringRef) {
これは好みの問題かもしれませんが、テストケースごと増やすよりも以前からのテストケースに assertion を追加する形の方が簡潔で良いように思えます。同じコメントを繰り返す必要がなくなりますし、内容のほぼ同じ asssertion は隣接していた方が読む人のストレス軽減に役立ちそうです。

2021-05-04 10:17 UTC, k-kagari commented on sakura_core/mem/CNativeW.h
> +		{ return GetSizeOfChar( cStr.GetPtr(), cStr.GetLength(), nIdx ); }
> CStringRef を扱う GetKetaOfChar / GetColmOfChar のオーバーロードにもテストが無いです。

これはたぶん私のやらかしです。追加していただきありがとうございます。

2021-05-04 13:37 UTC, k-kagari commented
添付のマクロを動かしてみました。
- PR適用前後で結果に変化はありませんでした。
- 「329 文字・レイアウト 57 行」でしたが、「ロジック 29 行」ではなく「27 行」になっているように見えます。（環境依存？ ロジック行の数え方が間違っている？）

行番号を数えて29でしょうか？ 終了時のステータスバーの表示であれば「28 行」になっています。

2021-05-04 14:17 UTC, k-kagari commented
> 27 行で正しいです。

でしたら大丈夫ですね😃

> 実際に問題になったのは行頭禁則処理においてです。次行に追い出されるロジック単位文字数が足りませんでした。
> #1543 では条件判定追加で済ませましたが、後から桁数の算出方法が非対称になっている（※）ことがそもそもの原因だと思いましたので、本PRを作成しました。

ある種の弥縫策を改めて本修正にしたという理解でよろしいでしょうか。そういうことでしたら前後で変化がないことを確認するテストで適切ですね。

2021-05-04 14:18 UTC, k-kagari approved these changes
良さそうに見えます。

2021-05-04 15:38 UTC, berryzplus commented
レビューありがとうございます。
このへんは難しくて、積極的にレビューに加われなかった感じですが、異論はないです。

サクラエディタの内部文字コードは、いわゆるUnicodeです。
Unicodeには複数のエンコーディング方式が存在していますが、Windows標準はUTF-16LEなので
サクラエディタの内部エンコーディングもUTF-16LEを基本としています。

|形式|内容|備考|
|--|--|--|
|文字列|&#x1F6B9; &#xD7; &#x1F6BA;||
|`uint32_t[]`|`\u1F6B9` `\xD7` `\u1F6BA`||
|`wchar_t[]`|`\xD83D` `\xDEB9` `\xD7` `\xD83D` `\xDEBA`|サロゲートペアのhi,lowは必ずこの順。|
|`std::byte[]`|`\x3D` `\xD8` `\xB9` `\xDE` `\xD7` `\x00` `\x3D` `\xD8` `\xBA` `\xDE`|リトルエンディアンなのでこう見える。|

サクラエディタでは、Unicodeに変換できなかったバイトデータを `\xDCxx` にマップする（ことがある）という仕様があるので、末尾から前方に向けて一文字進めるときの処理が若干複雑になります。

2021-05-05 06:39 UTC, kazasaku commented
レビューありがとうございます。
マージしてしまいます。
他に問題があれば対応いたしますのでお知らせください。

2021-05-05 06:40 UTC, merged