Windows8.1でスクロール時に画面が乱れるのを修正
sakura-editor/sakura pull request #1694
Opened 2021-06-07 14:57 UTC by dep5

#  PR の目的
#1601 での変更でWindows 8.1で表示の乱れが起きることがあるので修正します

##  カテゴリ

- 不具合修正

##  PR の背景
Windows 8.1でマウスで選択中、または選択部分をマウスでドラッグしているときに
スクロールが発生すると画面が乱れます。

##  PR のメリット
Windows 10での動作には影響が少ないと思います

##  PR のデメリット (トレードオフとかあれば)
Windows 10で動いているかどうかの判定にmanifestを追加するので、何か影響があるかもしれません。

##  仕様・動作説明
view/CCaret.cppの
::SendMessage(hWnd, WM_SETREDRAW, FALSE, 0);
をコメントアウトすると収まったので、背景の条件時に呼び出さないようにします

##  PR の影響範囲

##  テスト内容

### テスト1

手順

##  関連 issue, PR
#1601

##  参考資料
[Windows 用アプリケーションのターゲット設定 - Win32 apps | Microsoft Docs](https://docs.microsoft.com/ja-jp/windows/win32/sysinfo/targeting-your-application-at-windows-8-1)

2021-06-07 15:04 UTC, dep5 commented
本体で対応するよりWindows 10 未満用のバージョンを用意するのがいいかもしれません。
必要なのはWindows 10 以上かどうかだけですが、そのままマニフェストに入れています。
Windows 10での動作に影響が無いようにしたいので、よければアドバイスください。

2021-06-09 09:47 UTC, sanomari commented
> Windows 8.1でマウスで選択中、または選択部分をマウスでドラッグしているときに

修正内容が妥当だとすると色々矛盾する気がします。

やってること
・マニュフェストファイルを埋め込んでwin10判定できるようにする
・#1601 で入れた WM_SETREDRAW を win10 の場合のみに制限する
　👇
WM_SETREDRAWはwin10でしか使えないので、チェックしてから呼ぶように修正する、という趣旨の変更に見えます。

しかし、メッセージ自体はw2kから有効なので、矛盾します。
https://docs.microsoft.com/en-us/windows/win32/gdi/wm-setredraw


> スクロールが発生すると画面が乱れます。

現象を報告する「用語」が見慣れないのが少し気になってます。
「乱れる」とは具体的にどういう状態でしょう？

発生事象を「乱れる」と表現できるなら、ハード故障が疑われます。
たぶん、そうではないと思うんですけど、本当に乱れているなら買い替えが妥当、と言ってみます。

2021-06-09 13:07 UTC, arigayas commented
最近GitHubに動画ファイル(mp4)を貼ることが出来るようになったので
どのように乱れるのかスクリーンキャプチャーソフトで録画して
ここにアップロードすると良いと思います。
_GIFアニメでも良いです_

@dep5 さん
あとお使いのパソコンのグラフィックチップが
Intel なのか
GeForce なのか
Radeon なのか
ほんのちょびっと気になりました。

2021-06-09 13:14 UTC, dep5 commented
#1246 と同様の挙動です。GIF画像を添付してくださっているのでご覧ください

マウスを使って描画範囲外まで選択またはドラッグするためにスクロールした場合に発生するようです。

WM_SETREDRAWはwin10でしか使えないというよりかは
win10以外でFALSEに設定すると条件により画面が乱れるので、使う前にバージョンチェックが必要になるということです。

キーボードで操作する、スクロールしない、ステータスバーを表示しないなら、問題は起きません。。

GPUはRadeonです

2021-06-10 11:55 UTC, dep5 commented
はい、最新のmasterで再発しているという意味です。

更新の終了したWindows 7でもチェックしてみましたが（Intelのグラフィック）
同様にスクロールの描画に問題があり
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/39495505
対策したこちらでは普通にスクロールできました。
有償サポートのWindows 7でも同様の現象が起きるかもしれませんが、持ってないのでわかりません。

Windows 10では描画の問題が修正されているのでしょう。

2021-06-11 04:14 UTC, sanomari commented
対策したい事象は「ちらつき」だってことですかね。

「ちらつき」は、再描画指示が余分に行われることにより発生します。
WM_SETREDRAWを使うと、発行された再描画命令を無効にできます。

呼び分けを入れようとしているWM_SETREDRAWは描画抑制をかけるほうですが、
問題あるとするなら描画抑制を解除するタイミングなんではないでしょうか。

2021-06-12 12:54 UTC, berryzplus requested changes
変更の妥当性に納得がいきませんでした。

2021-06-12 12:54 UTC, berryzplus commented on resource/manifest.xml
> +      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
windows7は既に黒歴史入りしてたと思います。
windows8は8.1の登場により延長サポートが破棄されてた気がします。

マニュフェストを入れること自体に文句はありませんが、
「ファイルで指定する必要がある」と判断して方針を変えるなら他の定義も含めるべきと思います。

2021-06-12 12:54 UTC, berryzplus commented on sakura/sakura.vcxproj
>      </Manifest>
挿入するのは1箇所でよいです。
`x86 - Debug`だけマニュフェストを添付ない、とかやりたい場合を除いて。

2021-06-12 12:54 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +const bool IsWin10 = IsWindows10OrGreater();
そのまま使ったらよいと思います。

2021-06-12 12:54 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +			}
誰もツッコミ入れてないですが、ここダウトですよね？

`win10の場合だけWM_SETREDRAWを送るように修正する`じゃないじゃん :smiley:

2021-06-14 14:17 UTC, dep5 commented
sanomariさん
ちらつきならいいのですが・・・
画像のような状態なので何か対処が欲しいです。

berryzplusさん
manifestの指摘いただいた項目は必要ないので削除しました。
Windows 7は企業ユーザーには使っている人もいるかもしれないですね。
サクラエディタでsakura.exeを開くと最後の方に文字列が確認できますが、
通常のビルドでもmanifestが埋め込まれています。
そこにWindowsのバージョン情報を追加するファイルです。

Visual Studio 2019で、プロジェクト > プロパティ の > 構成プロパティ > マニフェストツール > 入出力
「すべての構成・すべてのプラットフォーム」を選んで
追加のマニフェストファイルに入力すると4か所に追加されました。
わたしも1か所で十分ではないかと、いろいろしてみましたが、わかりませんでした。

IsWindows10OrGreater()は多数回呼び出されると思うので
変数に入れたほうがいいと思いましたが、そのままでよいのですね。削除しました。

ダウトというのはifが空だということでしょうか？
Windows 10未満でのチェックが
!,||,&&の使い方がよくわからなかったので、後回しにしていましたが、修正しました。

![win8](https://user-images.githubusercontent.com/66961537/121906806-6e8c9f80-cd66-11eb-9ace-8fef40f42c65.png)

2021-06-17 04:06 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +const bool IsWin10 = IsWindows10OrGreater();
> IsWindows10OrGreater()は多数回呼び出されると思うので
> 変数に入れたほうがいいと思いましたが、そのままでよいのですね。削除しました。

繰り返し使う関数戻り値は、ローカル変数にキャッシュすると思います。

* グローバル変数を定義しています。
* このグローバル変数が初期化されるタイミングが謎です。
* 名前が短くなったのは評価に値する（？）ようにも思いますが、不正確な名前になっとります。
*

2021-06-17 04:13 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +			}
> ダウトというのはifが空だということでしょうか？

ダウト　＝　Win10じゃないときのコードが`WM_SETREDRAW を呼ばない`でないことをダウトと言ってます。

仕様動作説明の記述と一致しないと言ってます。
> view/CCaret.cppの
> ::SendMessage(hWnd, WM_SETREDRAW, FALSE, 0);
> をコメントアウトすると収まったので、「PRの背景」に書いた条件時に呼び出さないようにします

コメントアウトじゃねーじゃん、というツッコミです。

コード的には、win10じゃないときは WM_SETREDRAW に行く前にチェックを挟むように変えてますよね？
その変更がいいか悪いかは分からんですが、説明の筋が通らないことを気にしています。

2021-06-17 04:19 UTC, berryzplus requested changes
更新っす。

> manifestの指摘いただいた項目は必要ないので削除しました。
> Windows 7は企業ユーザーには使っている人もいるかもしれないですね。

意識的に古いバージョンのWindowsを使っている人々は存在します。
  * 軍需産業（兵器等）に携わる人々（日本国内には存在しない建前）
  * 一部の医療機器を触る人々（生命維持装置など）
  * 放射線を応用した機器を扱う人々（レントケンやCTとか）
  * 独自開発のハードウェア（独自機器）を扱う人々（ハード開発に携わる現場）

これらの特殊機器は外界から切り離された環境で稼働することもあり、
意識的にWindows Updateと無縁な世界で運用されます。
極限に高いセキュリティを要求される分野なので、サクラエディタが利用される事態は考えにくいです。

そうでない環境でWindows7以前のOSを使ってるなら、
それは単にその企業のシステム管理者がアフォなだけっす。
まっとうなシステム屋としては、適切に突っ込むべきだと思います。

> Visual Studio 2019で、プロジェクト > プロパティ の > 構成プロパティ > マニフェストツール > 入出力
> 「すべての構成・すべてのプラットフォーム」を選んで
> 追加のマニフェストファイルに入力すると4か所に追加されました。
> わたしも1か所で十分ではないかと、いろいろしてみましたが、わかりませんでした。

vcxprojはxmlファイルなので、テキストエディタで編集できます。
condition指定なしのノードを入れてやればよいです。

2021-06-17 04:26 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +			}
違うかも。
説明が分かりづらいだけで、説明通りの変更になってるかも。

結局、win10じゃない場合だけ WM_SETREDRAW の呼出を条件付にするって対応が、何故妥当なのか分からんです。
なんとなく、win10の場合も「問題が表面化してないだけ」なんじゃないの？という点が気になります。

2021-06-18 13:00 UTC, dep5 commented
berryzplusさん
こう書くんですね。ありがとうございます。
マニフェストファイルの指定を1つにまとめました。



[項目定義 | Microsoft Docs - Visual Studio | Microsoft Docs](https://docs.microsoft.com/ja-jp/visualstudio/msbuild/item-definitions?view=vs-2019)

2021-06-18 14:05 UTC, kazasaku commented
少し前に「ウィンドウ下端（＝ステータスバー付近）の複数行を範囲選択した後、別の行にカーソルを移動したので範囲選択は解除されているはずなのに、その領域がなおも選択されているように見える」ということがありました。

> OS: Windows 10 Pro 21H1 (64bit)
> PC: Dell Latitude e7270
> CPU: Intel Core i5-6300U
> GPU: Intel HD Graphics 520
> サクラエディタ: v2.4.2.3817 32bit dev ( 9152b834e2a30146662b0713897d2875777e5cab )

現象を再現できていないので参考にならないかもしれない😰ですが、念のためメモしておきます。

2021-06-19 16:12 UTC, dep5 commented
kazasakuさん
ステータスバー付近を選択した際にスクロールは起きましたか？
マウスでの操作でしたか？

「Windows 10未満で」
「マウス操作中に」
「選択中か選択部分のドラッグ中に」
「スクロールする」
のが条件だと考えていますが、いくつか関係あるかもしれませんね。

再現するのって大変ですよね・・・。

2021-06-20 05:30 UTC, kazasaku commented
> kazasakuさん
> 
> 「Windows 10未満で」
> 「マウス操作中に」
> 「選択中か選択部分のドラッグ中に」
> 「スクロールする」
> のが条件だと考えていますが、いくつか関係あるかもしれませんね。
> 
> 再現するのって大変ですよね・・・。

そうですね😅。
僕の体験はさておき、このPRが言及している事象を真面目に調べようと思って、範囲選択の描画処理にブレークポイントを入れたところ、偶然再現できました。

- 再現できた環境
    - OS: Windows 10 Pro 64bit (バージョン21H1, ビルド19043)
    - PC: Dell Latitude e7270
        - CPU: Intel Core i5-6300U 2.40~3.00GHz（ハイパースレッディング無効のため論理2コア）
        - GPU: Intel HD Graphics 520
    - IDE: Visual Studio 2019 16.10.2
    - SDK: Windows 10.0.19041.685 (Win10 2004相当)
    - サクラエディタ: v2.4.2.0 32bit DEBUG dev ( ef76fe1437d130854150584d0619cef27261098f )
- 再現に成功したときの作業内容
    1. 選択範囲を描画する処理の呼び出し回数を確認するため、次の関数にトレースポイントを設定
        - CViewSelect.cpp#L178 `void CViewSelect::DrawSelectArea(bool);`
        - CViewSelect.cpp#L298 `void CViewSelect::DrawSelectArea2(HDC) const;`
        - CViewSelect.cpp#L511 `void CViewSelect::DrawSelectAreaLine(HDC, CLayoutInt, const CLayoutRange&) const;`
    2. Visual Studioを開いてビルドし、デバッグ実行を開始する
    3. 適当なファイルを開く
        キャプチャ動画では`CRecentImp.cpp`を使いました。
    4. ドラッグスクロールを行う
- 実行結果
https://user-images.githubusercontent.com/67105596/122663061-c302a580-d1d2-11eb-9435-855d4fb65fb1.mp4

余談：XBox Game Barがこんなことに役立つとは思わなかったです。1024x472・60fps・約18秒で10MBくらいになりました。

2021-06-20 05:42 UTC, kazasaku commented
なお、次の環境でも c1568ded08eee89759f6954ed15d4fc79069b029 をビルドした[成果物](https://github.com/sakura-editor/sakura/actions/runs/936370990)を使って再発を確認しました。
>OS: Windows 7 Home Premium 32bit Service Pack 1
>PC: Dell Latitude e6320
>CPU: Intel Core i5-2520M 2.50~3.20GHz（ハイパースレッディング無効のため論理2コア）
>GPU: Intel HD Graphics 3000
>サクラエディタ: v2.4.2.1100 32bit dev ( c1568ded08eee89759f6954ed15d4fc79069b029 )

2021-06-20 06:07 UTC, berryzplus commented
このPRの変更点は大きく2つと思ってます。
* **実行環境が Win10 以外のバージョンで** WM_SETREDRAWするタイミングがおかしい懸念があるので対策したい。
* 実行環境が Win10 かどうかを判別できるようにするため マニュフェストを添付したい。

いま引っ掛かってるのは「**実行環境が Win10 以外のバージョンで**」の部分です。
もし単に「WM_SETREDRAWするタイミングがおかしい懸念があるので対策したい。」だとするなら、バージョン判定のためのマニュフェスト添付は要らないです。そして「懸念があるので対策したい」であれば、反対するために反証を用意する必要があるので反対する理由がなくなります。「不具合を修正します」の場合には、「不具合である」と「対応により不具合を解消できる」を証明しないといかんと思いますが、懸念の対策ならかなりラクです。

マニュフェスト添付自体についても、単体で入れるなら特に反対する理由はないです。
が、現状だと「添付したい理由」が誤ってる可能性があって（≒Win10でも再現してそう）、
何年後かにアフォの子に説明することを考えるとすっごくダルいです・・・。

2021-06-20 06:22 UTC, berryzplus commented
PRの本筋と関係ないですが、メモっておきます。

> なお、次の環境でも [c1568de](https://github.com/sakura-editor/sakura/commit/c1568ded08eee89759f6954ed15d4fc79069b029) をビルドした[成果物](https://github.com/sakura-editor/sakura/actions/runs/936370990)を使って再発を確認しました。
> 
> > OS: Windows 7 Home Premium 32bit Service Pack 1
> > PC: Dell Latitude e6320
> > CPU: Intel Core i5-2520M 2.50~3.20GHz（ハイパースレッディング無効のため論理2コア）
> > GPU: Intel HD Graphics 3000
> > サクラエディタ: v2.4.2.1100 32bit dev ( [c1568de](https://github.com/sakura-editor/sakura/commit/c1568ded08eee89759f6954ed15d4fc79069b029) )

現状のCI/CDビルドでは、バージョン`v2.4.2.1100` の末尾数字`1100`が環境によって変わる（≒一意にならない）のを対策したいと思ってます。#1687

2021-06-20 12:21 UTC, dep5 commented
kazasaku さん
ブレークポイントを右クリックして条件でアクションを選ぶとトレースポイントになるんですね。
さっそく手順を試すと、再現しました。Windows 10でも起きるんですね。
最初にサクラエディタで現象が起きた時もvisual studioでデバッグ中でしたか？
Windows 10でリリースビルドでも起きるんでしょうかね？


berryzplusさん
コードレビューの質問に答えてくださっているのに気づきませんでした。すいません。
変数をどこに書いたらわかりませんでしたがキャッシュされるんですね。安心しました。
win10ではあまりサクラエディタを活用しておらず、ちょっとテストしてみた感じでは
スクロールの問題はなさそうでした。
#1601 の目的は処理の効率化だということでif文を通るたびにその効果を減じるのではないかと心配して、
Windows 10に影響が無いように考えたつもりです。
windowsバージョン判定しないならmanifestの追加もいらないですね。


スクロールが無い時はWindows 8.1でも問題ないのですが・・・。

2021-06-20 15:01 UTC, kazasaku commented
> 最初にサクラエディタで現象が起きた時もvisual studioでデバッグ中でしたか？

「最初」というのが数日前の[このコメント](https://github.com/sakura-editor/sakura/pull/1694#issuecomment-864063753)を指しているのであれば「いいえ」です。まぁ、これはこのPRが出た直後でまだ内容を確認する前だったと思いますし、結局再現できなかったので忘れてよいです。
ただ、おかげで #1246 の事案はWin10でも再発しているんじゃないかと思うきっかけにはなりました。

> Windows 10でリリースビルドでも起きるんでしょうかね？

改めて確認しましたが、同じ環境でDebug/Releaseともに再現できました。

2021-06-20 15:37 UTC, berryzplus commented on sakura_core/view/CCaret.cpp
> +const bool IsWin10 = IsWindows10OrGreater();
> 繰り返し使う関数戻り値は、ローカル変数にキャッシュすると思います。

誤読された気がするので補足っす。

グローバル変数ではなくローカル変数にキャッシュするのが普通だと思います。
という意図で書いたコメントです。

* 戻り値をキャッシュする意義については、異論ないです。
* 確保域がグローバルであっても、const付き（≒定数）なら深刻な問題にはならないと思います。
* イニシャライザに書いたグローバル関数について、呼出タイミングが予測不能であることが気になっています。

2021-06-24 13:45 UTC, dep5 commented
Windows 8.1で描画が乱れた後の状況を説明していませんでした。

マウスでドラッグ中にサクラエディタの上下端にポインターを移動するとスクロールが始まります。
それ以外の中央付近にポインターを移動するとスクロールが停止します。
これをスクロール停止エリアと呼ぶことにします。
適切な呼び方はあるんでしょうか？

Windows 8.1
・マウスで選択中のスクロール
画面が乱れた状態でスクロール停止エリアで少しずつポインターを上下に動かすと1行ずつ正しい表示になります。
上下に動かしすぎて少しでもスクロールが発生するとまた画面が乱れます。
マウスボタンのアップで画面全体が正しい描画になります。

・選択部分をマウスでドラッグアンドドロップ中のスクロール
ずっと乱れたままなのでドロップ先が決められない。
マウスボタンのアップで画面全体が正しい描画になります。


Windows 10
・マウスで選択中のスクロール
スクロール停止エリアにポインターを移動すると画面全体が正しい描画になります。

・選択部分をマウスでドラッグアンドドロップ中のスクロール
描画の乱れは起きない


Windows 10ではWM_SETREDRAW, FALSEでも適宜再描画されているのでしょうか？

2021-06-24 13:46 UTC, dep5 commented
#1601 で説明されているパフォーマンス プロファイラーで少し調べてみました。
sakura_rc.rcを表示して、30秒ずっと上下にスクロールしました。各条件で1回動かしただけです。
このテストでは画面の乱れは起きませんでした。

sakura_core/view/CCaret.cpp の
::SendMessage(hWnd, WM_SETREDRAW, FALSE, 0); を
(1)そのまま
(2)削除
(3)if (!m_pEditView->GetSelectionInfo().IsMouseSelecting() && !m_pEditView->m_bDragMode) {
		::SendMessage(hWnd, WM_SETREDRAW, FALSE, 0);
	} に置き換える

Windows 10
・マウスで選択中のスクロール
(1) 5.5%
(2) 18.5%
(3) 21.5%

・PageUp,PageDownで選択せずにスクロール
(1) 0.5%
(2) 8%
(3) 0.5%

(3)ではちらつきが少し発生しました。

https://github.com/sakura-editor/sakura/pull/1694#issuecomment-864502098 の手順で
・選択部分をマウスでドラッグアンドドロップ中のスクロール
をテストしてみましたが、スムーズに表示されました。
しかし、トレースポイントを設定する箇所が違うのかもしれません。

・マウスで選択中のスクロール
実際の使用ではバイナリをサクラエディタに読み込ませると再現できるかもしれません。

2021-06-24 13:52 UTC, dep5 commented
まとめると
Windows 8.1ではマウスボタンを押したままスクロールした時
マウスボタンを放すまで画面が乱れるので操作ができなくなる。

Windows 10でもマウスで選択中にスクロールした時画面が乱れる場合があるが、
スクロールが停止すると描画は正常になる。
ドラッグアンドドロップでは症状は起きない。

#1601 にはCPU使用率をおさえる効果がある。
今回の(3)の対策ではかえってちらつきが発生する。

わたしのテストした範囲ではこのようになりました。
不具合の重大さがまるで違うと思いますが、どうでしょうか。
Windows 8.1での文書編集できない状態の応急措置と考えていますのでバージョン判定は必要だと思います。

2021-06-25 04:23 UTC, kazasaku commented
なんかヒントになりそうなコードを見つけました。

ある地点から開始されてなお継続している範囲選択処理では、直前の選択範囲との差分を描画領域としているようです。
https://github.com/sakura-editor/sakura/blob/c1568ded08eee89759f6954ed15d4fc79069b029/sakura_core/view/CViewSelect.cpp#L223-L228

自分のWin10環境でCEditView.cppを開いてファイルの先頭から末尾までドラッグスクロールしてみたところ、下方向は34px（2.5行相当）、上方向は14px（1行相当）となっており、現象発生時に更新されていた行の範囲に近いです。
（ちなみに、Ctrl+Aキーで全選択したときは364px（26行相当で表示領域の総行数と同じ）でした。）

なお、現象発生時でも時々編集ビューの上下端でない部分が再描画されることがありましたが、これは編集ビュー宛てのメッセージで別途描画処理が実行されたことによるものでした。

今までは差分更新で対象外となった領域が、何かしらの処理で`WM_PAINT`などのメッセージが送られて更新されていたために、問題が表面化しなかったのではないでしょうか。

そういえば、`WS_EX_COMPISITED`スタイルはWin8だと正常に機能しない噂を聞きましたが、どうなんでしょうね。

2021-06-25 04:26 UTC, kazasaku commented
> ・マウスで選択中のスクロール

たぶん、これが https://github.com/sakura-editor/sakura/pull/1694#issuecomment-864502098 で再現できたやつですね。

> ・選択部分をマウスでドラッグアンドドロップ中のスクロール

えっと、たぶん初耳です。
一応、Microsoft の公式仮想環境（英語版）で確認はできたので、後で動画をとっておきます。

---
余談：以下は一個人のどうでもよさそうな意見です。

> これをスクロール停止エリアと呼ぶことにします。
> 適切な呼び方はあるんでしょうか？

普段使うアプリケーションの動作を見た感じでは、アイテムをドラッグ中に表示領域の上下端付近にカーソルが来た場合、「表示されていない領域にドロップしようとしている」とみなして、スクロールを追加で行っているように感じます。
故に、「スクロール停止エリア」という領域は存在しないと僕は思うのですが。

2021-06-25 11:36 UTC, kazasaku commented
> Microsoft の公式仮想環境（英語版）で確認はできた~~ので、後で動画をとっておきます。~~

Microsoft Edge Developer向けに提供されているWin8.1の公式イメージをHyper-V環境で起動し、最新のAppVeyorビルド版を実行してみました。
テキストを選択してドラッグした際にスクロールが発生すると、確かに表示がおかしくなります。そのままテキストをドロップすれば表示は回復します。

なお、表示がおかしいときでもステータスバーの座標だけは正しく更新されているようです。

2021-06-26 10:32 UTC, suconbu commented
CEditView::ScrollDraw にて InvalidateRect の後に UpdateWindow が呼ばれていない点が怪しそうです。

https://github.com/sakura-editor/sakura/blob/c1568ded08eee89759f6954ed15d4fc79069b029/sakura_core/view/CEditView_Scroll.cpp#L594-L605

Windows10 にてですが https://github.com/sakura-editor/sakura/pull/1694#issuecomment-864502098 に記載の方法で「マウスで選択中のスクロール」の問題を再現させることができ、所々にログを追加してトレースポイントを追加する前と後の違いを調べたところ、トレースポイント追加後では CEditView が WM_PAINT (赤字部分) を受信できていません。
![image](https://user-images.githubusercontent.com/11252784/123509625-80990700-d6b1-11eb-8879-9ce3443e2662.png)

InvalidateRect の説明を読むと「更新領域が空でない、かつキューが空の時に限り WM_PAINT を送信する」とあります。
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-invalidaterect#remarks
(Windows10 での再現時においては) トレースポイントが追加されたことでマウスメッセージの処理が少し遅くなり、後者の条件が満たされなくなっていた可能性がありそうです。

@dep5 さん
CEditView::ScrollDraw の末尾に「UpdateWindow();」を追加することで Windows8.1 でも問題が解消するかどうか、一度試してみて頂けますか。

2021-06-26 11:45 UTC, suconbu commented
Windows10 で再現できる現象は UpdateWindow を追加することでほぼ解消されました。
ただし、スクロール中にマウスカーソルをウィンドウから遠ざけすぎるとまだ起きてしまいます。。

バージョン|動画
-|-
UpdateWindow なし | ![sakura_scrollerror_without_updatewindow](https://user-images.githubusercontent.com/11252784/123511593-1be3a980-d6bd-11eb-80f2-74a1fd8c3251.gif)
UpdateWindow あり (表示異常が起きないケース) | ![sakura_scrollerror_updatewindow](https://user-images.githubusercontent.com/11252784/123511597-2140f400-d6bd-11eb-927a-ebe48499ee97.gif)
UpdateWindow あり (表示異常が起きるケース) | ![sakura_scrollerror_updatewindow_error](https://user-images.githubusercontent.com/11252784/123511621-45043a00-d6bd-11eb-9f94-60113e61a718.gif)

2021-07-02 13:56 UTC, dep5 commented
kazasakuさん
いろいろ調べていただいてありがとうございます。
WS_EX_COMPOSITEDもいじってみましたが、問題解消に効果がなかったように思います。
停止エリアは!(スクロールエリア)みたいな意味でつけてみたんですが、あんまりよくなかったですね・・・。


suconbuさん
目についたInvalidateRectの後にUpdateWindow();を追加しても、何も変わらなくてがっかりしたのですが、
コメントを読み直して、最後の}の前に追加したところ
選択中のスクロール、ドラッグアンドドロップでのスクロール共に乱れが解消しました！
1行追加すると直るんですね。
#1642 とも似ているなと思いました。
ぜひ、プルリクエストをお願いします。
こちらは閉じようと思います。



コメントいただいた方、ありがとうございました。

2021-07-02 16:20 UTC, suconbu commented
@dep5 さん

ご確認ありがとうございます。
了解しました。私の方で引き取り対応させて頂きます。

しかし、元々の修正方法※でも発生しなくなっていた理由が良くわかりませんね。。
描画処理が重くなって逆に起きやすくなるような気がしますけどね。
※`::SendMessage(hWnd, WM_SETREDRAW, FALSE, 0);` を呼ばなくする

2021-07-02 16:28 UTC, suconbu commented
> ただし、スクロール中にマウスカーソルをウィンドウから遠ざけすぎるとまだ起きてしまいます。。

1回の移動量が表示行数 (or列数) 以上になるとこちらの処理に流れるようで、ここにも UpdateWindow が必要でした。(追加したら直りました)
https://github.com/sakura-editor/sakura/blob/9768d7f0537b00ac4a801ce7542f99dfa61ff056/sakura_core/view/CCaret.cpp#L297-L307

InvalidateRect を呼んでいる箇所は一度全部点検をした方が良さそうです。

2021-07-07 11:01 UTC, kazasaku commented
dep5さん、#1699 がマージされているので、最新のmasterを試して欲しいです。
問題がなければ、このPRはCloseできます。

2021-07-09 14:18 UTC, dep5 commented
最新のmasterで問題が解消されました。ありがとうございました

2021-07-09 14:18 UTC, closed without merging