履歴データ管理クラスに関するヘッダーファイルのインクルード文を整理する
sakura-editor/sakura pull request #1697
Opened 2021-06-23 05:33 UTC by kazasaku

#  PR の目的

##  カテゴリ

- 機能追加
- 仕様変更
- 不具合修正
- 速度向上
- リファクタリング
- ドキュメント修正
- プログラムの動作上の問題
  - 正式リリース版
  - Azure Pipelines ビルド版
  - AppVeyor ビルド版
  - GitHub Actions ビルド版
  - ローカルビルド版
- ビルド関連
  - ビルド手順
  - Azure Pipelines
  - AppVeyor
  - GitHub Actions
  - ローカルビルド
- ドキュメントの問題
- GitHub 関連の問題
- 実験 (master へのマージを目的としない)
- その他の問題

##  PR の背景

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

##  PR の影響範囲

##  テスト内容

### テスト1

手順

##  関連 issue, PR

##  参考資料

2021-06-23 05:53 UTC, kazasaku commented on sakura_core/recent/CRecentFolder.h
> -//StaticVector< StaticString<WCHAR, _MAX_PATH>, MAX_GREPFOLDER, const WCHAR*>
混乱を招きそうな予感がするので可能であれば削除させてほしいです。
- ファイル：CRecentFolder.h（「最近開いたフォルダ」の履歴）
- 記述されている定数値：MAX_GREPFOLDER（履歴に保存可能な「Grepフォルダ条件」の数）

2021-06-23 05:54 UTC, kazasaku commented on sakura_core/recent/CRecentImp.cpp
> +template class CRecentImp<CExcludeFolderString, LPCWSTR>;	// CRecentExcludeFolder
記述が無かったので追記しました。

2021-06-23 05:56 UTC, kazasaku commented on sakura_core/recent/CRecentImp.cpp
>  #if !defined(__MINGW32__) || (defined(__MINGW32__) && !defined(UNICODE))
余談：`defined(__MINGW32__) && !defined(UNICODE)` という条件は必要なのだろうか。

2021-06-23 06:12 UTC, kazasaku commented
Azure PipelinesのMinGWビルドが正常終了したのでDraftは外しておきます。

2021-06-25 15:19 UTC, k-kagari requested changes

2021-06-25 15:19 UTC, k-kagari commented on sakura_core/recent/CRecentImp.cpp
> +template class CRecentImp<CExcludeFolderString, LPCWSTR>;	// CRecentExcludeFolder
テンプレートの明示的インスタンス化はプログラム中で1回までと規定されているため、これらの定義のうち typedef する前の型が重複しているものは実は規格違反だったりします。MinGWでコンパイルを外しているのは GCC の方がこの点を厳密に検査するからかなと推察しました（検証してない）。

重複してしまう実体化は削除したほうがいいと思います。下記のような形になりますね。

```cpp
template class CRecentImp<StaticString<WCHAR, 260>, LPCWSTR>;
template class CRecentImp<StaticString<WCHAR, 512>, LPCWSTR>;
```
可読性・保守性が下がりそうで残念ですけども…。

2021-06-26 02:40 UTC, kazasaku commented on sakura_core/recent/CRecentImp.cpp
> +template class CRecentImp<CExcludeFolderString, LPCWSTR>;	// CRecentExcludeFolder
ちょっと考えましたが、今回は戻しておきます。

> 可読性・保守性が下がりそうで残念ですけども…。

実はこんな共通定義があります。
https://github.com/sakura-editor/sakura/blob/c1568ded08eee89759f6954ed15d4fc79069b029/sakura_core/basis/CMyString.h#L42-L44

`CPathString`・`CMetaPath`・`CCurDirString`・`CSearchString`・`CReplaceString`・`CTagjumpKeywordString`は`SFilePath`と、`CGrepFileString`・`CGrepFolderString`は`SFilePathLong`と定義内容が同じです。
`CExcludeFileString`・`CExcludeFolderString`の定義で使われる定数`MAX_EXCLUDE_PATH`は`MAX_GREP_PATH`と同じ値なので、この二つも現時点では`SFilePathLong`と同じと言えます。

この定義を活用して、こう書くこともできますね。
```
template class CRecentImp<SFilePath, LPCWSTR>;
template class CRecentImp<SFilePathLong, LPCWSTR>;
```
ただ、そうするなら各クラスでもSFilePath/SFilePathLongを利用するようにしたほうがいいのかな、とも思いました。
（typedefは履歴データ構造体側に移せば、長い型名の短縮に使えそうです。）

最も、履歴関係でSFilePath/SFilePathLongを使ってもよいのかはわかりません。

2021-06-26 03:58 UTC, kazasaku commented on sakura_core/recent/CRecentImp.cpp
> +template class CRecentImp<CExcludeFolderString, LPCWSTR>;	// CRecentExcludeFolder
> 履歴関係でSFilePath/SFilePathLongを使ってもよいのかはわかりません

`CSearchString`・`CReplaceString`・`CTagjumpKeywordString`はパス文字列ではないので不適切でした😓

2021-06-26 04:10 UTC, k-kagari approved these changes
妥当だと思います。

2021-06-26 08:56 UTC, berryzplus approved these changes
ビルドが通れば問題ないと思います。

細かい指摘入れましたが対応は任意っす。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
レビュー指摘じゃないんですけど、これらのインクルードがここに必要になるクラス設計がマズいように思います。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/dlg/CDlgGrep.h
> +#include "recent/CRecentExcludeFolder.h"
ここも。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/dlg/CDlgGrepReplace.h
> +#include "recent/CRecentReplace.h"
これも。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/dlg/CDlgReplace.h
> +#include "recent/CRecentSearch.h"
これも。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/recent/CRecentFile.cpp
> +#include "config/maxdata.h"
指摘です。ここだけmaxdata.hの参照が実装側になってる気がします。ヘッダ側で参照すべきでは？

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/recent/CRecentFolder.cpp
> +#include "config/maxdata.h"
あ、ここもやｗ

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/recent/CRecentFolder.h
> -//StaticVector< StaticString<WCHAR, _MAX_PATH>, MAX_GREPFOLDER, const WCHAR*>
無関係なコメント（コピペで作成したあと消し忘れただけ？）かと思います。
削除おっけーです。

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/recent/CRecentReplace.cpp
> +#include "config/maxdata.h"
ここもやｗ　（実装側じゃなくヘッダ側に書くべきじゃ・・・

2021-06-26 08:56 UTC, berryzplus commented on sakura_core/recent/CRecentTagjumpKeyword.cpp
> +#include "config/maxdata.h"
ここもやｗ　（同上

2021-06-27 02:00 UTC, kazasaku commented on sakura_core/recent/CRecentFile.cpp
> +#include "config/maxdata.h"
ヘッダ側で使われていればヘッダ側に、そうでなければソース側に配置する方針で記述しました。

2021-06-27 02:19 UTC, kazasaku commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
CRecentの各実装クラスをクラスメンバとして保持しない方が良いということでしょうか。
現状では、以下のクラスがCRecentをメンバに持っています。
- CDlgExec
- CDlgFavorite
- CDlgFind
- CDlgGrep
- CDlgGrepReplace
- CDlgFileData
- CDlgReplace
- CDlgTagJumpList
- CMRUFile
- CMRUFolder
- CMainToolBar

2021-06-27 14:11 UTC, berryzplus commented on sakura_core/recent/CRecentFile.cpp
> +#include "config/maxdata.h"
方針は了解です。

ただ、maxdata.hに定義されているものは定数なので、「インターフェース or 具象クラス」に当てはめた場合のインターフェース側に当たると思います。

インターフェースの参照は、ヘッダで行うべきな気がします。
ま、言ってみてるだけ（≒このコメントは指摘じゃない）ですが。

2021-06-27 14:24 UTC, berryzplus commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
「CRecentの各実装クラス」の役割が謎なんですよね。

実装から推測されるCRecentクラスの役割
* 履歴配列へのアクセスを容易にする
* 履歴配列に格納されるデータ型と文字列ポインタの交換を容易にする
* 共有メモリへのアクセスを局所化する

たぶん、真面目にクラス設計すると共有メモリへの書き込みアクセスがマルチスレッドを考慮してない件に手を入れる必要があるはずで、その役割を持つのはどのクラスか？と考えるとCRecentが最適な気がするわけです。
　👇
もしコレ（＝CRecentに排他機能を付ける）に踏み切ろうとすると、例示されたウインドウ系クラスが修正対象になります。クラスのメンバにインスタンスを持つということは、ウインドウを表示している間は他スレッドから書き込みできないということで、容易にデッドlロックするアフォな設計になってしまうからです。

2021-06-27 14:34 UTC, berryzplus commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
メンバにCRecent派生クラスのインスタンスを持たない設計には以下のものがあります。
* 読み取りアクセスは現状のまま、ロックして書き込む処理を新設する。
* ロックが必要なときだけ生成するRAIIクラスを新設する。

2021-06-28 08:59 UTC, kazasaku commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
排他制御をCRecent側で行い、利用側が意識しないようにした方が使いやすくなりそうですね。
今のところCAppNodeManagerのメンバ関数だけが、CRecentEditNodeの呼び出し直前にロックを掛けていました。

検討してみます。

2021-06-28 09:06 UTC, kazasaku commented on sakura_core/dlg/CDlgFavorite.h
> +#include "recent/CRecentCurDir.h"
CDlgOpenFileDataクラスは #1481 のマージ以後CRecentのインスタンスを利用していませんでした。
当該コードの除去をCRecent利用側のリファクタリング案件としてPRを提出しようと思います。

2021-06-29 04:17 UTC, kazasaku commented
レビューありがとうございました。マージしてしまいます。

CRecentの各派生クラスは今後変更すると思うので、その時にmaxdata.hのインクルード位置を再考します。

2021-06-29 04:19 UTC, merged

2021-06-29 14:12 UTC, kazasaku commented
本文に記載した3件のSonarQubeによる指摘が消えたことを確認しました。