テキストコピーで無応答となる事象を打開するためにコードを整理する
sakura-editor/sakura pull request #1710
Opened 2021-07-22 15:05 UTC by berryzplus

#  PR の目的

目的はタイトル通りです。
巨大ファイルを開いて全選択＆コピーをしようとしたときに固まる事象の対策ができるように、コード整理を行います。
※このPRを入れた時点で、メモリ確保失敗の場合に「ビンッ！」と音が出てコピーが失敗するようになります。

##  カテゴリ

- 不具合修正
- リファクタリング

##  PR の背景

サクラエディタは x64 対応していません。
ここのプロジェクトのダウンロードからもx64版モジュールは落とせるので
「もう対応してるんじゃないの？」と思う方もおられるかもしれませんが、断じて対応しておりません。

とはいえ、既に使える状態で入手可能な状態にしているものを、
いつまでも「x64には未対応ですから」と放置しておくのも変です。

----
こんなissueが立ちました。
#1575 64bit版で2GBより大きいサイズのテキストのコピペをする事が出来ない

結論からすると「仕様なので諦めてください」です。
文字数が2GBを超えるデータが編集できるようなる未来は「ない」と思っています。
（文字数が2GBを超えるデータの一部を参照できるようになる未来はあり得ます。）

issueに関しての結論は👆なんですけど、
報告された挙動はバグのように見えます。

「64bit版で2GBより大きいサイズのテキストのコピペをする事が出来ない」
　👆コピペできないのは仕様。
　👆コピペしようとすると固まるのは不具合。

##  PR のメリット

メモリ確保が失敗するほどの巨大データを誤ってコピーしようとしても、サクラエディタが固まらなくなります。

##  PR のデメリット (トレードオフとかあれば)

* 対応がかなり中途半端です。
* この対応が「正しい」かどうか自信がありません。
* もし「正しい」とすると周辺コードが全体的に「正しくない」ということになりますが、自分的に「正しくない」とは思っていません。

##  仕様・動作説明

背景で引用した issue で報告されている不具合を引き起こしている関数を整理してみました。
目についた不審点を解消させる修正を含んでいるので修正内容がかなり多いです。

本質的には、必要な修正は２点だけと思われます。
* データ量の計測に使うサイズ値の型を size_t に変更する
* CNativeW::AllocStringBufferの呼出後に、要求したメモリを確保できているかチェックし、メモリ確保に失敗していたら処理を終了させるように変更する。

##  PR の影響範囲

* コピー、カット、ドラッグアンドドロップなど、クリップボードに関連する機能。
* サクラエディタ上の変換機能

##  テスト内容

### テスト1

手順

##  関連 issue, PR

#1575 

##  参考資料

2021-07-23 04:22 UTC, berryzplus commented
「重複コード多過ぎ」の指摘は、今回修正部分とは関係なさそうです。
CEditViewのコピペ関連のコードが「コピペによって作られている」ことが原因。

----
重複コードが多い　≒　コードをコピペして作っている

これがイケナイことかどうかの判断は、プロジェクトの文化に依ります。

コピペが何故イケナイかというと、コピペ元に不具合があった場合の修正箇所が増えるからです。

逆にコピペ可能なコードがあればできるだけコピペすべきだ、という考え方もあります。
既に稼働している、信頼できるコードを複製することのどこに問題があるんだ？という見方です。
プロの世界では、とある事情により「コピペ推奨」の文化が主流です。

個人的には、ロクにテストもしていない、信頼性に疑問のあるコードをコピペすることが問題ないと何故言えるんだ？とか思ったりもするんですけど、それなりに経験を積んだ真面目な職業プログラマがコードを書くと、ついついコピペに走ってしまうのは分かるような気がします。

誰かが言った格言
「コピペは設計ミスである。」
----

これを「正しいもの」として突き詰めると、色々修正せにゃならんです。
それが「必要か？」というと、「別に要らんのじゃね？」と思うので積極的にPRする気にはならんです。

ただ、たぶん、このあたりの問題に対処しないと「快適なサクラエディタ」は作り出せない気がしています。

2021-07-23 15:36 UTC, berryzplus commented
ありゃ？重複コードが検出されなくなってしまいました。
今回修正対象以外のコードを指して「重複している」と出てたので、てっきり外部が原因なのかと思っていました。
修正箇所の変更のみで警告が消えたってことは、今回修正が「重複」と判定されてたってことか。。。＿|￣|○

残ったコードスメルの指摘は、やや難易度が高いです。
> This function has 8 parameters, which is greater than the 7 authorized.

超訳：関数のパラメータが8個です。認可された数（＝7）よりも多いので氏んでください。

初めて知ったのですがSonarCloudの推奨パラメータ数は上限7のようです。
上限7という数字が妥当でないかというと、たぶんそうでもないです。（≒妥当です。）
上限7という数字は、たぶん少ないです。（数字の根拠がおそらく「7±2の法則」だから7では少ない。）
設定された数値が小さ過ぎるので「妥当な指摘ではない」とするのも１つの考え方かもしらんです。

学問的なお話で「割れ窓理論」というのがあります。
六本木ヒルズのビルのキレイに磨き上げられた窓ガラスを割るのには、大きな勇気が要ります。
尾崎豊が窓ガラス壊して廻ったあとの学校の窓ガラスを割るのには、ちょっとの勢いで事足ります。
まー、いずれにしても器物損壊になるので大人はやらんでしょうけど、割れ窓の話なので。

2021-07-24 03:40 UTC, berryzplus commented
PRの趣旨が良く分からなくなってきたので仕切り直します。

いったんDraftを外しておくので、質問等ある方はお気軽にコメントどうぞ。

2021-07-24 17:19 UTC, beru requested changes
コピー＆ペーストの操作で適切に処理が行われない不具合を確認しました。

コピーする行の改行コードがCRLFだと改行前の最後の文字が1文字削られてしまいます。

タイプ別設定の入力モードのデフォルトの文字コードの改行コードの値によって Enter キーを押した時に入力される改行コードが変化します（設定を変えてもソフトを再起動しないと変化しないようです）。

まず改行コードが `CR+LF` の設定で確認します。

- サクラエディタを起動する
- `123` と入力しEnterキーを押して改行すると1行目の改行コードが CRLF で2行目にキャレットが移動する
- Ctrl + A で全選択する
- Ctrl + C でクリップボードにコピーする
- Ctrl + V でクリップボードからペーストする
- 1行目の内容が `12` 改行コード(CRLF)になってしまう
  - 期待する内容はコピーした時点での `123` 改行コード(CRLF) です。

改行コードの設定が `CR+LF` でない場合は、コピー元の改行コードがCRLFでないのにペースト後の改行コードがCRLFになります。

上記のような不具合が追加されるのはまずいので修正が必要です。

2021-07-24 20:29 UTC, berryzplus commented
> 改行コードの設定が `CR+LF` でない場合は、コピー元の改行コードがCRLFでないのにペースト後の改行コードがCRLFになります。
> 
> 上記のような不具合が追加されるのはまずいので修正が必要です。

気付いていませんでした。ありがとうございます。

サクラエディタ内部の特殊仕様でCRLFが「1桁」になることを忘れていました。
処理を簡単にするためなんだかよくわからんのですが、レイアウト的に改行コードは常に1桁です。
文字幅は2桁分使うので1桁扱いなのが謎なんですけど、まぁそういう仕様があるっす。。。

2021-07-25 01:10 UTC, berryzplus commented
> タイプ別設定の入力モードのデフォルトの文字コードの改行コードの値によって Enter キーを押した時に入力される改行コードが変化します（設定を変えてもソフトを再起動しないと変化しないようです）。

タイプ別設定の変更が一部即時反映されないのは既知の不具合です。
設定変更時にエディタウインドウに反映する処理が漏れとります。
改行コードは別の方法で変更できる（かつ、そちらのほうが便利）なので、このまま放置で良いと思います。

ステータスバーに表示されている改行コード CRLF を右クリックすると、現在のドキュメントの改行コードを変更することができます。ステータスバーから操作した場合、改行コードの変更は即時反映されます。

なお、ウインドウ幅を狭めて利用しているとステータスバーに改行コードが表示されないことばあるので注意が必要です。

2021-07-25 03:31 UTC, beru commented
a6a47121baaf34dff0806a99d2e93c203db355c8 で再確認しました。

コピーする行の改行コードがCRLFだと改行前の最後の文字が1文字削られてしまう問題は無くなりました。

改行コードがCRやLFの行をコピーしてからペーストすると改行コードがCRLFに変化してしまう問題は解消されていません。

---

コピペでプログラミングするとコードクローンが生じますが、その話が出るたびにいつも思い出すのが昔阪大で研究開発されていた CCFinder というソフトです。

https://sel.ist.osaka-u.ac.jp/cdtools/

国際的なカンファレスのワークショップで表彰の記念品に羊のドリーの飾りが付いていて味わい深いなぁと思いました。

2021-07-25 07:59 UTC, berryzplus commented
> 改行コードがCRやLFの行をコピーしてからペーストすると改行コードがCRLFに変化してしまう問題は解消されていません。

この変更 7efaa56 の対応漏れでした。
コピー後の文字コードを指定できる機能の「変更しない」を意味するコードを当初設計値（？）に戻しているんですが、
一部で変え忘れているために発生している事象のようです。

2021-07-25 08:16 UTC, berryzplus commented
このPRは、変更の趣旨が分かりにくいので仕切り直す予定です。

現状、変更で影響を受ける箇所について自動テストを書けないのが課題です。
せっかくなのであと一点、追加の変更を入れてから閉じようかなと思っています。

2021-07-25 12:27 UTC, berryzplus commented
いったんpush...

2021-07-26 00:54 UTC, oooonduke commented
サクラエディタ   v2.4.2.3896 64bit dev Alpha Version
(GitHash 9f0fd1c62d10749297d4a1a6b994448e36e2dd17)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V_A641916 WPR WIN601/I800/C000/N601
      Last Modified: 2021/7/25 14:49:56


コピーするとクリップボードに半角後ろ一桁落ちる挙動が確認されました。

2021-07-30 21:23 UTC, berryzplus commented
> コピーするとクリップボードに半角後ろ一桁落ちる挙動が確認されました。

どういう選択状態でテストされましたか？

このPRはやりたいことがぼやけてしまっているので出し直すつもりです。

行末の改行コードを削る処理のところで「1桁削る」と書いているあたりが原因と考えられます。
「1桁削る」と書いてますが扱ってるものは CLogicInt なので「桁」ではないんです。

2021-08-01 02:56 UTC, berryzplus commented
> > コピーするとクリップボードに半角後ろ一桁落ちる挙動が確認されました。
> 
> どういう選択状態でテストされましたか？

線形選択の末尾が改行ではないケースで再現しました。
選択範囲の行末が改行であるかどうかを判定する処理が誤っています。

2021-09-25 06:58 UTC, berryzplus commented
どうしたらいいか、ほぼ結論が出ていることに気付く、なう。

> 本質的には、必要な修正は２点だけと思われます。
> 
> * データ量の計測に使うサイズ値の型を size_t に変更する
> * CNativeW::AllocStringBufferの呼出後に、要求したメモリを確保できているかチェックし、メモリ確保に失敗していたら処理を終了させるように変更する。

この2点だけを行う形でPR作り直します。

2021-09-25 06:58 UTC, closed without merging