Visual Studio 2022に対応する
sakura-editor/sakura pull request #1755
Opened 2022-01-04 11:56 UTC by dep5

#  PR の目的

Visual Studio 2022に対応します。
起動しているVisual Studioのバージョンのツールを使うようにします。

##  カテゴリ

- 不具合修正
- ビルド関連
  - ビルド手順
  - ローカルビルド

##  PR の背景

Visual Studio 2022を使うとソリューション(プロジェクト)の再ターゲットが必要になります。
合わせて想定と違うバージョンのツールが選ばれるのにも対応しました。

##  PR のメリット

そのままビルドできます。
起動したバージョンのツールが選ばれます。

##  PR のデメリット (トレードオフとかあれば)

対応した以外のビルド方法に影響があるかもしれません。

##  仕様・動作説明

vcx-props/vcxcompat.propsとtools/find-tools.batに追記しました。

Visual Studio 2017とそれ以上がインストールされている環境でIDEでローカルビルドをすると
サクラエディタの初回ビルドやリビルドの時に
find-tools.batが動いて各種ツールで2017のものが設定されます。
そのままでも特に問題はないですが、調べてみました。

find-tools.batはtests/compiletests.run.cmdで呼ばれており
tests/compiletests.targetsではNUM_VSVERSIONに起動しているVisual Studioのバージョンが指定されています。
置き換えでいいかもしれませんが、ARG_VSVERSIONにも同様の指定をして、環境変数を追加しています。

tests/googletest.targetsにも同様の指定があるので対応した方がよいかも。

##  PR の影響範囲

対応した以外のビルド方法に影響があるかもしれません。

##  テスト内容

Visual Studio 2022 IDEのsakuraプロジェクトを右クリックしてビルドします。

### テスト1

手順

##  関連 issue, PR

##  参考資料

2022-01-04 12:58 UTC, kazasaku commented on tests/compiletests.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
不要な対応だと思います。

2022-01-04 13:02 UTC, kazasaku commented
僕が #1752 で言及した直後にこういったものが出てくると、なんだか不安になってきます。

2022-01-04 13:21 UTC, dep5 commented
https://github.com/sakura-editor/sakura/discussions/1752
の内容はCIの対応についてではないですか？
2017を残したままの環境で
ローカルで2022IDEからビルドした場合に2017のCMAKEが動いてしまうことへの対処です

設定する環境変数はNUM_VSVERSIONではなく、ARG_VSVERSIONではないかなと思います。

2022-01-04 13:46 UTC, kazasaku commented
> #1752 の内容はCIの対応についてではないですか？ 

CIの話ではありますが、VS2017のビルドをCIで確認できないということは、VS2017を使い続けることが困難になるということでもあります。特定バージョンでしかビルドできないコードを弾くためにも確認できないといけません。
ということで、結局はローカルビルドにまで影響する話になるだろうと予想しています。

2022-01-04 14:38 UTC, berryzplus reviewed
不要と思われる修正が1箇所、質問が1件あるので、コメントのみです。

2022-01-04 14:38 UTC, berryzplus commented on vcx-props/vcxcompat.props
> +  </PropertyGroup>
ジジくさい指摘です。

17の挿入位置がおかしいと思います。
「16、15」と並んでいるので「17、16、15」となるように入れるのが素直な気がします。
間に挿入するメリットが何かありますか？

2022-01-04 14:38 UTC, berryzplus commented on vcx-props/vcxcompat.props
> +  </PropertyGroup>
v143はここでよいと思います。（当然

2022-01-04 14:38 UTC, berryzplus commented on tools/find-tools.bat
> +::     2022 or 17  => Visual Studio 2022
ここのコメント修正はどちらでもよいです。

visual studio 的に「バージョン」とは 17.0 のことで 2022 は「商標」にあたります。
ここで指定するのはバージョンなので、2桁を前にしたほうが良いように思います。（対応不要

2022-01-04 15:59 UTC, kazasaku commented on tools/find-tools.bat
> +::     2022 or 17  => Visual Studio 2022
そもそも
```
  ::     2017 => Visual Studio 2017
  ::     2019 => Visual Studio 2019
+ ::     2022 => Visual Studio 2022
  ::     15     => Visual Studio 2017
  ::     16     => Visual Studio 2019
+ ::     17     => Visual Studio 2022
```
とすればよかったような気もします。

2022-01-04 16:02 UTC, kazasaku commented on vcx-props/vcxcompat.props
> +  </PropertyGroup>
> 「16、15」と並んでいる

そのようには見えません。上から順に「15.0」「16.0」「17.0」になっています。

2022-01-04 16:06 UTC, kazasaku commented on tools/find-tools.bat
>      )
ここも変更する必要がある気がします。
https://github.com/sakura-editor/sakura/blob/90951db80693289dd59700ed02de7ced1da67485/tools/find-tools.bat#L235

2022-01-05 09:58 UTC, berryzplus commented on vcx-props/vcxcompat.props
> +  </PropertyGroup>
自分の見間違いでした。

2022-01-05 10:07 UTC, berryzplus commented on tools/find-tools.bat
>      )
👆の部分は、利用できるMsBuildのパスを列挙する部分です。
ここを修正しないとPRの目的が達成されないのではないかと思います。

vs2019のMsBuildは、vs2022を使ったビルドができる仕様なので、
結果オーライになると予想されますが、vs2022しか入れない端末でのビルドができないんじゃないかと思いました。

2022-01-05 10:36 UTC, berryzplus commented
@kazasaku さん
> 僕が #1752 で言及した直後にこういったものが出てくると、なんだか不安になってきます。

コメントの意図が分からないです。

「こういったもの」がこのPRを指すのは自明ですが、
このPRを「どういったPR」と評価しているかが謎です。
後に続く「不安」から、プラスには捉えてはないんですかね。。。

個人的には「あきらかにアカンやつ」とは思っていないです。
vs2022を使いたい人は使えばいいと思います。
「まだ早い」が良識だと思いますが。

2022-01-05 13:35 UTC, dep5 commented
指摘ありがとうございます。

わたしも最初そのように変更していたのですが
vswhere -version [15,16)
とすると「15.0.0...以上」「16.0.0...未満」という意味になるようです
つまり、15系のみを指定しています
[Examples · microsoft/vswhere Wiki · GitHub](https://github.com/Microsoft/vswhere/wiki/Examples)


:find_msbuild で CMD_MSBUILD が設定されない場合に
:find_msbuild_legacy が呼ばれ、15系があれば15のMsbuildを使うという意味のようです

今までARG_VSVERSIONが無かったので :find_msbuild_legacy が呼ばれていました
ARG_VSVERSIONがあれば :find_msbuild で CMD_MSBUILD が設定されます。

サクラエディタがいつまで対応するかは置いておいて、
Visual Studio 2017のサポートは2027年まであるようなので
(コメントなのに)最終的に8行になってしまうことと
2017と17で間違えそうになったのでまとめてしまいました。
:msbuild での流れを見ると2017,2019... のほうが先に来るのが自然かと思いましたがどうでしょうか？

Visual Studio 2019のみ、2022のみの環境で動くのかは気になっています。
どなたかビルドできるかテストしてもらえませんか？

tests/compiletests.targetsで NUM_VSVERSION を残すべきか
tests/googletest.targetsをどうすべきかについてはいかがでしょうか？

2022-01-05 14:10 UTC, kazasaku commented
> @kazasaku さん
> 
> > 僕が #1752 で言及した直後にこういったものが出てくると、なんだか不安になってきます。
> 
> 
> 
> コメントの意図が分からないです。
> 
> 
> 
> 「こういったもの」がこのPRを指すのは自明ですが、
> 
> このPRを「どういったPR」と評価しているかが謎です。
> 
> 後に続く「不安」から、プラスには捉えてはないんですかね。。。
> 
> 
> 
> 個人的には「あきらかにアカンやつ」とは思っていないです。
> 
> vs2022を使いたい人は使えばいいと思います。
> 
> 「まだ早い」が良識だと思いますが。
> 
> 

自分の中では「CIも対応したみたいだし、そろそろ**検討**を始めませんか」と言う段階なので、いきなり対応開始するPRが出されたのは「タイミングが早すぎる」と感じています。

2022-01-05 14:16 UTC, kazasaku commented
> tests/compiletests.targetsで NUM_VSVERSION を残すべきか
tests/googletest.targetsをどうすべきかについてはいかがでしょうか？

それらtargetsファイルの変更は要らないと言っています。

2022-01-05 14:54 UTC, kazasaku commented
> それらtargetsファイルの変更は要らないと言っています。

`find-tools.bat`の処理は`setlocal`コマンドと`endlocal`コマンドで囲われています。
このため、`setlocal`を呼んでから`endlocal`を呼ぶまでの間に設定した環境変数はローカル変数として扱われます。
`endlocal`より後で設定した環境変数はグローバル変数になりますが、`find-tools.bat`で`endlocal`の後ろにあるコードは次の部分だけです。
https://github.com/sakura-editor/sakura/blob/42568b86ce23081aab9e013180b51b4e35a324f5/tools/find-tools.bat#L58-L75
ここで`NUM_VSVERSION`に選択されたVSのメジャーバージョンが設定され、その値を後からtargetsファイルなどが利用します。
`ARG_VSVERSION`は、find-tools.batを呼び出す前にあらかじめユーザーが設定したとかでなければ定義されないはずです。

2022-01-08 06:17 UTC, kazasaku commented on tools/find-tools.bat
>      )
VS2019/VS2022が混在した環境で実行し、vswhereにどんな引数が入るか確認してみました。
引数指定なしの場合
```
find-tools.bat
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version [15,16\)
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion -latest
vswhere -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -version [17,18\)
|- CMD_MSBUILD=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
|- CMAKE_G_PARAM=Visual Studio 17 2022
end
```
引数に「15」を与えた場合（※実行した環境にVS2017はインストールされていない）
```
find-tools.bat
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version [15,16)`
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion -latest`
vswhere -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -version [17,18)`
|- CMD_MSBUILD=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
|- CMAKE_G_PARAM=Visual Studio 17 2022
end
```
引数に「16」を与えた場合
```
find-tools.bat
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version [16,17)
vswhere -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -version [16,17)
|- CMD_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
|- CMAKE_G_PARAM=Visual Studio 16 2019
end
```
引数に「17」を与えた場合
```
find-tools.bat
vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version [17,18)
vswhere -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -version [17,18)
|- CMD_MSBUILD=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
|- CMAKE_G_PARAM=Visual Studio 17 2022
end
```

探索ロジックがまずビルドツールを「指定したバージョンが利用できるか調べ、できなければ最新のものを選ぶ」ようになっており、MSBuildは「ビルドツールの探索で決定したバージョンのものを探す」ようになっているようなので、find-tools.batの実行結果からは問題なく見えています。

しかし、`find_msbuild_legacy`で実行されるvswhereの呼び出し箇所は、逆に「利用できる一番古いもの」という動作になりそうな気がします（上記と同じ環境で実行しました）。
```
> vswhere -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion -latest
17.0.32014.148

> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,17)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
```
ビルドツールの探索と同じく、指定バージョンのものが見つからなければ利用可能な最新のものを選ぶようにして良いのではないかと思うのですが。
```
vswhere -requires Microsoft.Component.MSBuild -property installationPath -latest
C:\Program Files\Microsoft Visual Studio\2022\Community
```

2022-01-08 06:22 UTC, kazasaku commented on tools/find-tools.bat
>      )
単独環境はこうなりました。

VS2017のみ
```
> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,16`)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,17`)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
```
VS2019のみ
```
> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,16`)

> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,17`)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
```

VS2022のみ
```
> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,16`)

> vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,17`)
```

2022-01-08 12:20 UTC, dep5 commented
kazasakuさん

その部分の前に
https://github.com/sakura-editor/sakura/blob/42568b86ce23081aab9e013180b51b4e35a324f5/tools/find-tools.bat#L39
が呼ばれています。
`setlocal`コマンドと`endlocal`コマンドで囲われた箇所です
`:msbuild`では
`NUM_VSVERSION`は`ARG_VSVERSION`の値で上書きされています。
`ARG_VSVERSION`を指定しない場合、15が設定されます

つぎに`:msbuild`の中で`:check_installed_vsversion`が呼ばれ
例えば、Visual Studio 2019のみをインストールした環境では15.0のVisual Studioがないので
`:check_installed_vsversion`の中で` :check_latest_installed_vsversion`が呼ばれ
最終的に`NUM_VSVERSION`に一番新しいVisual Studioが設定されます。

わたしの直面したのは15.0と17.0の組み合わせですが、
15.0、16.0、17.0のうち一つだけインストールしていると(当然)それが選ばれ、
15.0と16.0、15.0と17.0、15.0と16.0と17.0という組み合わせなら15.0が選ばれ、
16.0と17.0という組み合わせなら17.0が選ばれるように思います。
15.0が入ってない環境で`ARG_VSVERSION`を設定せずにリビルドした場合、
今までわずかながら無駄なvswhereの呼び出しが入っていた、ということになると思います。

コマンドラインでのビルドについて考えてみます。CIもこれでしてるのでしょうか？
https://github.com/sakura-editor/sakura/blob/42568b86ce23081aab9e013180b51b4e35a324f5/build-sln.bat#L22
まずこれが呼ばれるようなので、どのバージョンが選ばれるかは上と同じだと思います。

2022-01-08 12:25 UTC, dep5 commented on tools/find-tools.bat
>      )
vswhere -versionを使って抽出するには
```
VS2017のみ
vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,16)
VS2019のみ
vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [16,17)
VS2022のみ
vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [17,18)
VS2017とVS2019
vswhere -requires Microsoft.Component.MSBuild -property installationPath -version [15,17)
```
となります。
1つだけ指定のメジャーバージョンを見つけるにはこう書くようです。
```
vswhere -version [x,x+1)
```

2022-01-08 12:37 UTC, dep5 commented
find-tools.batでバージョンを受け入れるのは`ARG_VSVERSION`だけなのに、
targetsファイルで指定しているのは `NUM_VSVERSION`なので
問題が起きているのではないでしょうか？

targetsが意図しているのがfind-tools.batにVSVERSIONを渡すことなら
find-tools.batを`NUM_VSVERSION`を受け入れるように編集するか
targetsで`ARG_VSVERSION`を設定するように追加or変更する必要があります。

> どうしてもVS2022を使いたいんだとかであれば別ですが。

そう言われれば、その通りです。
PRの説明にもある通り困っているので、投稿しています。
ぜひよろしくお願いします

2022-01-08 13:00 UTC, berryzplus commented
実現したことが明確で変更理由に筋が通っているなら導入して問題ない内容だと思っています。

・vs2022でもビルドできるようにしたい
・compiletest.targetsのバグ（？）を直したい
・find-tools.batのバグを直したい

find-tools.batには一貫性のないロジックがあると思うんですが、
それを不具合として修正したいというならそれもアリだと思います。

バッチでも関数でも同じですが、呼出の引数は最小限とするのが望ましいので、
既にある引数と同じ意味の引数を追加する変更は「筋が通らない」ように思います。

2022-01-08 13:08 UTC, dep5 commented on tools/find-tools.bat
>      )
:find_msbuild_legacyについてですが
改めて見直してみたところ、将来のVisual Studioのバージョンで
Msbuild.exeのパスが変更された場合などを想定しているように思います

2022-01-08 13:34 UTC, kazasaku commented
> find-tools.batでVSVERSIONを受け入れるのはARG_VSVERSIONだけなのに、
> targetsファイルで指定しているのは NUM_VSVERSIONなので
> 問題が起きているのではないでしょうか？ 

繰り返しになりますが、`ARG_VSVERSION`は`NUM_VSVERSION`と持っている値の意味が違っています。
`NUM_VSVERSION`はVisual Studioのバージョン番号を保持するのに対して、`ARG_VSVERSION`は製品名や英単語が入ります。
| 想定している使い方 | ARG_VSVERSION | NUM_VSVERSION                        |
| --------------------- | ------------- | ------------------------------------ |
| find-tools.bat        | (未定義)      | 利用できる最新のVSバージョン(例: 16) |
| find-tools.bat clear  | (未定義)      | 現在の値を初期化                             |
| find-tools.bat latest | latest        | 利用できる最新のVSバージョン(例: 16) |
| find-tools.bat 2015   | 2015          | 15                                   |
| find-tools.bat 2019   | 2019          | 16                                   |
| find-tools.bat 2022   | 2022          | 17                                   |
| find-tools.bat 15     | 15            | 15                                   |
| find-tools.bat 16     | 16            | 16                                   |
| find-tools.bat 17     | 17            | 17                                   |

ユーザー側の指定の揺れを吸収しつつ値を検証し、正しい値をNUM_VSVERSIONとして設定する仕組みです。
VSのバージョン**番号**が必要な場面で`ARG_VSVERSION`を参照した結果が「latest」だったときはどうすればいいんですかね。

2022-01-08 13:36 UTC, dep5 commented
一貫性のあるロジック、ですかね？
私にはとてもよく考えられてるように思います。

find-tools.batを触らないことにしたのでそれ以外を編集することにします。

https://github.com/dep5/sakura/blob/0dd4391776be5530ef4d0a66e8279ace744d3dd6/tests/compiletests.run.cmd#L8

ここ以外に出てこないので一時的なテストコードと考えて削除しています。

2022-01-08 13:37 UTC, kazasaku requested changes

2022-01-08 13:37 UTC, kazasaku commented on tests/compiletests.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
（再掲）不要な対応です。

2022-01-08 13:41 UTC, kazasaku commented on tests/compiletests.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
不満はたくさん残りますが、これを撤回していただければapproveすることにします。
…が、今後はいきなりPRを出したりせず、issueを立ててください。

2022-01-08 13:49 UTC, kazasaku commented
2022の導入には反対しませんが、この形で対応しても2022でビルドできることは検証できませんのでご注意ください。
（過去に2017ではビルドできるが2019ではできない、といった事例がありました。）

今月中ごろを目標にいったんCI対応の実験PRを出す予定ではいますのでよろしくお願いします。

2022-01-08 13:54 UTC, kazasaku requested changes

2022-01-08 13:54 UTC, kazasaku commented on tests/googletest.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
同上。

2022-01-08 14:06 UTC, kazasaku commented
> ・compiletest.targetsのバグ（？）を直したい
> ・find-tools.batのバグを直したい

僕は「そんなバグは存在しない」という認識です。

2022-01-08 14:22 UTC, dep5 commented
kazasaku さん

set ARG_VSVERSION=latest
build-all.bat Win32 Release
コマンドラインでこう打つと、まずbuild-sln.bat の中で
tests\compiletests.targets よりも先にfind-tools.batが呼ばれます。
ここではlatestが渡り最新のバージョンで各種変数が設定されます

つぎに
tests\compiletests.targets が呼ばれ、ARG_VSVERSIONが数字で設定され直すと思います。
各種変数が設定済みなので、find-tools.batは動きません。

しかし、ARG_VSVERSIONがlatestから実際のバージョンに変わってしまっていますね。
わたしは、それで問題ないと判断しました。

```
<ARG_VSVERSION Condition="'$(ARG_VSVERSION)' == ''">
	<SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
</ARG_VSVERSION>
```
まだテストしてませんが、このような指定にする必要があるかもしれないです。


kazasakuさんはVS2019/VS2022が混在した環境をお持ちなんですよね？
tests\compiletests.targetsの
```
    <SetEnv name="NUM_VSVERSION" value="$(VsVersion)" prefix="false" />
```
の行を
```
    <SetEnv name="NUM_VSVERSION" value="16" prefix="false" />
    <SetEnv name="NUM_VSVERSION" value="17" prefix="false" />
    <SetEnv name="ARG_VSVERSION" value="16" prefix="false" />
    <SetEnv name="ARG_VSVERSION" value="17" prefix="false" />
```
と書き換えながらテストしてみてもらえませんか？
うまくいかなかったら、IDE上でやってみてください。
NUM_VSVERSIONではビルドツールが変化せず
ARG_VSVERSIONなら指定したバージョンになると思うのですが・・・

表にしてくださった
想定している使い方	ARG_VSVERSION	NUM_VSVERSION
find-tools.bat 	(未定義) 	利用できる最新のVSバージョン(例: 16)
ですが、正しくは
find-tools.bat 	(未定義) 	15が入っていれば15、15が無ければ利用できる最新のVSバージョン(例: 16)
となります(表が書けなくてすいません)
これに対応するための変更です
IDEではコマンドラインのように気軽に環境変数が設定できませんので。

2022-01-08 14:49 UTC, berryzplus commented on tests/compiletests.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
このファイルが実行されるのは、常にvisual studioの「中」です。
ここから呼ばれたバッチでは「呼出元と同じバージョンのvisual studio」を使います。
ユーザーの利便性のための「2022」に対応する必要はないので「追加不要」ということになります。

2022-01-08 14:50 UTC, berryzplus commented
結論として不具合修正でなくなるなら、
PR本文の「不具合修正」を外してほしいです。

2022-01-08 14:59 UTC, berryzplus commented
targets経由で呼ばれるバッチの仕組み
　・起動中のvisual studioのバージョン番号を取得
　・ビルドのサブプロセスから参照できるように環境変数を追加
　　（システムの環境変数には影響しないので、新しい環境変数ブロックが作られていると考えられます。）
　・サブプロセスとしてバッチファイルを実行

visual studioの中で、起動中のvisual studioのバージョンが取れないケースはありえない想定です。
理屈は分かりませんが、msbuild経由で実行した場合も同じ挙動になるようです。

2022-01-08 15:09 UTC, kazasaku commented on tools/find-tools.bat
>      )
`find_msbuild_legacy`まで到達するシチュエーションが本当にありうるかは不明です。
.vsconfigに書いたコンポーネントのインストールが済んでいることを前提とすれば到達しなさそう。
だとしたら変更しなくても支障ないかも。

2022-01-08 15:13 UTC, kazasaku commented
> 正しくは
> find-tools.bat (未定義) 15が入っていれば15、15が無ければ利用できる最新のVSバージョン(例: 16)
> となります(表が書けなくてすいません)

👌 訂正しました。

2022-01-09 10:19 UTC, berryzplus requested changes
現状では対応してないvs2022に対応させたいのか、
既存バッチの不具合（？）を修正したいのかが分からないです。

ざっとみた感じ、修正内容が誤っているように見えています。

正しいと思われる修正を用意したほうがよいでしょうか？

2022-01-09 10:19 UTC, berryzplus commented on tests/compiletests.run.cmd
> -
これを削ってよいのか疑問です。

本来 [16,17) のように使うための変数と考えられるので、
変数が利用されていないとすれば、find-tools.batが壊れていると思います。

2022-01-09 10:19 UTC, berryzplus commented on tests/compiletests.targets
> +    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
ここを修正する必要がある　＝　find-tools.batに不具合がある　です。
伝わらないんでしょうか？

NUM_VSVERSION　＝　visual studioのバージョン番号が入ります。
ARG_VSVERSION　＝　ユーザーが手入力でfind-tools.batを利用するときの利便性を図る目的で「2019」などの厳密にはバージョンではない値を介して NUM_VSVERSION を「間接指定する」ための引数です。ここに指定した値と、最終的に利用される NUM_VSVERSION は異なる場合があります。

指定したバージョンとズレてしまっては困るので、ARG_VSVERSIONを指定すべきではないと思います。

2022-01-09 10:34 UTC, berryzplus commented
試してみましたところ、find-tools.batに不具合があるように見えます。

vs2017、vs2019、vs2022がインストールされた端末で、
以下を入力した場合はvs2019のMsBuildが選択される想定ですが、vs2017のものが選択されています。

```cmd
find-tools.bat clear
set NUM_VSVERSION=16
find-tools.bat
```

先にこの不具合を修正したほうがわかりやすいのではないかと思います。

2022-01-09 10:50 UTC, berryzplus commented on tests/compiletests.run.cmd
> -
調査結果：　この一文は要りません。

PRの趣旨とは無関係なので、対応からは外すのがベターと思います。
コミットが分かれているならPRに混ぜてもよいはと思います。

2022-01-09 11:25 UTC, dep5 commented on tests/compiletests.run.cmd
> -
NUM_VSVERSION_NEXTはソースをGrepしてみたところ、find-tools.bat内とここでだけ使用されています。
find-tools.batのあとで使われているのでテストコードのように思えるのですが、どうでしょうか？
コミットは分けたほうがよいですね・・・

2022-01-09 11:51 UTC, berryzplus commented
find-tools.batの不具合修正をしてみました。
https://github.com/berryzplus/sakura/tree/feature/fix_find-tools_bat

やりとりするのが面倒くさいのでPRは出しません。
流用してもいいし、スルーして進めるのも自由です。

2022-01-09 11:59 UTC, dep5 commented
berryzplus さん

> set NUM_VSVERSION=16

ARG_VSVERSIONを使う必要があります
ARG_VSVERSIONを設定しないと
find-tools.batの中で、まずNUM_VSVERSION=15となります。

> PR本文の「不具合修正」を外してほしいです。

不具合とはプログラム本体の動作のことなのですか？
だとしたら間違えました。

vcx-props/vcxcompat.props を修正しないとVS2022を使うことができません。
これは同意いただけてると思います。

調べた結果、問題の原因はARG_VSVERSIONとNUM_VSVERSIONの混用にあると思います
NUM_VSVERSIONは「find-tools.bat内でのみ」使われている変数で
外からは設定できません。
NUM_VSVERSION は「直接指定できません」

find-tools.batの挙動をNUM_VSVERSIONも指定できるように変更する場合、
ARG_VSVERSIONとNUM_VSVERSIONのどちらを優先すべきかという問題もあります。

どちらでも設定できるとなったら、どちらで設定するのが正解ですか？
一方ARG_VSVERSIONは15,16,17といったバージョンでも問題なく受け入れます。

わたしはfind-tools.batに渡すにはARG_VSVERSIONに一本化すべきと思います。

NUM_VSVERSIONでソースをGrepすると使用されているのは
find-tools.bat以外では
compiletests.targets
compiletests.run.cmd
googletest.targets
の3つのみで、該当の部分は

> ビルドのサブプロセスから参照できるように環境変数を追加
> 　　（システムの環境変数には影響しないので、新しい環境変数ブロックが作られていると考えられます。）

なので、コマンドラインで
set ARG_VSVERSION=latest
ビルド後に%ARG_VSVERSION%でチェックしてみてもlatestのままでした。

2022-01-09 12:30 UTC, kazasaku commented on tests/compiletests.run.cmd
> -
find-tools.batの`NUM_VSVERSION_NEXT`はendlocalより前にあるので外には出てこないはずです。
find-tools.batから制御が戻った時にはもうなくなっています。

つまりこのコードは要りません。
…が、VS2022対応とは無関係な変更になります。

2022-01-09 12:36 UTC, berryzplus commented
> ARG_VSVERSIONを設定しないと
> find-tools.batの中で、まずNUM_VSVERSION=15となります。

自分はそれを「find-tools.bat の不具合である」と解釈しました。

> > PR本文の「不具合修正」を外してほしいです。
> 
> 不具合とはプログラム本体の動作のことなのですか？

違います。バッチの不具合も「不具合修正」としてよいと思います。
「find-tools.batに不具合はない」という話が出ていたので書いたコメントです。

> vcx-props/vcxcompat.props を修正しないとVS2022を使うことができません。

「vs2022を使えるようにする」が目的なら、その修正は必須です。
自分が提示したのは「find-tools.batの不具合を修正する」なので、その修正は含めない形としました。

> NUM_VSVERSIONは「find-tools.bat内でのみ」使われている変数で
> 外からは設定できません。

ARG_VSVERSION はバッチに与える引数なので、厳密には環境変数じゃありません。
NUM_VSVERSION は環境変数なので、setコマンドなどを使って呼び出し前に定義できます。ゆえに「外から設定できません」は認識違いだと思います。

ARG_VSVERSION　＝　find-tools.batに与えた第１引数の値が "clear" でない場合に、ローカルな環境変数として定義されるものです。（外部から指定できますが、名前付き引数として指定できるわけじゃないです。）
NUM_VSVERSIONを間接的に指定するためのものです。
バージョン番号しか受け付けないNUM_VSVERSIONだけだと使い勝手がわるかろう、という経緯で用意されたものです。

> わたしはfind-tools.batに渡すにはARG_VSVERSIONに一本化すべきと思います。

NUM_VSVERSIONとは異なり、ARG_VSVERSIONはバッチ引数に付けるローカルな名前なので、
find-tools.batの外部で利用すべきではないように思います。


まぁ結局、vs2022を使えるようにしたいのか、compiletest.targetsのバグ（？）を直したいのかどっちやねん？という感じになります。こういう言い方をしたらあかんのかも知れませんが。

2022-01-09 12:41 UTC, berryzplus commented
書き洩らし。

> なので、コマンドラインで
> set ARG_VSVERSION=latest
> ビルド後に%ARG_VSVERSION%でチェックしてみてもlatestのままでした。

ARG_VSVERSIONはNUM_VSVERSIONを指定するためのものなので、
設定したlatestに対応する値をNUM_VSVERSIONに設定して終わりだと思います。
その点（＝ARG_VSVERSIONがlatestに相当するバージョン番号に変更されない）については不具合じゃないように思います。

2022-01-09 12:51 UTC, dep5 commented
VS2017と2022の入った環境で
コマンドラインでのビルドもテストしてみました。
環境変数をリセットするために毎回新しいコマンドプロンプトを立ち上げる必要があります。
作業フォルダbuildの削除も必要かもしれません。

または
.....\tools\find-tools.bat clear
set ARG_VSVERSION=
をテスト前に毎回実行します。

compiletests.run.cmdに
echo test=%test1%
echo ARG_VSVERSION=%ARG_VSVERSION%
と追記し、
ビルド後に次のチェックもしました。
echo CMD_ARG_VSVERSION=%ARG_VSVERSION%

compiletests.targetsの
    <SetEnv name="NUM_VSVERSION" value="$(VsVersion)" prefix="false" />
の部分を以下のように書き換えながらチェックします

ARG_VSVERSIONが未定義の場合のみ設定するようにする

    <SetEnv name="test1" value="$(ARG_VSVERSION)" prefix="false" />
    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" />
結果:
test=latest
ARG_VSVERSION=17
CMD_ARG_VSVERSION=latest


    <SetEnv name="test1" value="$(ARG_VSVERSION)" prefix="false" />
    <SetEnv name="ARG_VSVERSION" value="$(VsVersion)" prefix="false" Condition=" '$(ARG_VSVERSION)' == '' " />
結果:
test=latest
ARG_VSVERSION=latest
CMD_ARG_VSVERSION=latest

以上から、コマンドプロンプトで環境変数ARG_VSVERSIONを設定したあと、
compiletests.run.cmdで一度書き換えられるが、compiletests.run.cmdが終わったら
もとの値に戻っているので、それ以降のコードには影響がないようです
しかし、念のため、ARG_VSVERSIONに何か設定されていないか調べることにしました。
空の場合のみ、設定します。
ARG_VSVERSIONに値が設定されていれば変更することはありません。

2022-01-09 13:23 UTC, dep5 commented
パッチありがとうございます。
berryzplus さんの変更はARG_VSVERSIONを優先するようですね。

リンクがうまくできなくてすいませんが
build.mdの97行目

> set ARG_VSVERSION=16

tools\find-tools.mdの44行目

> 環境変数 ```ARG_VSVERSION``` の値でビルドに使用するバージョンを切り替えられる。

などをご覧ください

ARG_VSVERSIONは引数以外の使い方もできますし、それを想定しています。


> NUM_VSVERSION は環境変数なので

$(VisualStudioVersion)と間違えてませんか？

https://github.com/sakura-editor/sakura/blob/25281cdf5d5be0174ca4be0923cbee717dc77ba5/tests/compiletests.targets#L16
$(VsVersion)は$(VisualStudioVersion)を整数に切り詰めてつくったこの場限りのプロパティです。

kazasakuさんもおっしゃったように
tools\find-tools.bat 内で最終的にNUM_VSVERSIONも環境変数として設定されてはいますが、ソースGrepではここ以外で呼び出されないように思うのですが？（つまりfind-tools.bat でしか利用していない）

これを対応しないと、VS2022のCMAKEが使えないのでVS2022対応の一環と思っています。

2022-01-09 13:26 UTC, kazasaku commented
> > ARG_VSVERSIONを設定しないと
> > find-tools.batの中で、まずNUM_VSVERSION=15となります。
> 
> 自分はそれを「find-tools.bat の不具合である」と解釈しました。
> 

「引数指定がない場合に無条件でVS2017を仮選択する」のはおかしいということかな？
どのみちこの動作もVS2017対応を廃止すると合理性がなくなるので変えてもよいかもしれませんね。

find-tools.bat の話はVS2022対応とは関係ない話だと思うので、issueとして切り出しておきます。

2022-01-09 14:22 UTC, kazasaku commented
> kazasakuさんもおっしゃったように
> tools\find-tools.bat 内で最終的にNUM_VSVERSIONも環境変数として設定されてはいますが、ソースGrepではここ以外で呼び出されないように思うのですが？（つまりfind-tools.bat でしか利用していない）

そう言った覚えはないです😢
- `NUM_VSVERSION` は（現状では）find-tools.batで設定される環境変数です
- `NUM_VSVERSION_NEXT` はfind-tools.batの中でのみ使われる一時変数です
   - compiletests.run.cmd に**たまたま**同じ名前で未使用の一時変数が定義されていた（ #1758 で消える）

2022-01-09 14:34 UTC, kazasaku commented
> find-tools.bat の話はVS2022対応とは関係ない話だと思うので、issueとして切り出しておきます。

find-tools.batに関する疑問などをまとめ、 #1759 として投稿しました。

2022-01-09 14:39 UTC, dep5 commented
kazasakuさん

> kazasakuさんもおっしゃったように
> tools\find-tools.bat 内で最終的にNUM_VSVERSIONも環境変数として設定されてはいます

で切れていました。すいません

https://github.com/sakura-editor/sakura/pull/1755#issuecomment-1005755185
に貼ってもらったコードについてでした。
たまたまではなく動作テスト用のコピーのように思いますが
消えるなら問題ないですね。

2022-01-09 14:44 UTC, berryzplus commented
指摘していただいた部分だと思うのですが、ドキュメントが変な感じですね。
https://github.com/sakura-editor/sakura/blob/25281cdf5d5be0174ca4be0923cbee717dc77ba5/tools/find-tools.md#L44

ドキュメントに「環境変数」と書くとグローバルな環境変数と混同してしまうのでよくないと思います。
実態としては、「find-tools.batの実行引数に特定の値を指定するとビルドに使用するバージョンを指定できます。」です。
構造として「環境変数」として利用することも可能と思いますが、そうだとすると変数名がおかしい気がします。

https://github.com/sakura-editor/sakura/blob/25281cdf5d5be0174ca4be0923cbee717dc77ba5/tools/find-tools.bat#L23-L25
バッチファイルの記法で `%~1` は「最初の引数から引用符を取り除いた文字列」を意味します。
[shiftコマンド](https://docs.microsoft.com/ja-jp/windows-server/administration/windows-commands/shift)とか、知らないことにしたほうが説明しやすい概念もあったりなかったり。。。

2022-01-09 15:35 UTC, dep5 commented
mdのファイルはリンクできないのかと思ったのですが、できるのですね。

グローバルな環境変数とはコントロールパネルで設定する項目のことですか？
setで設定できるのは環境変数だと思います。
[set (環境変数)](https://docs.microsoft.com/ja-jp/windows-server/administration/windows-commands/set_1)
システム環境変数やユーザー環境変数ではなくプロセス限定の環境変数ですね。

2022-01-09 15:48 UTC, berryzplus commented
> mdのファイルはリンクできないのかと思ったのですが、できるのですね。

表示したプレビューページの上の方に `<>` マークがあるのでクリックすると普通のソースコード表示になります。
で、いつものように行番号をクリックして Copy permalink したあと、
```https://github.com/sakura-editor/sakura/blob/25281cdf5d5be0174ca4be0923cbee717dc77ba5/tools/find-tools.md?plain=1#L5```のようなURLから```?plain=1```を削除したら貼れました

2022-01-10 13:19 UTC, dep5 commented
https://github.com/sakura-editor/sakura/blob/138ec8e53ad4b1d5c8b06d373be9130bc01658b8/build.md#L1-L2

できました。?も消すのですね。ありがとうございます

2022-01-10 13:57 UTC, berryzplus commented
force-pushしてしまったのですが、こんな感じになりました。
https://github.com/berryzplus/sakura/commits/feature/fix_find-tools_bat

vs2022対応とは無関係なコミットを7つも積んでいます。
個々のコミットがPRに相当する変更内容なので、想定通り「ボチボチ大変」っぽいです。

2022-01-10 14:49 UTC, closed without merging