表示スケールに合わせて拡大する処理を色々と追加
sakura-editor/sakura pull request #1762
Opened 2022-01-10 13:28 UTC by beru

- ミニマップのウィンドウ横幅とフォントサイズを表示スケールに合わせて拡大する処理を追加
- ミニマップのフォントサイズのデフォルト値を -1 から -2 に変更
- ルーラーの高さ、ルーラーとテキストの隙間、行番号とテキストの隙間を表示スケールに合わせて拡大する処理を追加
- 文字の間隔と行の間隔を表示スケールに合わせて拡大する処理を追加

#  PR の目的

ディスプレイの表示スケールに合わせて見た目がスケールするようにする。

##  カテゴリ

- 仕様変更

##  PR の背景

##  PR のメリット

表示スケールに変更した際に見た目がスケールするので設定値を変更する必要がなくなる。

##  PR のデメリット (トレードオフとかあれば)

dot by dot のピクセル単位では設定出来なくなるので、表示スケールが大きい数値の時にピクセル単位で細かく調整する事が出来なくなります。

##  仕様・動作説明

変更前はディスプレイの表示スケールを掛けないピクセル単位でした。

##  PR の影響範囲

項目に関連する画面の見た目

##  テスト内容

様々な表示スケールで画面の見た目を確認

##  関連 issue, PR

##  参考資料

2022-01-10 14:24 UTC, berryzplus commented
CIのビルドエラーに見えているものは、LeProcのインストール失敗によるものなのでスルーしてよいと思います。

2022-01-10 15:05 UTC, beru commented
> この制限外します？
> 
> https://github.com/sakura-editor/sakura/blob/138ec8e53ad4b1d5c8b06d373be9130bc01658b8/sakura/sakura.vcxproj#L87
> 
> _WIN32_WINNTを_WIN32_WINNT_WIN7にしたままだと、 Windows 10の[GetSystemMetricsForDpi](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetricsfordpi)を利用できず、 HighDPI対応を2回やらナイトいけなくなるような気がします。

定かでは無いんですが、サクラエディタの対応OSにWindows 8.1を今はまだ入れていたような気がします。検索してみたところWindows 8.1の延長サポートは2023年1月10日に終了となるようなので、それを過ぎたらさすがに切り捨ててWindows10以降に限定して良いと思います。

高DPI対応では `GetDpiForWindow` を使うとPer-Monitor DPI対応も行いやすいですね。Per-monitor DPI対応しようとするとソースコードの色々な箇所を書き換えないといけなくて大変なので行われるか不明ですが…。

`GetSystemMetricsForDpi` が使えないとHighDPI対応を2回やらないといけなくなる、という理由は理解出来ていません。Google検索すると #519 がヒットしたので読んでみました。

しかしなんかうまくコード書いてまとめないとHighDPI対応の為にWindowsAPIをそこらじゅうで呼び出しまくる事になってしまいますね。既にごちゃごちゃしてるのに輪をかけてとかいうと首を絞められるかも。。

2022-01-10 15:45 UTC, beru commented
> 自分も良く分かってなかったんですが、公式サイト（？）に Windows 10以降 と書いてありました。 https://sakura-editor.github.io/
> なので、Windows 8.1対応は考慮不要なはずです。 現状のプロジェクト設定だとwin7準拠コードしか書けませんけれども。

記憶が正しければ文章（`Ver. 2.4.0.0 以降のバージョンは MS Windows 10 で動作します。`）をそのように書いたのは自分だったような気がします。Windows 8.1の記載を省略したのは記載を簡潔にする為だったか書くのが面倒くさかったのか、まぁ確信犯というか切り捨てたいバイアスが働いたのかもしれません。

ただ時間が経過してもうみんなWindows 10かWindows 11(自分はまだ未使用)を使っているだろうし、Windows 8.1は切り捨てても良いんじゃないかとも思いますが、

- 今から1年後の2023/01/10に延長サポートが過ぎるまでは切り捨てては駄目だ派
- それが過ぎても切り捨てては駄目だ派

の意見が強ければ今のままでしょうか…。

2022-01-11 00:42 UTC, berryzplus commented
> GetSystemMetricsForDpi が使えないとHighDPI対応を2回やらないといけなくなる、という理由は理解出来ていません。Google検索すると #519 がヒットしたので読んでみました。

システムDPI対応で1回、PerMonitorV2対応で2回です。

現状ではシステムDPI対応も完了していなくって、
このPRの対応もシステムDPI対応にあたると思います。

2022-01-11 12:25 UTC, beru commented
> システムDPI対応で1回、PerMonitorV2対応で2回です。
> 
> 現状ではシステムDPI対応も完了していなくって、 このPRの対応もシステムDPI対応にあたると思います。

なるほど、それで2回という事だったんですね。`GetSystemMetrics` と比較して `GetSystemMetricsForDpi` は `dpi` 引数が追加されていて、Per-Monitor DPI対応をする場合にこのAPIを使うと。文章の背後の意図が読めてませんでした。

一足飛びに対応するか、2回に分けて対応するのかに特にこだわりはないです。Per-Monitor DPI対応をするとなると変更量が増えるので対応に時間は掛かりますね。

個人的にはWindows 8.1を切り捨てても構わないと思います。とはいえ `_WIN32_WINNT=_WIN32_WINNT_WIN10` に変更するPRを出してそれがすんなりマージされるかは…何事もやってみないと分からないですね。

2022-01-12 10:24 UTC, berryzplus commented
動作確認して問題なければ入れていいんじゃないかと思います。

2022-01-13 04:01 UTC, berryzplus requested changes
表示確認はできないのでコメント付けるつもりなかったんですが、コードチェックしてみました。

根拠不明なベタ書き定数を1件、誤記と思われるDPI変換を2件見つけました。
妥当な理由があれば修正要求は取り下げます。

2022-01-13 04:06 UTC, berryzplus commented on sakura_core/view/figures/CFigure_ZenSpace.cpp
> +			rcZenSp.SetSize(dx[0]- DpiScaleX(pcView->m_pcEditDoc->m_cDocType.GetDocumentAttribute().m_nColumnSpace),
`dx[0]` にはGDIが算出した文字幅(px単位)が入ると考えられるので、もしかしたら正しいかも知れないです。

2022-01-13 04:35 UTC, berryzplus commented
付けるつもりなかったのは、レビューですね・・・

2022-01-13 15:27 UTC, beru commented on sakura_core/env/CShareData.cpp
> +			sWindow.m_nMiniMapFontSize = -2;
動作確認して決めた値です。

ミニマップの幅を表示スケールに合わせて調整するようにしましたが、動作確認してみるとここの値が -1 だとミニマップのフォントがあまり大きくならないんです。-2 にすると（表示スケールに合わせてそこから拡大しますが）ちょうどよい大きさになるのでデフォルト値を変更しました。

なおこのフォントサイズの値は設定ファイルに記録されてサクラエディタの設定画面では変更が出来ません。なのでここのデフォルト値を変更しても既に設定ファイルに従来の値(-1)が書かれている場合は手動で変更したりしない限りそのままになってしまいます。

2022-01-13 15:28 UTC, beru commented on sakura_core/view/CRuler.cpp
> +		lf.lfHeight			= 1 - DpiScaleY(pCommon->m_sWindow.m_nRulerHeight);	//	2002/05/13 ai
元のコードが `1 - n` している理由は自分も分かっていません。どちらの記述が良いのかは後で動作確認してみます。

2022-01-13 15:28 UTC, beru commented on sakura_core/view/figures/CFigure_ZenSpace.cpp
> +			rcZenSp.SetSize(dx[0]- DpiScaleX(pcView->m_pcEditDoc->m_cDocType.GetDocumentAttribute().m_nColumnSpace),
そうだったんですね、指摘ありがとうございます。後でデバッグして確かめてみます。

2022-01-14 00:45 UTC, berryzplus commented on sakura_core/env/CShareData.cpp
> +			sWindow.m_nMiniMapFontSize = -2;
動作確認で必要と考えられたので修正、ですね。了解です。

設定ファイルの値なのでやや微妙なんですけど、元々設定していた「-1」の意図は「高さ1px」じゃなくて「指定できる最小サイズ」なのかも知れないと思いました。つまり「-cyBorder」なんじゃないかと。

```const auto cyBorder = GetSystemMetrics(SM_CYBORDER);```

DPI考慮なしのときは保存していた設定を、DPI対応のために削る、というのはアリな気がします。

今回の対応に含めるべきか？と考えるとNOだと思うので、ここは「妥当な根拠が提示されたので問題なし」と考えてよさそうに思います。

2022-01-14 00:53 UTC, berryzplus commented on sakura_core/view/CRuler.cpp
> +		lf.lfHeight			= 1 - DpiScaleY(pCommon->m_sWindow.m_nRulerHeight);	//	2002/05/13 ai
お願いします。

`LOGFONT.lfHeight`に負数を指定してCreateFontIndirectすると、指定した高さのフォントが使われる、という仕様があるはずです。正数を指定した場合は、指定した値に近似するサイズが使われる（つまり、指定したサイズと一致しないかもしれない）仕様です。

`1 - n` はそそらく、
・指定したサイズより少し小さいフォント
を意味していると考えられます。
たぶん、2より小さい値が設定されることは想定してないっす。

なんか前に、ルーラーって消せなくていいんでしたっけ？というやりとりがあったようななかったような・・・。

2022-01-14 00:54 UTC, berryzplus commented on sakura_core/view/figures/CFigure_ZenSpace.cpp
> +			rcZenSp.SetSize(dx[0]- DpiScaleX(pcView->m_pcEditDoc->m_cDocType.GetDocumentAttribute().m_nColumnSpace),
ちゃんと見れてないので正しいかもです。
変数名とか見ると「本当か？」とも思いますが・・・。

2022-01-14 04:13 UTC, k-takata commented on sakura_core/view/CRuler.cpp
> +		lf.lfHeight			= 1 - DpiScaleY(pCommon->m_sWindow.m_nRulerHeight);	//	2002/05/13 ai
負数は文字の高さ、正数はセルの高さですね。
正数だとセル内の余白の分、文字の高さが小さくなります。

2022-01-18 03:11 UTC, k-takata commented
数日前にVimのPerMonitorV2対応を行いました。 https://github.com/vim/vim/commit/c81e9bf4f07d350b860b934aa6bf0c2a7c91d07e
sakuraエディタのPerMonitorV2対応を行う際には何らかのアドバイスができるかもしれません。

2022-01-21 04:16 UTC, berryzplus commented
残1件です。

`1 - n`で`n`だけDPI対応してるが、`1 - n`をDPI対応しなくてよいか？
納得できる理由があれば変更要求は取り下げます。

2022-03-20 12:53 UTC, berryzplus commented
ステータス変わってないように見えました。

request changesで残1件です。
https://github.com/sakura-editor/sakura/pull/1762#discussion_r783612979

元が`1 - n`のコードで`n`だけDPI対応してるのがなんで？という話です。
たぶん`1 - n`全体をDPI対応しないといかんはず。。。

2022-03-20 14:35 UTC, beru commented
> ステータス変わってないように見えました。
> 
> request changesで残1件です。 [#1762 (comment)](https://github.com/sakura-editor/sakura/pull/1762#discussion_r783612979)
> 
> 元が`1 - n`のコードで`n`だけDPI対応してるのがなんで？という話です。 たぶん`1 - n`全体をDPI対応しないといかんはず。。。

う、そういえば対応していませんでした。元の `1 - n` の計算の意味合いが良く分からなくてそのまま引き延ばして良いのか謎です。まぁ動かして結果を見て確認するしかなさそうですね。

2022-03-21 02:59 UTC, berryzplus commented
`1 - n` で負数にした値を指定する意味は [takataさんコメント](https://github.com/sakura-editor/sakura/pull/1762#discussion_r784496226) を参照です。
`n`だけ対応すると、高解像度のときのフォントが少し大きくなります。

2022-03-21 04:03 UTC, beru commented
> `1 - n` で負数にした値を指定する意味は [takataさんコメント](https://github.com/sakura-editor/sakura/pull/1762#discussion_r784496226) を参照です。 `n`だけ対応すると、高解像度のときのフォントが少し大きくなります。

https://github.com/sakura-editor/sakura/pull/1762#discussion_r784432820 のberryzplusさんのコメントとtakataさんコメントに答えが書いてありそうですね。

> 1 - n はおそらく、
・指定したサイズより少し小さいフォント
を意味していると考えられます。
たぶん、2より小さい値が設定されることは想定してないっす。

2より小さい値というのは正の数だと1や0ですが、1だと0になって0だと-1になるのでサイズ的には逆転しそうですが指定されないだろうから問題ないという事ですね。了解しました。

2022-03-21 04:40 UTC, beru commented
2より小さい値が設定されないようにUI側でチェックが入っていました。

https://github.com/sakura-editor/sakura/blob/e67c8ce03f808ae940689373a82e01d6bc066043/sakura_core/_main/global.h#L101

定数 `IDC_SPIN_nRulerHeight_MIN` の値が 2 で、`CPropWin` の実装でそれを下回らないようにしてました。

2022-03-21 05:28 UTC, berryzplus submitted a review, later dismissed
システムDPI対応として問題なさそうに思います。

2022-03-21 05:41 UTC, berryzplus approved these changes
GHAのSonarCloudビルドが失敗していますが、PRに起因する問題ではなさそうなのでスルーします。

2022-03-21 09:40 UTC, beru commented
レビューありがとうございました。Mergeします。
もし後で問題が見つかったら別PRで修正します。

2022-03-21 09:40 UTC, merged

2022-03-21 10:45 UTC, beru commented
`1 - n` の記述ですが、 `-(n - 1)` と同じ結果になるので、

- berryzplusさんコメント : 指定したサイズより少し小さいフォント
- takataさんコメント : 負数は文字の高さ、正数はセルの高さ、正数だとセル内の余白の分、文字の高さが小さくなる

を展開した記述と捉える事が出来そうです。