複数のVisual Studioを入れたときの問題に対応
sakura-editor/sakura pull request #1806
Opened 2022-02-21 14:19 UTC by dep5

#  PR の目的

複数のVisual Studioをインストールしている場合
ビルド時に違うバージョンのcmakeなどが選択される問題を修正します

##  カテゴリ

- 不具合修正
- ビルド関連
  - ビルド手順
  - ローカルビルド

##  PR の背景

tools/find-tools.batの探索順が変更になり
NUM_VSVERSION -> VS2022 -> VS2019 -> VS2017
このような優先順で選ばれるようになりました
複数インストールしている場合、
下位のバージョンを使うにはNUM_VSVERSIONを設定する必要があります。
IDEでは使用中のバージョンを (targetsファイルを使って) 環境変数NUM_VSVERSIONに設定する必要があります。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

呼び出し順を変えるので何か不具合があるかもしれません。

##  仕様・動作説明

例としてVS2022とVS2017をインストールした環境の話です。

１．
IDE/コマンドライン
Visual Studio 2017でビルドすると違うバージョンのツールが選択される
-> tools/find-tools.batでのNUM_VSVERSION_NEXTの設定忘れです。

２．
IDEのみ
sakura_core\githash.h が存在しない場合
Visual Studio 2017 IDEでビルドすると違うバージョンのツールが選択される。
-> NUM_VSVERSIONを設定しないままtools/find-tools.batが呼ばれている。

sakura\githash.targets に環境変数NUM_VSVERSIONを設定する方法と
sakura\sakura.vcxproj の呼び出し順でtests\compiletests.targets を優先させる方法があると思います。

依存関係が無ければ順を変えるほうが
環境変数NUM_VSVERSIONを設定する箇所を
tests\unittests\tests1.vcxproj - tests\googletest.targets - googletest.build.cmd
sakura\sakura.vcxproj - tests\compiletests.targets - compiletests.run.cmd
の二つに固定できるのでいいと思います。

##  PR の影響範囲

いくつかファイルの呼び出し先を追ってみた感じでは、依存関係が無いように思いましたが、どうでしょうか？

##  テスト内容

2つ以上インストールした最新でないほうのVSを起動し、ビルドを行う。
IDEのテストではsakura_core\githash.hを削除した状態でもテストする。

### テスト1

手順

##  関連 issue, PR

##  参考資料

2022-02-21 14:36 UTC, kazasaku commented
NUM_VSVERSIONの値は以下の記述により設定されています。
https://github.com/sakura-editor/sakura/blob/0c8db7496c87069c51b857da1af7904fcc22949e/tests/compiletests.targets#L20
https://github.com/sakura-editor/sakura/blob/0c8db7496c87069c51b857da1af7904fcc22949e/tests/googletest.targets#L38

2022-02-21 14:39 UTC, kazasaku commented
0c8db7496 をVisual Studio 2019 でビルドしたときのログ（抜粋）です。
```
4>------ ビルド開始: プロジェクト: tests1, 構成: Debug Win32 ------
4>ビルドの開始時の環境:
4>VisualStudioDir                = C:\Users\Kohki Akikaze\Documents\Visual Studio 2019
4>VisualStudioEdition            = Microsoft Visual Studio Community 2019
4>VisualStudioVersion            = 16.0
4>VSAPPIDDIR                     = C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
4>VSAPPIDNAME                    = devenv.exe
4>VSLANG                         = 1041
4>VSSKUEDITION                   = Community
4>find-tools.bat
4>|- CMD_GIT=C:\Program Files\Git\cmd\git.exe
4>|- CMD_7Z=C:\home\kazasaku\.local\bin\7z.exe
4>|- CMD_HHC=C:\Program Files (x86)\HTML Help Workshop\hhc.exe
4>|- CMD_ISCC=
4>|- CMD_CPPCHECK=C:\Program Files\Cppcheck\cppcheck.exe
4>|- CMD_DOXYGEN=
4>|- CMD_VSWHERE=C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
4>|- CMD_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
4>|- CMD_CMAKE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
4>|- CMD_NINJA=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe
4>|- CMD_LEPROC=C:\home\kazasaku\.local\bin\LEProc.exe
4>|- CMD_PYTHON=C:\Windows\py.exe
4>|- NUM_VSVERSION=16
4>|- CMAKE_G_PARAM=Visual Studio 16 2019
4>end
4>-- The C compiler identification is MSVC 19.29.30140.0
4>-- The CXX compiler identification is MSVC 19.29.30140.0
```
上記の通り、`CMD_CMAKE`にはVS2019付属のものが選択されています。

2022-02-21 14:50 UTC, kazasaku commented
> sakura\githash.targets に環境変数NUM_VSVERSIONを設定する

`githash.bat`における`find-tools.bat`の呼び出しは、 [Git for Windows](https://github.com/git-for-windows/git/) の所在確認が目的です。
CMake/MSBuildは同バッチファイル内では使われませんので、`NUM_VSVERSION`の指定は不要です。

2022-02-21 14:53 UTC, kazasaku commented
なお、混在環境におけるツール選択のトラブルは #1785 で対応済みです。

2022-02-21 15:31 UTC, kazasaku commented
> tools/find-tools.batでのNUM_VSVERSION_NEXTの設定忘れです。

#1785 よりも前から存在した漏れみたいなのでフォローアップ対応（ #1807 ）を行います。

2022-02-22 15:18 UTC, berryzplus reviewed
ぱっと見で良く分からなかったのでスルーしましたが、
修正内容はイケてそうに見えました。

2022-02-22 15:18 UTC, berryzplus commented on sakura/sakura.vcxproj
> -  <Import Project="..\tests\compiletests.targets" />
この行の修正根拠がわかりませんでした。

2022-02-23 13:42 UTC, dep5 commented
コメントありがとうございます。

いつもこのようにビルドしているのでテスト条件に書き忘れていました。
すいません。
https://github.com/sakura-editor/sakura/pull/1755

IDEのソリューションエクスプローラーで
sakuraプロジェクトを右クリックした場合に起きます。

find-tools.batを呼び出す前にその時必要な該当変数の確認がされています。
つまりサクラエディタ1回のビルドでfind-tools.batは1回しか呼び出されません。(変数が設定済みなので)
サクラエディタソース内でfind-tools.batで設定されるツールは
VSバージョンごとに用意されているもの(CMake)とそれ以外(git)があります。
Gitを設定する場合でもCMake用にNUM_VSVERSIONの指定が必要です。

2022-02-23 13:42 UTC, dep5 commented
kazasakuさん

1.sakura_core\githash.hを削除してから
2.VSを二つ以上入れた環境で最新版でないIDEからビルドした際の問題です。

2022と2019の混在環境でgithash.hを削除後のビルドログとみてよいですか？

ログ（抜粋）というのはログの冒頭部分という意味ですか？
それとも、今回のPRに関係ない部分を編集しているということですか？
というのも、
「ビルドの開始時の環境:
...
VSAPPIDDIR
VSAPPIDNAME
...
」
というのを見たことがない気がして…。
ログを全部確認したいという意味ではないです。

2022-02-23 13:51 UTC, dep5 commented on sakura/sakura.vcxproj
> -  <Import Project="..\tests\compiletests.targets" />
（IDEでは）記載順にtargetsが呼ばれるようなので
githashでfind-tools.batが呼ばれる前に
compiletestsでfind-tools.batを呼んでしまう、ということです。
これによってgithash.hの有無で動作が変わるのを防げます。

2022-02-23 14:41 UTC, dep5 commented
質問なのですが
#1807
同じ内容のPRを出すのはどういう意味があるのですか？
ドラフトを外せなくなるし、こちら側のコミットを修正するか、
PRを出し直さないといけなくなるので、困るのですが…。

2022-02-23 16:05 UTC, kazasaku commented
> 質問なのですが #1807 同じ内容のPRを出すのはどういう意味があるのですか？ ドラフトを外せなくなるし、こちら側のコミットを修正するか、 PRを出し直さないといけなくなるので、困るのですが…。

PRの目的が完全に異なっています。ゆえに別物です。

このPRの目的は「ビルド時に違うバージョンのcmakeなどが選択される問題を修正」ですが、僕が見る限りそのような事象が生じているようには見えません。
そのような事象が生じたときの完全なビルドログを公開してほしいです。

2022-02-23 16:15 UTC, berryzplus commented on sakura/sakura.vcxproj
> -  <Import Project="..\tests\compiletests.targets" />
何か大事なことを(ぼくが)読み取れて無さそうな気がします。

> githashでfind-tools.batが呼ばれる前に
> compiletestsでfind-tools.batを呼んでしまう、ということです。

compieltestsの記述準は、元々githashの後で、このPRで入れ替えようとしてるように見えています。

「githashで呼ぶ前にcompiletestsで呼んでしまうとマズい」と言ってるように見えますが、読んだらマズいなら変えなくてよいのではないかと思いました。何が抜けてるんでしょう・・・

> これによってgithash.hの有無で動作が変わるのを防げます。

`githash.h`を生成できない状況（≒ソースzipからのビルド）について、正しくビルドできる想定をするのは何か痴愚用な気がします。

2022-02-23 16:54 UTC, kazasaku commented
> find-tools.batを呼び出すタスクの実行時には SetEnv で NUM_VSVERSION を設定しておく必要がある

その見解に基づいてgithash.targetsに`SetEnv`を追加するだけ、という話だったら何も言わずにapproveしてましたね。
githash.targetsに`SetEnv`がないこと（＝ログ上ではバージョン選択ミスが起きているように見える）と、`NUM_VSVERSION_NEXT`の定義漏れは別の問題ですし。

2022-02-24 01:09 UTC, berryzplus commented
問題はいくつかありそうです。
* `find-tools.bat` を呼び出すバッチは、 `SetEnv` で visual studio のバージョンをバッチに渡してやる必要がある。
* ビルド工程で最初に実行される「find-tools.batを呼び出すタスク githash」に `SetEnv` の定義がない。
* `find-tools.bat` へのバージョン指定は、１回目の呼出以外は意味がない。
* `find-tools.bat` 内で cmake を検索するときに、未定義の環境変数 NUM_VSVERSION_NEXT を参照している。 #1807

問題が何で、原因が何で、の説明ができたら、直すだけです。
誰がやっても構わない修正だと思っています。
問題に気付けたのは @dep5 さんのおかげなので、このPRを修正して進めるのがベターだと思っています。

今回の原因に対して「ビルド順を変える」 は違う気がします。

find-tools.batを呼ぶには定義が必要なんだから対象タスク全部を修正するんじゃね？
　↓でも、使われるのは最初の定義だけじゃんね？
じゃあ、最初のタスクだけの修正にしようぜ！
　↓いま書いてある定義はどうする？
使われなくなるなら削っちゃおうぜ！

というような論理の組み立てになるので、
「誰がやっても同じ」にはならないですが、
「誰がやってもいい」と思います。

2022-02-24 01:49 UTC, berryzplus commented on sakura/sakura.vcxproj
> -  <Import Project="..\tests\compiletests.targets" />
ものすごく重要なことに思い当たりました。
ここの書き順を変えても、処理順には影響しないです。。。。

2022-02-24 08:49 UTC, kazasaku commented
ちょっと整理。

- #1755 でfind-tools.batでの`NUM_VSVERSION`環境変数の取り扱いについて問題が指摘される
  - 話題は #1759 に分離して検討。
- #1785 で、すでにあらかじめ設定した`NUM_VSVERSION`の値が無視されることに対して、ロジックの変更で対処
  - #1759 は解決されたとみなしてクローズ。
- もともと`NUM_VSVERSION`を設定していないgithash.targetsによる呼び出しは現時点でそのまま。
  - @dep5 さんは多分ここを気にしている。

このPRは次の点を指摘するものだと考えます。
- githash.targetsに`NUM_VSVERSION`の設定がないので、ログ上ではVS2022のツールを選択した旨が依然として出力されている。
  - つまり #1759 が未解決だと指摘している。
  - （ただし、githash.bat内ではそれらは使用されないので動作上の影響はないはず。）

ゆえに必要なのは「githash.targetsでも設定してから呼び出す」ようにして、 #1759 を閉じることだと思います。

`NUM_VSVERSION_NEXT`の件は #1785 よりも前からある問題であり、 #1759 とは無関係です。
（`git blame`した限りでは、CMakeの探索をfind-tools.batに追加したときの手落ちのようでした。）
なので同時対応しない方がわかりやすいと思います。

2022-02-24 13:06 UTC, dep5 commented
kazasakuさん
完全ログをありがとうございます

49行め
```
1>VisualStudioEdition            = Microsoft Visual Studio Community 2019
1>VisualStudioVersion            = 16.0
```
126行め
```
2>---- Make githash.h ----
2>find-tools.bat
2>|- CMD_MSBUILD=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
2>|- CMD_CMAKE=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
2>|- CMD_NINJA=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe

```
バージョンが違いますよね。これを修正したいのです。
githash.targetsの呼び出し順を変更して、修正できるか試してもらえませんか。

これも最近の変更とは関係ない以前からあるバグですのでまとめちゃってもいいかと思います。

2022-02-24 13:23 UTC, dep5 commented
berryzplusさん

> * ビルド工程で最初に実行される「find-tools.batを呼び出すタスク githash」に `SetEnv` の定義がない。

githashは一度作成されるとリビルドでは作り直されないようです。
ソースを展開するところから始めるようなケースでは sakura\githash.targets
修正しながらビルドをするようなケースでは tests\compiletests.targets
2つのルートを想定しないといけないので、この際順を変えてしまったらいいのでは、と思います。

順を変えることで不具合が起きたり、元の呼び出し順に何か理由があれば、githash.targetsの変更でも構いません。

2022-02-24 13:53 UTC, berryzplus commented on sakura/sakura.vcxproj
> -  <Import Project="..\tests\compiletests.targets" />
レス付けるために現状のコードを確認したところ、
現時点では確かに、書き順を入れ替えたらcompiletestsを先に実行させることができることに気付きました。
ただし、これは「githashの実行タイミングの指示が誤っているため」なのですっごく微妙です。。。（詳細は後述

2022-02-24 14:16 UTC, berryzplus commented
> githashは一度作成されるとリビルドでは作り直されないようです。

この「一度作成されると呼び出されない」が間違ってるように思っています。
また、リビルドで再作成されない原因は `githash.h` がCleanタスクで削除する対象になっていないからです。
#1757 で対応をやりかけましたが、推奨しない手順でビルドした場合に問題があることが指摘されて、
説明がめんどくさくなったので取り下げています。

> 2つのルートを想定しないといけないので、この際順を変えてしまったらいいのでは、と思います。

論理構造的には、`find-tools.bat` を呼び出す「すべてのタスク」で `SetEnv` したほうが良いと思います。
ただし、最初に実行されるタスクが1つに決まるなら、1つだけの修正でもよいはずです。
「すべて vs １つか２つ」だったら後者を選択したくなるのが人情ではないかと思います。

MsBuildのタスク実行順は、属性定義により相対的に決まります。
https://github.com/sakura-editor/sakura/blob/90d67663d151798237c6336c9e2af5ae0162c827/sakura/githash.targets#L8-L9
https://github.com/sakura-editor/sakura/blob/90d67663d151798237c6336c9e2af5ae0162c827/tests/compiletests.targets#L14
現時点では「ClCompileの前」が共通するので、先に定義したものが先に実行されます。
しかし、タスクの意味合いが違うので、実行順を入れ替えると変です。

* githashタスク　ソースファイル `githash.h` を生成します。
  ソースファイルはコンパイル開始前までに完了させたい。
* compileTestsタスク　ソースファイルが妥当かどうかを検証します。
  テンプレートクラスの互換チェックなのでビルド前に完了させたい。

ソースを生成する前に、ソースコードのチェックをしていいの？　ということになります。

2022-02-24 16:11 UTC, kazasaku commented
> kazasakuさん 完全ログをありがとうございます
> 
> 49行め
> 
> ```
> 1>VisualStudioEdition            = Microsoft Visual Studio Community 2019
> 1>VisualStudioVersion            = 16.0
> ```
> 
> 126行め
> 
> ```
> 2>---- Make githash.h ----
> 2>find-tools.bat
> 2>|- CMD_MSBUILD=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
> 2>|- CMD_CMAKE=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
> 2>|- CMD_NINJA=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe
> ```
> 
> バージョンが違いますよね。これを修正したいのです。 githash.targetsの呼び出し順を変更して、修正できるか試してもらえませんか。

3個あるターゲットのうち、`NUM_VSVERSION`をあらかじめ定義していないgithash.targetsからの呼び出し時のログも対応したいのでしょう？
僕の言ってることと何が違いますか？？
そうしたいならそうすればいいです…とすでに申し上げています。

> これも最近の変更とは関係ない以前からあるバグですのでまとめちゃってもいいかと思います。

目的と関連がなく、かつ問題の原因と捉えているようですが違います。 #1807 のコメントで説明した通りです。
「本問題とは無関係ですが同時対応します」と書けば誤解されずに済みましたが、なぜそう書かなかったのでしょうか。

2022-02-24 16:14 UTC, dep5 commented
berryzplusさん

> リビルドで再作成されない原因は `githash.h` がCleanタスクで削除する対象になっていないからです。

そういう経緯だったんですね。以前、ビルドの失敗が続いて、
githash.hを削除したらうまくいくようになりました。

> ソースを生成する前に、ソースコードのチェックをしていいの？　ということになります。

compileTestsの前にgithash.hを含めてすべてのファイルをそろえておくために、この順になっているのですね。順序を変えるのはやめました。

2022-02-24 16:21 UTC, kazasaku commented
> > リビルドで再作成されない原因は `githash.h` がCleanタスクで削除する対象になっていないからです。
> 
> そういう経緯だったんですね。以前、ビルドの失敗が続いて、 githash.hを削除したらうまくいくようになりました。
> 

#1757 で、僕はこう書きました。
> プロジェクトごとにビルド/クリーンしているような場合は大丈夫なんでしょうか？

これはツールバーの「ビルド」メニューにある「（プロジェクト名）をビルド」、あるいはソリューションエクスプローラーで、プロジェクトを右クリックして表示されるメニューの「ビルド」をクリックしてビルドしている場合を指しています。本PRのコメントから察するに @dep5 さんのビルドのやり方は多分これなんじゃないかと推測します。

2022-02-24 16:30 UTC, kazasaku requested changes
>> ソースを生成する前に、ソースコードのチェックをしていいの？　ということになります。
>
> compileTestsの前にgithash.hを含めてすべてのファイルをそろえておくために、この順になっているのですね。順序を変えるのはやめました。

PR本文は並べ替えることを前提に書かれているので修正が必要です。

2022-02-24 16:50 UTC, dep5 commented
kazasaku さん

https://github.com/sakura-editor/sakura/pull/1806#issuecomment-1046947788
```
4>VisualStudioEdition            = Microsoft Visual Studio Community 2019
4>|- CMD_CMAKE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
```
ではバージョンが一致していますね。
このPRの再現はできていません。(再現する必要はないですが)

https://github.com/sakura-editor/sakura/pull/1806#issuecomment-1048920030
```
1>VisualStudioEdition            = Microsoft Visual Studio Community 2019
2>|- CMD_CMAKE=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
```
では異なったバージョンです。
このPRの再現が出来ています。

わたしは今まで行頭の数字は何だろうと思っていたのですが。プロジェクトを示しているのですね。
VisualStudioVersionの値の確認方法も今まで不思議だったので教えてくれてありがとうございます。

ログではなく、選ばれるツールのバージョンを想定通りにしたいです。
1回しか呼ばれないから初回にすべて対応する必要があります。

わたしはIDEからのビルドがメインですので、ビルド時の問題に対応という意味で一体なのですが、
コマンドラインでのビルドがメインの方はそう思わないかもしれません。
個人的にはコミット履歴から、PRに飛んだ時にある程度情報がまとまっていてほしいのですが…。
PR本文に追記しました。

2022-02-24 16:54 UTC, kazasaku commented
#1807 を捨ててこちらで進めます。

@dep5 
この後のコメントに、あなたが遭遇している問題の原因と、解決に必要な対処の説明をまとめます。
これをPRの「仕様説明」の部分に書いてください。
やり方：ハンバーガーアイコンからEditを押す
![スクリーンショット 2022-02-25 015303](https://user-images.githubusercontent.com/67105596/155570354-46d3361c-4efe-4a43-93eb-cde27e203d05.png)

2022-02-24 17:05 UTC, kazasaku commented
###  PR の背景
VS2017とVS2022が混在した環境で、VS2017のツールを探索した際、CMakeとNinjaのみ異なるバージョンのツールが選択されます。

（ここに https://github.com/sakura-editor/sakura/pull/1807#issuecomment-1050037000 と同じログを挿入）

### 仕様・動作説明

#1785 で、VS2017とそれより後のバージョンで、探索処理を行うサブルーチンを分けました。
VS2019以降の場合、Visual Studio Locatorの引数で、選択したバージョン（`NUM_VSVERSION`）と、それに1加えた値（`NUM_VSVERSION_NEXT`）を使って、そのバージョンのMSBuildを探すようになりました。
一方、VS2017の場合は、Visual Studio Locatorの引数に固定値（`[15,16)`）を用います。
このため、VS2017では`NUM_VSVERSION_NEXT`変数が定義されません。

さて、CMakeおよびNinjaの探索を行う処理でも、Visual Studio Locatorを使っていますが、引数に選択したバージョンとそれに1加えた値を利用しています。
ここで本来`NUM_VSVERSION_NEXT`を定義しなければなりませんでしたが、CMakeの探索処理をfind-tools.batに実装した際に漏れがありました。
#1785 で変更する以前はMSBuild探索時に定義された値が再利用されていたため影響はありませんでしたが、 #1785 でサブルーチンを整理した結果、`NUM_VSVERSION_NEXT`が定義されないコードパスが生じ、定義漏れの影響が顕在しました。

このPRでは、漏れている定義を追加して、VS2017との混在環境でもCMake/Ninja探索時に正常に動作するようにします。

2022-02-25 15:00 UTC, dep5 commented
find-tools.batについてです。
ソース内での使用例は以下のような感じで、環境変数を設定済みなら2回目は呼ばれないと今まで思っていました。
```
if not defined CMD_GIT call "%~dp0..\tools\find-tools.bat"
if not defined CMD_VSWHERE call %~dp0..\tools\find-tools.bat
if not defined CMD_NINJA call %~dp0..\tools\find-tools.bat
```

[.bat（バッチファイル）のforコマンド解説。 - Qiita](https://qiita.com/plcherrim/items/67be34bab1fdf3fb87f9#3for%E6%96%87%E3%81%AE%E8%A7%A3%E5%89%96-%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%99%E3%83%83%E3%83%88%EF%BC%91%E6%96%87%E5%AD%97-)
> `for /f "usebackq tokens=1 delims==" %%i in (`set`) do echo %%i`

こちらから拝借した環境変数を列挙するコマンドを該当行の上に追記してみたところ
find-tools.batを2回目に呼び出す直前にfind-tools.batが設定する変数は何もありませんでした。
1回目 - sakura\githash.bat
2回目 - tests\compiletests.run.cmd 

したがって、初回のみ対応すればよいとしましたが
IDEから呼ばれる度に環境変数を設定する必要があるようですね。
訂正します。テストが不十分でした。
https://github.com/sakura-editor/sakura/pull/1806#issuecomment-1048794627

2022-02-25 15:13 UTC, kazasaku commented
> 修正案をいただいたので併記しています。(#1806 (comment))

🤔

2022-02-25 15:28 UTC, berryzplus commented
このPRはどこに向かいます？
目的が明確で達成手段が妥当と判断できればどんな内容でも構わないと思っています。

ステータス的には `request changes` です。
PR本文の説明が実態と違っていて混乱を招きそうです　という趣旨の指摘が入ってる認識っす。。。

2022-02-25 15:47 UTC, berryzplus commented
ぼくが個人的に「あかんやろ・・・」と思った点を、参考までに書き残しておきます。

#### カテゴリ
「事象の捉え方は個人の自由」なのですが、認識が誤っている気がします。
> * 不具合修正
> * ビルド関連
>   * ビルド手順
>   * ローカルビルド

* アプリの不具合ではないので「不具合修正」は正しくないです。
* 「ビルド手順」は変更されないので、これも正しくありません。
* 「ローカルビルド」は正しいですが、MSVCビルド全般に影響する変更なのでやや微妙です。
* 個人的には「その他」が最も適切じゃないか？という見解です。

#### PR のデメリット (トレードオフとかあれば)
> 呼び出し順を変えるので何か不具合があるかもしれません。

「呼出し順」は変えない変更になった認識です。
「変更によって何か不具合が出るかもしれません。」は、当たり前なので「自明」として省略でもよいです。

#### PR の影響範囲
> ~~いくつかファイルの呼び出し先を追ってみた感じでは、依存関係が無いように思いましたが、どうでしょうか？~~

最初に突っ込むべきでしたが、ここは「どうでしょうか？」を書く場所じゃないです。
この項目には想定の影響範囲を書いておき、
「テスト内容」が十分かどうかを判断できるようにします。

「この修正、自分の中では完璧っす！」を誤解なく伝えるための項目なので、
ここに疑問文を書かれると「なんでやねん！」のドツキ漫才になってしまいます。

ただ、「わかりません（キリッ」なら、それはそれでもよいです。

2022-02-27 13:59 UTC, dep5 commented
berryzplus さん
ローカルでしかテストできず、
ビルド中の不具合修正なので選択しました。
結局当初の想定した原因と違っていたのが
カテゴリは用意された選択肢の中で必要なものを残すタイプですが
アプリの不具合と明記するか、ビルド関連のなかに不具合修正を用意しておいてほしいですね。

このPRで書いた当初一番教えてほしかったのが、
依存関係についてだったのですが、どこに書くべきでしたか？

2022-02-27 15:14 UTC, berryzplus commented
> カテゴリは用意された選択肢の中で必要なものを残すタイプですが
> 「アプリの不具合修正」と明記するか、ビルド関連のなかに「不具合修正」を用意しておいてほしいですね。
> 不具合修正をその他と書くのは抵抗を感じます・・・。

ではテンプレ修正しましょう。
すぐやれる人がいたらお願いしたいです。
来週末までくらいで良ければ自分がPR作ります。

2022-02-27 15:23 UTC, berryzplus commented
> このPRで書いた当初一番教えてほしかったのが、
> 依存関係についてだったのですが、どこに書くべきでしたか？

このコメントの意味がわかりませんでした。

* 依存関係　「ビルドの依存関係」という意味で使う言葉かと思います。
  MsBuildの設定ファイル内では `DependsOn` 属性で指定しますが、あんまり使ってないです。
  実行順序のことを指しているなら、こないだ書いた通り相対的に決まるものなのでやや説明しづらいです。

「どのPRで作り込んだバグです」的な依存関係を書く場所はない気がします。
強いて言えば「PRの背景」がそういう説明の記述位置になると思ってます。

この辺も、具体的な改善案があれば試してみてよいと思います。

2022-02-28 01:06 UTC, kazasaku commented
> ではテンプレ修正しましょう。
> すぐやれる人がいたらお願いしたいです。

「こうしたいです」という構想はあるので、用意しておきます。

2022-02-28 01:11 UTC, kazasaku approved these changes
承認しておきます。
本文の書き方は他のissueやPRを手本に勉強しましょう。

2022-02-28 06:56 UTC, berryzplus commented
問題ないとおもうのでマージしておきます。
何かあれば別PRで対処していきましょう。

2022-02-28 06:57 UTC, merged

2022-02-28 12:37 UTC, dep5 commented
berryzplusさん

IDEでfind-tools.batが初回のみ呼ばれるという誤った思い込みをしていたので、
当初の想定で話すと、
sakura\sakura.vcxprojの中に以下の記述があります。
  <Import Project="..\sakura\githash.targets" />
  <Import Project="..\sakura\funccode.targets" />
  <Import Project="..\sakura\ExtractArchives.targets" />
  <Import Project="..\tests\compiletests.targets" />
  
funccodeでgithashが呼ばれていたのでfunccodeのビルドにgithashが必要なのはわかりました。
compiletestsではgithashかfunccodeの呼び出しがなさそうだったので
どのような順にしてもよいと当初は判断しました。
しかし、 compiletestsの前にすべてのファイルを用意しなければいけないので、誤りだったわけです。
質問に答えてもらえてよかったです。
(find-tools.batがその都度呼ばれるのでもともとこの対策自体は意味がなかったわけですが。)

DependsOn 属性についてではなく、targetsそれぞれにビルドを進めていくうえで
ほかのtargetsのビルドを呼び出すことがあるのか、という意味で依存関係と使いました。
今回でいうと compiletests.targetsのビルドを進めて、
githash,funccode,ExtractArchivesを先にビルドを済ませておく必要があるかという質問でしたが、
この個所以外でも何か依存関係があるかもしれないと思って、ぼかした表現を使いました。

2022-03-01 04:00 UTC, berryzplus commented
もう答えが出てそうですが・・・

> 今回でいうと compiletests.targetsのビルドを進めて、
> githash,funccode,ExtractArchivesを先にビルドを済ませておく必要があるかという質問でしたが、
> この個所以外でも何か依存関係があるかもしれないと思って、ぼかした表現を使いました。

* githash　ソースコード生成
* funccode　ソースコード生成（githashには依存しない）
* ExtractArchives　ビルド後のアーカイブ展開処理

です。

こうしてみるとExtractArchivesの記述位置がおかしいです。

このあたりを修正してもアプリ機能に影響がないので「動けばいいかぁ・・・」で放置し続けています。