「インタープリタ」のカタカナ表記を統一する
sakura-editor/sakura pull request #1836
Opened 2022-05-03 06:50 UTC by sanomari

#  PR の目的

タイトル通りです。

##  カテゴリ

- リファクタリング
- ドキュメント修正

##  PR の背景

#1822 で「インタープリタ」の表記ゆれが指摘されました。

修正したい人がPRして良いということなのでPR作成します。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

* コメントやドキュメントにある「インタープリタ」の表記を統一します。

|カタカナ表記       |出現回数|正誤(主観)|
|--------------------|----------|-----------|
|インタープリター|            4|誤             |
|インタープリタ   |            5|正             |
|インタプリター   |            0|誤             |
|インタプリタ      |             2|誤            |

表記修正が目的であるため、静的解析の警告には対処しません。

##  PR の影響範囲

コメントとドキュメントに影響する変更です。

##  テスト内容

機能影響がないので不要です。

##  関連 issue, PR

* #1822

##  参考資料

2022-05-03 09:10 UTC, beru commented
#1822 では「インタープリター」を正しい表記としているので、「インタープリタ」に統一するのが正しいのかどうか判断が付きません。

カタカナ表記 | Google検索 
-- | -- | --
インタープリター | 1,170,000
インタープリタ | 78,300
インタプリター | 97,100
インタプリタ | 590,000

2022-05-03 09:48 UTC, kazasaku requested changes
判断を保留します。
https://github.com/sakura-editor/sakura/issues/1822#issuecomment-1115908817

2022-05-03 10:53 UTC, sanomari commented
分かると思いますが、主観で正しいと思ったものに統一するよう提案しています。

インタープリタパターンとかインタープリタ言語とか言いますよね？

interpreterは「いんたぁぷりたぁ」なので、インタープリターとしても間違いじゃないと思います。

分かっててやってると思いますが、Google検索のヒット件数は正しいかどうかの判断に使わないほうが良いです。素人さんに説明するためのツールとしては使い勝手がよいので私もよく使いますが。

2022-05-03 11:34 UTC, berryzplus commented
Wikipediaの「インタープリタ」に面白いことが書いてありました。

[インタープリタ（曖昧さ回避）](https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%97%E3%83%AA%E3%82%BF_(%E6%9B%96%E6%98%A7%E3%81%95%E5%9B%9E%E9%81%BF))
> [インタプリタ](https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%97%E3%83%AA%E3%82%BF) - コンピュータのプログラムを逐次 機械語に変換しては即実行するソフトウェア。
> [インタープリター (自然)](https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%97%E3%83%AA%E3%82%BF%E3%83%BC_(%E8%87%AA%E7%84%B6)) - エコツアー、自然観察などで自然と人との仲介をする役目の人。

サクラエディタのコメントに書いてある「インタープリタ」は「エコツアーのツアコン」では断じてないので、「インタープリタ」の表記で良いように思いました。

エコツアーのツアコン、メジャーなんですね。。。

2022-05-03 11:51 UTC, beru commented
何が正しいかというのは主観で変わってしまいますね。個人的にはどっちでも良いと思うのでApproveします。

Google検索のヒット件数の定義は良く分かりませんが、検索エンジンのボットがインターネットのウェブサイトの色々なページを巡回してデータベースに登録したキーワード毎の件数なのかなと思いました。なので世の中でどちらの表記の単語がより使われているかの目安になるのではないかと思ってましたが、全くそんな事も無いんですかね？

2022-05-03 11:51 UTC, beru approved these changes

2022-05-03 16:22 UTC, Rukoto commented
本件は #1822 で小生が希望した修正とは異なる結果での修正案ですが、
まず、「インタープリタ」に統一されることについては異議はありません。
@beru さんの指摘（Google検索ヒット数）にあるように、当該語句は「インタープリター」への転換が進行中の語句だと考えております。
なので、私としては残念な気持ちは当然あります。ただ、このPRに反対するほどの語気は出せないです。
このPRに対する小生の判断は「統一されるならOKかな？」だと思ってください。

2022-05-04 05:23 UTC, berryzplus commented
よくよく考えてみると、Google検索のヒット件数に影響を与えているのは「ザ・インタープリター」という映画のほうかも知れません。

余談ですが、映画のタイトルがヒット件数に影響を与える例を紹介します。

USBやSATAが登場するまで、PCに機器を増設するには「スカジー」という技術が使われていました。
スカジー機器には接続コネクターが2つ付いていて、数珠繋ぎに複数の機器を接続できる仕組みでした。
この仕組みだと、数珠繋ぎの末端にあたる端末では接続コネクターが1つ余ります。
スカジー時代には、余った接続コネクターに「終端」を意味する部品を差しておく習わしがありました。
この終端部品を「[ターミネータ](https://e-words.jp/w/%E3%82%BF%E3%83%BC%E3%83%9F%E3%83%8D%E3%83%BC%E3%82%BF.html)」と言います。

さて、「ターミネーター」って映画があるじゃないですか。

Google検索で「ターミネータ」を探すと映画「ターミネーター」の情報が出てきます。
もう「コトバとしては『ターミネーター』が正しいんじゃないか？」と思えてくるほどの圧倒的な情報量です。

こういう場合は追加キーワードを指定して絞り込みをかけてみたり（「ターミネータ スカジー」とか）、辞書を参照してコトバの専門家の知恵を借りるしかなくなってくるような気がします。

2022-05-04 12:33 UTC, beru commented
検索エンジンについて分かりやすい解説ありがとうございます。

発音が同じで意味が異なる語：同音異義語
綴りが同じで意味が異なる語：同形異義語、同綴（どうてつ）異義語

が影響を与えてるんですね。

> こういう場合は追加キーワードを指定して絞り込みをかけてみたり（「ターミネータ スカジー」とか）、辞書を参照してコトバの専門家の知恵を借りるしかなくなってくるような気がします。

きちんとこだわりたい場合はそういう事になるんですね。

ただ、いわゆる正しさにどれだけ注意を払いたいかは人それぞれでしょうね。一部の語句が不完全でもコンテキストで大体意味が通じたりするので、誤解が生じるレベルで間違っているわけでないのであれば大体のケースで許容できるんじゃないかと思います。

例 | YES/NO
------|:-------:
英単語の綴り間違いは気にするか？ | YES
慣用読みを気にするか？ | NO
マクドナルドの短縮形は？ | マック

少し話が変わりますが、コードレビューで重箱の隅をつつくような指摘が続いてなかなかマージがされない場合に、神経質なレビューワー側に問題があるのか、問題があるコードを書きまくるプログラマ側の問題なのか、悩む事が多いです。ダメ出しは不毛な場合もあるのでイーロンマスクがどうやって増毛したかが気になります。

2022-05-05 05:19 UTC, berryzplus commented
「マクドナルド」の「マック」は、愛称（≒あだな）だと思います。
関西方面では「マクド」と呼ばれますが「愛称」なので好きに呼んだらよいと思います。

「サムライマック」や「ビックマック」、「マックフライポテト」という商品があるので、
個人的には、マクドナルドの短縮形は「マック」がしっくり来ます。
ただ、商品名は「公式な愛称を要求する意図ではない」らしいです。

* [日本における「マクドナルド」名称・表記・発音の由来](https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E3%83%9E%E3%82%AF%E3%83%89%E3%83%8A%E3%83%AB%E3%83%89#%E6%97%A5%E6%9C%AC%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%80%8C%E3%83%9E%E3%82%AF%E3%83%89%E3%83%8A%E3%83%AB%E3%83%89%E3%80%8D%E5%90%8D%E7%A7%B0%E3%83%BB%E8%A1%A8%E8%A8%98%E3%83%BB%E7%99%BA%E9%9F%B3%E3%81%AE%E7%94%B1%E6%9D%A5)

2022-05-05 05:20 UTC, merged