「インターフェース」のカタカナ表記を統一する
sakura-editor/sakura pull request #1837
Opened 2022-05-03 06:52 UTC by sanomari

#  PR の目的

タイトル通りです。

##  カテゴリ

- リファクタリング
- ドキュメント修正

##  PR の背景

#1822 で「インターフェース」の表記ゆれが指摘されました。

修正したい人がPRして良いということなのでPR作成します。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

* コメントやドキュメントにある「インターフェース」の表記を統一します。

|カタカナ表記       |出現回数|正誤(主観)|
|--------------------|----------|-----------|
|インターフェイス|          11|誤             |
|インタフェイス|                0|誤            |
|インターフェース|          98|正             |
|インタフェース|              38|誤            |

表記修正が目的であるため、静的解析の警告には対処しません。

##  PR の影響範囲

コメントとドキュメントに影響する変更です。

##  テスト内容

機能影響がないので不要です。

##  関連 issue, PR

* #1822

##  参考資料

2022-05-03 09:45 UTC, kazasaku requested changes
判断を保留します。
https://github.com/sakura-editor/sakura/issues/1822#issuecomment-1115908817

2022-05-03 16:33 UTC, Rukoto commented
![image](https://user-images.githubusercontent.com/31055417/166495072-edb1f8d1-df84-4d36-a5c5-945d86eb4cca.png)
とりあえずWindows上ではこれが一番目につく部分でしょうか。

inter-face
インター + フェイス

こう書くと、な～んで「フェース」が一般化しちゃったんだ？なんて思うわけですが。

語句が統一されることを優先したいですが、このPRについては「インターフェイス」が正しいと、私は強く考えておりますため、
できれば #1822 で提示した内容「インターフェイス」でご再考いただけないか、また、皆様の意見を伺いたく思っています。

2022-05-03 17:25 UTC, beru commented
一般的にはインターフェースが良く使われてるようですね。

https://interface.cqpub.co.jp/

個人的にはインターフェイスを推しますが、しょせんカタカナ英語なので統一されていればそれで良いと思います。

2022-05-04 12:06 UTC, kazasaku commented
このPRに関してはこれでよいと思いましたのでapproveに切り替えました。

2022-05-05 05:21 UTC, merged