「ヘッダー」または「フッター」のカタカナ表記を統一する
sakura-editor/sakura pull request #1838
Opened 2022-05-03 07:00 UTC by sanomari

#  PR の目的

タイトル通りです。

##  カテゴリ

- リファクタリング
- ドキュメント修正

##  PR の背景

#1822 で「ヘッダー」および「フッター」の表記ゆれが指摘されました。

修正したい人がPRして良いということなのでPR作成します。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

* コメントやドキュメントにある「ヘッダー」の表記を統一します。
* コメントやドキュメントにある「フッター」の表記を統一します。

|カタカナ表記       |出現回数|正誤(主観)|
|--------------------|----------|-----------|
|ヘッダ                  |         150|誤            |
|ヘッダー              |           42|正            |
|フッタ                  |           26|誤            |
|フッター              |           26|正            |

表記修正が目的であるため、静的解析の警告には対処しません。

##  PR の影響範囲

コメントとドキュメントに影響する変更です。
共通設定「ファイル」タブのチェックボックスのラベルを変更しているので、そこだけUI影響があります。

##  テスト内容

共通設定「ファイル」タブを表示して、チェックボックスのラベルにはみ出しがないのを確認しました。

##  関連 issue, PR

* #1822

##  参考資料

2022-05-03 08:51 UTC, kazasaku requested changes
濁点が付く「フッダ」という表記も存在したと思うので、これを含めてください。

2022-05-03 11:36 UTC, berryzplus commented
むかしは何故か「ヘッダ＆フッダ」って言ってましたね。
何で「フッダー」だったのか、ググってみたけど分かりませんでした。

2022-05-03 12:24 UTC, beru commented
> むかしは何故か「ヘッダ＆フッダ」って言ってましたね。 何で「フッダー」だったのか、ググってみたけど分かりませんでした。

言葉って読み書きが伴わないと変化しやすいものだと思います。ヘッダの最後が濁点なのでフッタの最後も濁点に変化してフッダと書いてしまう人が一定数いたんでしょうね。

2022-05-03 16:46 UTC, Rukoto commented
元のissue #1822 を提出した立場から意見させていただきます。

「ヘッダー」「フッター」は文書・印刷を扱う非常に多くのユーザーが目にする語句です。
それだけに、Widnws上との表記に違いがあると非常に違和感の大きなものです。

例えばWoedやExcel等、メジャーなソフトウェアとも異なってしまうことになりますので、
長音のない「ヘッダ」「フッタ」が残存している状況は即刻修正すべきである、という思いです。

2022-05-04 12:12 UTC, kazasaku approved these changes

2022-05-04 12:12 UTC, kazasaku commented
この内容で良いと思ったのでapproveに切り替えました。

2022-05-05 05:21 UTC, merged