「ユーザー」のカタカナ表記を統一する
sakura-editor/sakura pull request #1839
Opened 2022-05-03 07:39 UTC by sanomari

#  PR の目的

タイトル通りです。

##  カテゴリ

- リファクタリング
- ドキュメント修正

##  PR の背景

#1822 で「ユーザー」の表記ゆれが指摘されました。

修正したい人がPRして良いということなのでPR作成します。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

* コメントやドキュメントにある「ユーザー」の表記を統一します。
* 「ユーザーの利便性」を表す「ユーザビリティ」は置換対象から除外します。
* VB用語「ユーザ定義型」は置換対象から除外します。

表記修正が目的であるため、静的解析の警告には対処しません。

##  PR の影響範囲

コメントとドキュメントに影響する変更です。
インストーラーの表示文言にも影響する変更です。

##  テスト内容

修正内容から不要と思います。

##  関連 issue, PR

* #1822

##  参考資料

2022-05-03 09:00 UTC, beru commented
おおむね問題無いと思いますが、以下のファイルについては変更を加えない方が良いかなと思います。

- CHANGELOG.md
- help/sakura/res/HLP_UR009.html
- help/sakura/res/HLP_UR014.html
- help/sakura/res/HLP_UR017.html

改版履歴の文言については変更をしない方が良いと思います。あくまで履歴用の記述なので現状の変更の対象外になるかなと思います。

ソースコード中にコメントで日付付きで誰々がどういう変更をしたかが書かれていますが、これについては変更対象としても構わないと思います（そもそもそういうコメントの付け方が時代遅れですが…）。いちいち判断するのは大変なので。

2022-05-03 09:48 UTC, kazasaku requested changes
最終判断は一旦保留にします。
https://github.com/sakura-editor/sakura/issues/1822#issuecomment-1115908817

2022-05-03 11:11 UTC, sanomari commented
変更履歴からヘルプが作られる場合も考えられるので、変更履歴も除外すべきでないと思います。

開発当時の状況をできる限り残したい意図なら、すでにGitリポジトリになっていることからオリジナルの履歴コメントを保持する意味はないように思います。

2022-05-03 12:20 UTC, beru commented
> 変更履歴からヘルプが作られる場合も考えられるので、変更履歴も除外すべきでないと思います。

これはヘルプに変更履歴が含まれるとして、そこに表記ゆれがある状態を除外したいという事でしょうか？
別にサクラエディタを使う上で不都合は無いのだからそのままでも良いんじゃないですかね。

ただ仮に変更履歴の表記が多少変わったからと言って困る事も無いのでApproveします。

> 開発当時の状況をできる限り残したい意図なら、すでにGitリポジトリになっていることからオリジナルの履歴コメントを保持する意味はないように思います。

まぁヘルプに開発履歴を載せる意味はもう既に無いと思います。昔そうしていたら今もそうしているだけであって。

2022-05-03 16:57 UTC, Rukoto commented
変更履歴やコード内のコメントまで含むかについては、ある意味「思い切って」含めることを推奨したいです。
含まなければ修正対応として中途半端になるとも言えるので、
根拠とかよりも「スマートである事」を好むか、という話なのかなと。
機能とは関係ない部分では、こういう対応もありうるのではないか、と思います。

小生は実際にプログラムを修正したり品質を担保する立場じゃないので、私がこれ以上申すことはございません。

2022-05-04 12:16 UTC, kazasaku approved these changes

2022-05-04 12:17 UTC, kazasaku commented
この内容で良いと思ったのでapproveに切り替えました。

2022-05-05 05:22 UTC, merged