'GREPの「カレントフォルダーを初期値」に対応'
sakura-editor/sakura pull request #1852
Opened 2022-06-09 12:45 UTC by dep5

#  PR の目的
https://github.com/sakura-editor/sakura/issues/1851 で報告された問題に対応します

##  カテゴリ

- 不具合修正

##  PR の背景
https://github.com/sakura-editor/sakura/pull/1696 により動かなくなっています。

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明
`CDlgGrep::SetData()`
の中で"カレントフォルダーを初期値"がONの場合
```
		SetGrepFolder( GetItemHwnd(IDC_COMBO_FOLDER), szWorkFolder );
```
が動きますが、https://github.com/sakura-editor/sakura/pull/1696 での追加で
```
		::DlgItem_SetText(GetHwnd(), IDC_COMBO_FOLDER, m_szFolder);
```
別の変数で上書きしています。

https://github.com/sakura-editor/sakura/releases/tag/v2.4.1
で動きを確認してみると、
チェックボックスをONOFFするたびに反映されるタイプのものではなく、
ダイアログ表示時に一度動けばよいようです。

`CDlgGrep::SetData()` から`CDlgGrep::DoModal()` へ移動して対応してみました。

##  PR の影響範囲

##  テスト内容

### テスト1
https://github.com/sakura-editor/sakura/issues/1851
「カレントフォルダーを初期値」にチェックを入れた状態で「検索」を押した後
ファイルを開いてからGREPダイアログを表示します。

手順

##  関連 issue, PR
https://github.com/sakura-editor/sakura/issues/1851
https://github.com/sakura-editor/sakura/pull/1696

##  参考資料

2022-06-10 10:23 UTC, sanomari commented on sakura_core/dlg/CDlgGrep.cpp
> -		SetGrepFolder( GetItemHwnd(IDC_COMBO_FOLDER), szWorkFolder );
すみません、なんかおかしいです。

SetGrepFolderはグローバル関数でクラスメンバーを更新するものではありませんでした。

2022-06-10 12:02 UTC, dep5 commented on sakura_core/dlg/CDlgGrep.cpp
> -		SetGrepFolder( GetItemHwnd(IDC_COMBO_FOLDER), szWorkFolder );
`CDlgGrep::GetData()`は「検索」を押した時、ダイアログを消すときに呼ばれるのではないでしょうか？

> 直近のGrep実行が「カレントフォルダを初期値にする」ではなかった場合に
> カレントフォルダを初期値にできない（＝たぶん不具合になる）んじゃないでしょうか。

「カレントフォルダが初期値」をOFFで「検索」した後はONにできない、という意味ですか？
テストにくわえたいので、よかったら教えてください。

`SetGrepFolder`も誤ってコピーしていたので削除しました。

2022-06-10 12:13 UTC, dep5 commented
[1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=sakura-editor_sakura&pullRequest=1852&resolved=false&types=SECURITY_HOTSPOT)
はなぜ出ているのでしょう？/* 除外ファイル */と同じ書き方のつもりなのですが…
どなたか修正方法を教えてください。

2022-06-10 13:18 UTC, dep5 commented
元からあるコードの条件を変更しないように書き直しました。

2022-06-11 06:28 UTC, beru commented on sakura_core/dlg/CDlgGrep.cpp
>  	if( m_szFolder[0] == L'\0' && m_pShareData->m_sSearchKeywords.m_aGrepFolders.size() ){
else と if の行は分けずに else if と書いた方がコードが読み易いと思います。

2022-06-11 07:32 UTC, berryzplus requested changes
指摘の意味が通じるか微妙なんですけど、
コードの移動先をOnInitDialogにしたほうがよいと思う
の件で request change にしておきます。

2022-06-11 12:58 UTC, dep5 commented
https://github.com/sakura-editor/sakura/pull/1852#discussion_r894975834
berryzplusさんのアドバイスに従って`CDlgGrep::DoModal`から`CDlgGrep::OnInitDialog`に再移動しました。

2022-06-11 13:07 UTC, dep5 commented on sakura_core/dlg/CDlgGrep.cpp
>  	if( m_szFolder[0] == L'\0' && m_pShareData->m_sSearchKeywords.m_aGrepFolders.size() ){
[force-push](https://github.com/sakura-editor/sakura/compare/3eef9f134b564f946f33d8ebe0579fef26920d06..721e7b97582f7f538ba4454a448d6215899ea1d0)したのですが、wcscpyの部分でSecurity Hotspotsがでてしまいました。
以前、修正で苦労したのでそれよりはもとのコードを変更しないように書き換えたら
Security Hotspotsが消えるかも、と変な改行が入っています。

2022-06-11 13:08 UTC, dep5 commented on sakura_core/dlg/CDlgGrep.cpp
> +	if( pszCurrentFilePath ){	// 2010.01.10 ryoji
m_szCurrentFilePathを使いたかったので移動しましたが、必要なくなりました。

2022-06-11 13:12 UTC, dep5 commented on sakura_core/dlg/CDlgGrep.cpp
> +		SplitPath_FolderAndFile( m_szCurrentFilePath, m_szFolder, szWorkFile );
DoModalの時は移動のほかに少し変更がいりましたが、
OnInitDialogにすると、移動するだけで済んで、すっきりしたコードになりました。

2022-06-11 13:19 UTC, berryzplus approved these changes

2022-06-11 13:19 UTC, berryzplus commented on sakura_core/dlg/CDlgGrep.cpp
> +		SplitPath_FolderAndFile( m_szCurrentFilePath, m_szFolder, szWorkFile );
SonarCloudはCスタイル配列を使っても警告出さなくなったんですね。

`SplitPath_FolderAndFile`の第3引数は `nullptr` を受け入れるので `szWorkFile` のメモリ確保は無駄です。
500バイトくらい許容だと思いますが、文句言う人がいそうです。（既知のGuys...）

2022-06-11 13:24 UTC, berryzplus commented on sakura_core/dlg/CDlgGrep.cpp
> +		SplitPath_FolderAndFile( m_szCurrentFilePath, m_szFolder, szWorkFile );
別観点ですが、
`OnBnClicked(IDC_BUTTON_CURRENTFOLDER);`
とかにしなくて良いのかな？（無題の場合どうなる？）ということを思いました。
これ、指摘じゃないです。

2022-06-11 14:03 UTC, dep5 commented on sakura_core/dlg/CDlgGrep.cpp
> +		SplitPath_FolderAndFile( m_szCurrentFilePath, m_szFolder, szWorkFile );
削除部分のコメントしてるのは間違いだと思いましたが、意味があったんですね。
よく読めばよかったです。

2022-06-11 14:12 UTC, berryzplus approved these changes

2022-06-11 16:37 UTC, beru commented on sakura_core/dlg/CDlgGrep.cpp
>  	if( m_szFolder[0] == L'\0' && m_pShareData->m_sSearchKeywords.m_aGrepFolders.size() ){
Security HotspotsってSonarCloudのでしたっけ？

静的解析のfalse positiveな警告を潰す為にコードを読みにくくするのは、本来はコード品質を良くするためにツールを使っているのに、そのツールの都合に合わせる為にコードの可読性を悪くしている事になります。それだと人間がツールに振り回されてしまっているようで、トータルとしてツールを使う事でプラスになったんだろうか？と疑問を感じてしまいます。。

2022-06-12 10:31 UTC, merged