Windows SDKのマクロ定数「NULL」を再定義する
sakura-editor/sakura pull request #1858
Opened 2022-06-19 23:43 UTC by sanomari

#  PR の目的

コードでマクロ定数「NULL」を使った場合にCode Smellsが検出されてしまうのを対処します。

##  カテゴリ

- リファクタリング

##  PR の背景

ここのprojectではコードの静的解析に Sonar Cloud を使っています。
検出されたバグを修正する試みが何度か行われてきました。
やったことなさそうなんですが、現在 2万 件のCode Smellsが放置されています。
https://sonarcloud.io/project/overview?id=sakura-editor_sakura

今回はこのうちの１種類を軽減する修正を行いたいと思います。

> Use the "nullptr" literal.
https://sonarcloud.io/project/issues?issues=AXXRqVBbpi7wsJ_Rmynv&open=AXXRqVBbpi7wsJ_Rmynv&id=sakura-editor_sakura

##  PR のメリット

##  PR のデメリット (トレードオフとかあれば)

##  仕様・動作説明

マクロ定数「NULL」の定義を 数値`0` から `nullptr` に変えます。

時系列
* 1990年ごろ　Windows SDK提供開始、マクロ定数「NULL」が定義された。
* 2010年ごろ　C++11制定、ポインタ値に 数値`0` を指定することが非推奨となった。
* 2020年ごろ　(現在)　Windows SDKのマクロ定数「NULL」は修正されていない。

##  PR の影響範囲

コードの全域に影響する変更です。

##  テスト内容

### テスト1

手順

##  関連 issue, PR

##  参考資料

2022-06-20 04:04 UTC, sanomari commented
CI結果がこんなんだとわからないですね。

[ローカルリポジトリの Sonar Cloud 結果](https://github.com/sanomari/sakura-editor/runs/6959706897)を貼ります。
> 16557 Issues
Bug A [48 Bugs](https://sonarcloud.io/project/issues?id=sanomari_sakura-editor&branch=master&resolved=false&types=BUG)
Vulnerability A [1 Vulnerability](https://sonarcloud.io/project/issues?id=sanomari_sakura-editor&branch=master&resolved=false&types=VULNERABILITY)
Security Hotspot E [899 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=sanomari_sakura-editor&branch=master&resolved=false&types=SECURITY_HOTSPOT)
Code Smell A [16508 Code Smells](https://sonarcloud.io/project/issues?id=sanomari_sakura-editor&branch=master&resolved=false&types=CODE_SMELL)

Code Smellsのところ、修正を入れる前は [19,835 件](https://github.com/sakura-editor/sakura/runs/6932435361) でした。
約 3,300 件の Code Smells が解消してます。

今回分で発生した Code Smells は誤検知ですね。
そこ、触ってないです。

2022-06-20 04:38 UTC, k-takata commented on sakura_core/StdAfx.h
> +#  pragma warning( disable : 4005 )
`#  undef NULL` だとダメなのでしょうか？

2022-06-20 10:24 UTC, sanomari commented on sakura_core/StdAfx.h
> +#  pragma warning( disable : 4005 )
個人的なこだわりはないんですけど、前にどこかでダメと言われたことあったので回避しました。

ちょっと調べてみたところ、`MISRA C++`では `undef` の使用が「禁足事項」らしいです。
Sonar Cloudでも違反(?)がCode Smellsとして検出されるようです。
https://sonarcloud.io/project/issues?languages=cpp&resolved=false&rules=cpp%3AS959&id=sakura-editor_sakura

2022-06-20 11:21 UTC, k-takata commented on sakura_core/StdAfx.h
> +#  pragma warning( disable : 4005 )
なるほど

2022-06-22 03:40 UTC, berryzplus requested changes
目的には賛同します。
対処方法もLGTMです。
対応内容が不十分だと思うので request changes にします。

## 課題
Windows SDKのNULLの定義が誤っている

## 対策
NULLの定義を訂正する

## 考慮すべき事項
* マイクロソフトがWindows SDKのNULL定義を訂正しない理由を考える
→　何らかの影響があるから直さないんじゃないのか？

たとえば、以下のようなオーバーロード関数があったとすると、NULLの定義が0からnullptrに変わるとコードの意味が変わりますよね。
```c++
void func(int c) { std::out << "int" << std::endl; }
void func(const wchar_t* str) { std::out << "str" << std::endl; }

int main() {
func(NULL);
}
```
要するに、数値型パラメータとポインタ型パラメータでオーバーロードする関数がある場合、無影響とは言えません。

## サクラエディタのコードの影響範囲を予測する
少なくとも CNativeW には数値型パラメータとポインタ型パラメータでオーバーロードする関数があります。

テストコードを見ると、NULLを渡すケースで特殊なことをしているのが分かると思います。
MinGW付属のヘッダーでは既にNULLの定義がnullptrに変更されているので、
この違いを吸収するために `#if` を使った分岐を書いています。

内容が地味に高度なのでこのPRでテストコードの修正をスキップすると、永遠に放置される懸念があるので一緒に対応すべきだと思います。

2022-06-23 01:55 UTC, berryzplus commented
MinGWのNULL定義について認識誤りがあったので担当降ります。

2022-07-07 04:11 UTC, berryzplus approved these changes

2022-07-10 06:11 UTC, merged