ファイル読み込み時にインデントスタイルを検出して一時設定する機能と設定を追加
sakura-editor/sakura pull request #1931
Opened 2023-08-14 03:46 UTC by beru

#  PR対象

- アプリ(サクラエディタ本体)

##  カテゴリ

- 改善

##  PR の背景

#1924

##  仕様・動作説明

- タイプ別設定の「支援」に「ファイル読み込み時にインデントスタイルを検出して一時設定する」設定を追加しました。
- この設定が有効の場合、ファイル読み込み時にファイルのインデントスタイルを検出して一時的に適用するようにしました。

##  PR の影響範囲

##  テスト内容

テストに使用したファイル : [detect_indentation.zip](https://github.com/sakura-editor/sakura/files/12331327/detect_indentation.zip)

設定ON時に今回追加した機能が動作する事を確認しました。

設定OFF時に今回追加した機能が動作しない事を確認しました。

##  関連 issue, PR

#1924

##  参考資料

https://heathermoor.medium.com/detecting-code-indentation-eff3ed0fb56b

2023-08-14 03:55 UTC, beru commented
ファイル読み込み時だけでなく任意のタイミングで検出できるようにマクロ関数を追加しても良いかもしれません。

2023-08-14 07:24 UTC, berryzplus commented on sakura_core/doc/CDocEditor.cpp
> +	if (type.m_bDetectIndentationStyleOnFileLoad) {
変数名長くないです？正しい英語でなくていいはず。

m_bDetectIndentationStyleOnFileLoad
m_bDetectIndentTypeOnLoad

2023-08-14 07:24 UTC, berryzplus commented on sakura_core/sakura_rc.h
> +#define IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD 1738
識別子名長くないです？

2023-08-14 07:24 UTC, berryzplus commented on sakura_core/parse/DetectIndentationStyle.cpp
> +		// https://heathermoor.medium.com/detecting-code-indentation-eff3ed0fb56b
PRテンプレートの「仕様」欄は、参考サイトから読み取った判定条件を転記したりするためにあるはずです。

何を持って判定しとくか残したい気がします。
（自分は、多少なら判定条件漏れててよいと思っています。）

2023-08-14 08:15 UTC, beru commented on sakura_core/doc/CDocEditor.cpp
> +	if (type.m_bDetectIndentationStyleOnFileLoad) {
入力補間があるのであまり苦には感じませんでした。

もし短くするとしたら `m_bDetectIndentOnLoad` とかにすると思います。

2023-08-14 08:16 UTC, beru commented on sakura_core/sakura_rc.h
> +#define IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD 1738
ちょっと長いですね。

2023-08-14 08:46 UTC, berryzplus commented on sakura_core/parse/DetectIndentationStyle.cpp
> +		// https://heathermoor.medium.com/detecting-code-indentation-eff3ed0fb56b
検出アルゴリズム（≒検出手順）までは要らないですが

* 何を見て判定するか？
* スタイル混在の場合は何を基準にするか？

あたりを宣言しとくと揉めない気がします。

宣言がないと、後世「もっといいやり方」を思いついた人に「現行仕様の妥当性」を主張できないので。

2023-08-14 09:13 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.cpp
> +		// https://heathermoor.medium.com/detecting-code-indentation-eff3ed0fb56b
少しコメントを追加しておきますね。コード読めばそれで良い気もしますが億劫かもしれないですね。

「もっといいやり方」は色々あるだろうし思いつく人もいると思います。開発してくれるかは別ですね。あと揉めないようにその人がうまく説明してくれると良いですね。

本体に機能を入れないでプラグイン化すればやっかいな議論を避けられる気がします。ただ本体に機能が無いと嫌だという意見もあるので難しいところですね。

2023-08-14 17:01 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.cpp
> +		// https://heathermoor.medium.com/detecting-code-indentation-eff3ed0fb56b
ソースコードにコメントを追加し、PRの説明の記載も更新しました。

コメントや文字列中のインデントは無視するようにしないと誤判定してしまうケースがあると思いますが、それについてはこのPRでは対処を行いません。

タイプ別設定のカラーのプロパティシートに色々な設定がありますが、その設定を使った字句解析処理がモジュール化されていないと思うので、今回追加したインデントスタイルの検出処理で気軽に使う事が出来なそうです。

2023-08-14 22:55 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.cpp
> +				++indents[indent];
`indents` に指定できる最大のindexは TABSPACE_MAX - 1 なんですが、判定が入っていないので buffer overrun してしまいますね。

2023-08-15 04:03 UTC, berryzplus commented on sakura_core/parse/DetectIndentationStyle.cpp
> +				++indents[indent];
プロジェクト構成的には「C1網羅の単体テストコードを書いてチェックしてね」の方針を定着させようとして失敗した感じで、sonarcloudは「カバレッジ未達」を検知してくれとるわけです😃

去年あたりからGitHubのAI技術が色々進歩しているので、そういうのを併用するのも戦略としてアリかも知れません。

2023-08-15 10:02 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.cpp
> +				++indents[indent];
自分がSonarcloudで気にしていたのは Coverage and Duplications ではなくて下記の Issues の方です。

- Bugs
- Vulnerabilities
- Security Hotspots
- Code Smells

ところで先ほど cppcheck 2.11 を使ってみましたが、何故か `parse/DetectIndentationStyle.cpp` ファイルが検出対象となってくれませんでした。:sob:

2023-08-16 06:22 UTC, berryzplus commented on sakura_core/doc/CDocEditor.cpp
> +			bInsSpace = false;
```c++
swtch (indentStyle.character) {
case IndentationStyle::Character::Spaces:
    // ①Tab挿入→Space挿入の切替処理
    break;
case IndentationStyle::Character::Tabs:
    // ②Space挿入→Tab挿入の切替処理
    break;
default:
    // ③スタイルが判別不能なので切替処理なし
    break;
}
```
みたいな感じにするのはC++作法的にいかんのでしたっけ？

あと、TAB→SPACEとSPACE→TABで処理行数が異なる点が気になりました。
（判定条件もちょっと違うじゃんね。）

一般的なコードレビューだと、コード見ながら口頭説明するのが普通で、コード本体とチケットにすべての情報を含めないといかんのがPRレビューの辛いところかも。

で、理由があるなら「97行目あたりにコメントしたほうが良くないですか？」で、
理由がないなら「97行目あたりに必要そうなコードが抜けているように見えます」になる感じです。

2023-08-16 06:24 UTC, berryzplus commented on sakura_core/doc/CDocEditor.cpp
> +	if (type.m_bDetectIndentationStyleOnFileLoad) {
命名の件はスルーでもよいです。

2023-08-16 06:28 UTC, berryzplus commented on sakura_core/sakura_rc.rc
> +    CONTROL         "ファイル読み込み時にインデントスタイルを検出して一時設定する(&T)",IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,8,200,240,10
```suggestion
    CONTROL         "ファイル読み込み時にインデントスタイルを検出する(&T)",IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,8,200,240,10
```

趣味の問題かも。

2023-08-16 10:02 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.cpp
> +				++indents[indent];
cppcheck を自分でビルドしてCLIで実行してみましたが、 `parse/DetectIndentationStyle.cpp` ファイルもチェックされていたようです。cppcheck のGUIだと何も問題が見つからなかったら画面に出ないのかもしれません。

2023-08-16 10:21 UTC, beru commented on sakura_core/doc/CDocEditor.cpp
> +			bInsSpace = false;
> みたいな感じにするのはC++作法的にいかんのでしたっけ？

C++作法的にいけないという事はないと思います。コンパイルが通るのであれば何でも。
switch 文を使わないで if else if にしたのはその方が行数が短くなるのでそうしたような気がします。

> あと、TAB→SPACEとSPACE→TABで処理行数が異なる点が気になりました。

半角空白をインデントに使用する場合に下記の処理が追加で入っていますが、この処理はタブサイズを取得・設定する `ChangeTabWidth` マクロの処理を参考にしました。ここらへん [link](https://github.com/sakura-editor/sakura/blob/efff59306719526df9aef089ebfd1d4e713635af/sakura_core/macro/CMacro.cpp#L1582-L1588) です。

```cpp
			pcDoc->m_bTabSpaceCurTemp = true;
			auto& layoutMgr = pcDoc->m_cLayoutMgr;
			layoutMgr.SetTabSpaceKetas(CKetaXInt(indentStyle.tabSpace));
```

`CLayoutMgr::SetTabSpaceKetas` は `CLayoutMgr::m_nTabSpace` の値を設定する為に今回新規追加したメソッドです。

>（判定条件もちょっと違うじゃんね。）

判定条件で ` && indentStyle.tabSpace > 0` が入っているのは `DetectIndentationStyle` 関数の実装の都合で、半角空白がインデントに使われている事が分かってもインデント幅が検出出来ないケースもあるので、その場合に処理をしないようにする為に判定を入れています。

> 一般的なコードレビューだと、コード見ながら口頭説明するのが普通で、コード本体とチケットにすべての情報を含めないといかんのがPRレビューの辛いところかも。

説明があるかどうかはケースバイケースだと思います。もちろん依頼や質問すれば応えてくれると思いますが。
自分は実装内容が良く分からない事も多いのでその場合は簡単に動作確認だけして問題が無かったら Approve したりしてます。

> で、理由があるなら「97行目あたりにコメントしたほうが良くないですか？」で、
> 理由がないなら「97行目あたりに必要そうなコードが抜けているように見えます」になる感じです。

処理の説明のコメント入れた方がコードが読み易いですね。入れておきます。

2023-08-24 01:23 UTC, berryzplus requested changes
誤記見つけたので change request にしておきます。

2023-08-24 01:23 UTC, berryzplus commented on sakura_core/env/CShareData_IO.cpp
> +	cProfile.IOProfileData( pszSecName, LTEXT("bDetectIndentationStyleOnFileLoad "), types.m_bDetectIndentationStyleOnFileLoad );
誤記見つけました。

```suggestion
	cProfile.IOProfileData( pszSecName, LTEXT("bDetectIndentationStyleOnFileLoad"), types.m_bDetectIndentationStyleOnFileLoad );
```

サクラエディタでは、共有メモリ・タイプ別設定の項目を、そのままINIファイル設定項目名にする仕様です。
マージする前に適切な名前に改善できるなら対応したほうがよいと思います。
もっとも、既存の項目にも「常識の範囲で考えておかしな項目名」がたくさんあるので、修正は必須でないのかも知れません（ただ、余分な空白は削って欲しいです。）

2023-08-24 01:23 UTC, berryzplus commented on sakura_core/typeprop/CPropTypesSupport.cpp
> +	m_Types.m_bDetectIndentationStyleOnFileLoad = IsDlgButtonCheckedBool( hwndDlg, IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD );
新規追加のチェックボックスに対するヘルプIDとポップアップヘルプって対応しないんでしたっけ？

と思いました。

項目識別子(IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD)はヘルプIDテーブルにも書かないといかんので、他項目と同じくらいの長さにしておくのがベターです。

ヘルプの提供方法には課題があると思っていて、新機能導入時の対応は必須じゃないと思っています。

2023-08-24 14:03 UTC, beru commented on sakura_core/parse/DetectIndentationStyle.h
> +void DetectIndentationStyle(const CEditDoc* pcDoc, size_t nMaxLinesToCheck, IndentationStyle& style);
> - 第1引数：CEditDocのインスタンスは準グローバル変数なので、メソッド内でCEditDoc::getInstance()を呼び出せば取得できます。この引数は不要な気がします。

元々呼び出し元 (`CDocEditor::OnAfterLoad`) のローカル変数にあるのでそれを使っています。

```cpp
void CDocEditor::OnAfterLoad(const SLoadInfo& sLoadInfo)
{
	CEditDoc* pcDoc = GetListeningDoc();
```

> - 第2引数：チェック対象はファイル先頭のN行、ということでしょうか？全行を対象として良いような気がしていて、ちょっと引っかかりました。これについてはこのままで構いません。

100万行とかの異常に行数が多いファイルを読み込んだ場合に全行を対象にしてチェックしても無駄じゃないかなと思います。今の実装では最大で先頭の256行をチェック対象としていますが、この行数に何か妥当性があるわけでもないのでユーザーが調整出来るようにしても良いのかもしれません。

> - 第3引数：パラメータクラスを使っていますが、必要でしょうか？引数が多すぎる場合や特定の引数に一体として扱いたい場合、繰り返し変更されると予想される場合に便利な手法ですが、ハマりやすい手法でもあります。現時点の引数は2個なので、なんとなく微妙に思います。これについてもこのままで構いません。

`IndentationStyle` 構造体の事かと思いますが、将来的にインデントスタイルとして検出したい項目が増えた場合に構造体にしておけばメンバー追加で対応出来るので良いかなと思ってそうしました。

2023-08-24 14:11 UTC, beru commented on sakura_core/typeprop/CPropTypesSupport.cpp
> +	m_Types.m_bDetectIndentationStyleOnFileLoad = IsDlgButtonCheckedBool( hwndDlg, IDC_CHECK_DETECT_INDENTATION_STYLE_ON_FILE_LOAD );
https://sakura-editor.github.io/help/HLP000001.html

開発環境(Visual Studio)でデバッグ起動してると上のページが表示される挙動で確認がしづらいので対応する気にならないです。

2023-09-03 11:22 UTC, berryzplus commented
懸念
* 単体テストカバレッジが低い
  あとから修正かけると大変かも？という懸念がある。
* 共有メモリに追加するメンバー変数の名前が長すぎる
  おかしな名前は気付いた時点で改善していけばよいが、色々問題がある。
  ネーミングライツ、大事だよね。
  共有メモリの設定項目は外部仕様なので、変更時は互換性を意識するのがベター。
* 定期リリースのタイミングが近い。
  ここでマージすると戻れないかも知れない。

2023-09-03 11:25 UTC, berryzplus approved these changes
いろいろ懸念はあるものの、懸念内容は全体的な話でPR固有の問題ではなさそうに思います。

いったん入れてみる、で良さそうに思います。

2023-09-04 18:12 UTC, beru commented
@berryzplus さん

> 名前が長すぎる

`DetectIndentationStyle` までにして後半の `OnFileLoad` を削る変更を今から入れても良いですか？

2023-09-05 02:32 UTC, berryzplus commented
どちらでも良いです。

共有メモリのメンバー名変更はそのうちやりそうに思っていて、
「名前長いんじゃ！」とか
「スペルミスっとるやないか！」とか
「変数名全部大文字にるすとか草」とか
色々言いそうです。

入れるときに言わないのは信義則に反する気がするので言ってるだけです（approve済です。）

2023-09-05 05:36 UTC, beru commented
レビューありがとうございます。Mergeします。
もし問題が見つかったら別のPRで対応します。

2023-09-05 05:36 UTC, merged