READMEで2022対応明記
sakura-editor/sakura pull request #1953
Opened 2024-05-19 04:22 UTC by tats-u

#  PR対象

- ドキュメント(md、ヘルプファイル等)

##  カテゴリ

- 改善

##  PR の背景

#1944

2022で普通にビルドできるにもかかわらずREADMEに書いていないのはおかしいです。

なお、zlibライセンスのサクラは特例で全企業Communityを使えるのでVSの新バージョン対応を躊躇する理由はありません。
今後のコミットで2019以前を切り捨ててもいいと思います。

##  仕様・動作説明

##  PR の影響範囲

- README.md
- vcx-props/project-PlatFormToolset.md

##  テスト内容

両ファイルを直接・または差分を開いて妥当性確認

##  関連 issue, PR

- #1944
- #1872 (https://github.com/sakura-editor/sakura/pull/1872/commits/93cf3f3eacfed6a4d0a2c30d5445b53b2599db3c)

##  参考資料

https://visualstudio.microsoft.com/ja/license-terms/vs2022-ga-community/

2024-05-19 04:23 UTC, tats-u commented
#1952 に乗っかる形に修正します

2024-05-19 05:06 UTC, tats-u commented
#1952 との差分： https://github.com/berryzplus/sakura-editor/pull/34

2024-05-29 00:01 UTC, berryzplus commented
あくまで個人的な感想ですが、
バージョン書きたくないです。
（どうせ2025出るし、あっという間に2028出ますから。）

2024-05-29 13:11 UTC, tats-u commented
@berryzplus 表以外でのバージョン表記は徹底排除しました。2025が出ても表の更新とCommunity板ライセンスへのリンク差し替えだけで済みます。

2024-06-03 02:05 UTC, berryzplus approved these changes

2024-06-03 02:05 UTC, berryzplus commented on README.md
> +#### Visual Studio 2017 以降共通
これでも意味は通るはず。
```suggestion
#### Visual Studio 共通
```

2024-06-03 03:44 UTC, tats-u commented on README.md
> +#### Visual Studio 2017 以降共通
その路線で行くならば「全バージョン共通」の方が良さげな気がしますがいかがでしょうか？

2024-06-04 00:01 UTC, berryzplus commented on README.md
> +#### Visual Studio 2017 以降共通
* 全バージョン共通 `Visual Studio 2015`でもできる感じに見える。 vs2015はC++17に非対応が。検証していないがたぶんビルドできない。
* 共通 「バージョン間共通」が伝わらない懸念がある。
* 対応バージョン共通 妥協表記。もっといいのあるかも。

2024-06-04 03:32 UTC, tats-u commented on README.md
> +#### Visual Studio 2017 以降共通
- 全対応バージョン
- 対応バージョン共通
- 全対応バージョン共通

この3つぐらいですね

2024-06-07 00:10 UTC, berryzplus requested changes
TOC（≒目次？）の変更もお願いします。

2024-06-07 10:00 UTC, tats-u commented
@berryzplus  修正しました

2024-06-07 10:01 UTC, tats-u commented
コミットのスカッシュが必要ならばお申し付けください

2024-06-08 03:33 UTC, berryzplus approved these changes

2024-06-14 12:43 UTC, merged