クリッカブルURLの仕様変更に対するロールバック
sakura-editor/sakura pull request #1965
Opened 2024-07-15 13:45 UTC by beru

#  PR対象

- アプリ(サクラエディタ本体)

##  カテゴリ

- 不具合修正

##  PR の背景

#1915 に対応するPRです。

2021年7月にmergeされた下記のコミット内容をrevertする事で「ブラウズ」と「クリッカブルURL」の挙動を元に戻して関連付けされたアプリケーションで開くことが出来るようにしました。

9a0ed9f1ad0d27f016f37912c8753dd0ae623301
f44540f93b644348f1498314efd68cc55a0b28d1
f902c3c093824d8f0bcc089f67edde723eb5ead4
fdac3cac9eacb6db8c61469e090a50a08ef5ebb3
581c19d3bfda92a0789f0d29b0a177069539cac3
9169b13ab370c1f4e27cffb67613e787350fc78e
8501185e6f03d0ad6f29f09152a8618db9bea62b

##  仕様・動作説明

##  PR の影響範囲

##  テスト内容

##  関連 issue, PR

#1915 
#1702
#1705
#1708 

##  参考資料

2024-07-18 03:35 UTC, berryzplus requested changes
issue側で結論出てないのでPR作成は時期尚早と思います。

2024-07-18 13:13 UTC, beru commented
> issue側で結論出てないのでPR作成は時期尚早と思います。

#1915 で議論が今後行われるのかは良く分かりませんが、仮に議論が行われなくて何も対応がされないと、問題指摘があっても放置になるのでちょっとかわいそうではありますね。ただ自分がここで呟いても議論が進む事は無いでしょうが。。

今思うと #1702 と #1708 の変更ではヘルプに書かれている説明から外れた変更になってしまっているので（レビュー時にそこを指摘して）もし仕様変更するならヘルプの記載も同時に変えるようにするべきだったと思います。

#1702 と #1708 で加えた変更を設定で有効無効切り替えられるようにする事は可能ですが、ひとまず revert しても良いのかなとた。

2024-07-20 02:13 UTC, berryzplus commented
結局「こまってない」なんですよね。

優先度は下げてよいと思います。

2024-07-20 11:49 UTC, beru commented
> 結局「こまってない」なんですよね。

私は困ってないです。takeyamajpさんとかは困っているというか仕様変更されて面倒くさくなっていると思いますが。

> 優先度は下げてよいと思います。

最近CrowdStrikeによって引き起こされたBSODに比べると緊急度は高くないと思います。

2024-08-10 23:55 UTC, yuksiy commented
初めまして。yuksiyと申します。

> > 結局「こまってない」なんですよね。
> 
> 私は困ってないです。takeyamajpさんとかは困っているというか仕様変更されて面倒くさくなっていると思いますが。

私は困っている者の1人です。
念のため、困っている内容を具体的に書かせて頂くと、
v2.4.1までは「[sample.txt](https://github.com/user-attachments/files/16571154/sample.txt)」ようなファイルをサクラエディタで開き、
画面中の任意フォルダ名の箇所をダブルクリックすると、エクスプローラで該当フォルダが開かれ、
任意ファイル名の箇所をダブルクリックすると、関連付けられた任意アプリで該当ファイルが開かれていましたが、
v2.4.2になってからはフォルダもファイルも開けなくなってしまったことです。

困ったと同時に、不便になったと感じたため、v2.4.2の使用を中止して、
v2.4.1に戻して現在まで使い続けている状況です。
ですので、本PRがマージされるとありがたいです。

ただ個人的には、一旦v2.4.1に戻すことによって困っていたことは回避できているので、
berryzplusさんやberuさんの書かれているように、優先度低めでよいと思います。

2024-09-07 02:00 UTC, berryzplus commented
可能なrevert戦略についてメモっておきます。

## 目的
変更前に戻す。

変更前とは aad0b655196fb9d4ff52495e2f3fa41b2cac7772 のこと。
（#1703 のマージコミット。）

## revertイメージ
以下のコミットで適用された変更がすべて「変更前の状態」になったことを証明する。

![image](https://github.com/user-attachments/assets/3e4d0103-8af8-42ff-8741-662d866a2bf2)

対象ファイルこんだけ。
![image](https://github.com/user-attachments/assets/856c1297-7fb4-4d8a-b023-4c2c9e56ed47)

※この情報は本来、revertを要求した issue #1915 の作成者が用意すべき。

## 考慮事項
だいぶ古いPull Requestなので、revert対象ファイルに対して「その後の変更」が加えられている可能性あり。

このPRではおそらくそれも考慮済みだが、レビュアーが全部自分で確認しなおさないといけない。

で、実際に確認していくと、自分でPR作ったほうが早いくらいの作業量になる。

分類は次のような感じ。
* このファイルは純粋revertなので、変更前と完全一致。
* このファイルは後日別件で修正が入ったので、修正前とここだけ違う。
* このファイルはrevertとは関係ないが、後日別件で入った修正を受けてここを変える必要がある。

まとめると「必要な情報が足りないのでレビューできない」になるんだけど
不足情報を @beru さんに要求するのは「筋違い」のような。

「俺ならできるぜ」みたいなノリになれる人が居れば、レビュー敢行を否定するものではない。

2025-02-08 02:28 UTC, berryzplus approved these changes

2025-02-08 02:43 UTC, berryzplus commented
@beru マージしてしまいましょう。

PRが評価不能なことに変わりありませんが
問題の仕様変更を残したとしても
CEditViewクラスを整理すると消えそうなので。

2025-02-08 05:55 UTC, merged